#!/bin/bash -e
  #Get parameters
  vm_ip=$1
  vm_user=$2
  log_folder=$3
  tests_status=$4

  #---------------------------------------------------------------------------------------------------------------------
  echo -e "\e[0m"
  echo "***************************"
  echo "*** Tests Post-Process  ***"
  echo "***************************"
  echo -e "\e[0m"

  # Get logs
  echo " - Retrieving logs..."
  scp -r -o StrictHostKeyChecking=no ${vm_user}@${vm_ip}:/home/${vm_user}/tests/logs ${log_folder}


  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  # All the clean process has been erased and moved to the clean script before performing snapshot
  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


  # Clean hosts
  #echo "-- Cleaning hosts..."
  #ssh -t -t -o StrictHostKeyChecking=no -o BatchMode=yes -o ChallengeResponseAuthentication=no ${vm_user}@${vm_ip} "sudo sh /home/${vm_user}/tests/configure_hosts_remove"

  # Clean logs
  #echo " - Cleaning VM..."
  #ssh -t -t -o StrictHostKeyChecking=no -o BatchMode=yes -o ChallengeResponseAuthentication=no ${vm_user}@${vm_ip} "rm -rf /home/${vm_user}/tests"
  #ssh -t -t -o StrictHostKeyChecking=no -o BatchMode=yes -o ChallengeResponseAuthentication=no ${vm_user}@${vm_ip} "rm -rf /home/${vm_user}/.COMPSs"
  #ssh -t -t -o StrictHostKeyChecking=no -o BatchMode=yes -o ChallengeResponseAuthentication=no ${vm_user}@${vm_ip} "rm -rf /home/${vm_user}/.m2"

  # Clean history
  #ssh -t -t -o StrictHostKeyChecking=no -o BatchMode=yes -o ChallengeResponseAuthentication=no ${vm_user}@${vm_ip} "rm -f /home/${vm_user}/.bash_history"
 
  # Prepare machine for snapshot (if needed)
  #echo " - Preparing VM for snapshot..."
  #if [ "${tests_status}" == "ok" ]; then
    #ssh -t -t -o StrictHostKeyChecking=no -o BatchMode=yes -o ChallengeResponseAuthentication=no ${vm_user}@${vm_ip} "sudo rm -f /home/${vm_user}/.ssh/known_hosts"
    #ssh -t -t -o StrictHostKeyChecking=no -o BatchMode=yes -o ChallengeResponseAuthentication=no ${vm_user}@${vm_ip} "sudo rm -f /etc/resolv.conf"  
    #ssh -t -t -o StrictHostKeyChecking=no -o BatchMode=yes -o ChallengeResponseAuthentication=no ${vm_user}@${vm_ip} "sudo rm -f /home/${vm_user}/.ssh/authorized_keys"
  #fi


  # All process OK. Exit
  echo " OK!"
  exit 0

