#!/bin/bash -e

  distribution=$1
  arch=$2
  COMPSs_version=$3

  release_types="unstable testing stable"
  trunk_rel_path=../../../../
  packages_target=${trunk_rel_path}/builders/packages/
  PKGNAME=$(cat $arch/control | grep 'Package:' | tail -n 1 | cut -d ":" -f2- | cut -d " " -f2-)

  echo " "
  echo "* Erasing previous tmp Files..."
  rm -rf tmp/

  echo " "
  echo "* Compiling sources..."
  cd ${trunk_rel_path}/compss/runtime/adaptors
  mvn -U clean install
  cd -

  echo " "
  echo "* Create deployment folders"
  COMPSs_target=tmp/opt/COMPSs
  mkdir -p ${COMPSs_target}
  mkdir -p ${COMPSs_target}/Runtime/scripts
  mkdir -p ${COMPSs_target}/Runtime/adaptors
  mkdir -p ${COMPSs_target}/Runtime/configuration/log

  echo " "
  echo "* Copy deployment files"
  #Doc
  cp ${trunk_rel_path}/changelog ${COMPSs_target}
  cp ${trunk_rel_path}/LICENSE ${COMPSs_target}
  cp ${trunk_rel_path}/NOTICE ${COMPSs_target}
  cp ../README ${COMPSs_target}
  cp ${trunk_rel_path}/RELEASE_NOTES ${COMPSs_target}
  #Loggers
  cp ${trunk_rel_path}/compss/runtime/config/log/COMPSsWorker-log4j.off ${COMPSs_target}/Runtime/configuration/log/
  cp ${trunk_rel_path}/compss/runtime/config/log/COMPSsWorker-log4j.debug ${COMPSs_target}/Runtime/configuration/log/
  #Scripts
  cp -r ${trunk_rel_path}/compss/runtime/scripts/* ${COMPSs_target}/Runtime/scripts/
  #Adaptors
  path_source="${trunk_rel_path}/compss/runtime/adaptors"
  path_target="${COMPSs_target}/Runtime/adaptors"
  adaptors=$(ls ${path_source})
  for adaptor in $adaptors; do
    if [ "$adaptor" != "commons" ] && [ "$adaptor" != "pom.xml" ]; then
      mkdir ${path_target}/$adaptor
      if [ -d "${path_source}/$adaptor/worker/" ]; then
        mkdir ${path_target}/$adaptor/worker
        cp ${path_source}/$adaptor/worker/*.jar ${path_target}/$adaptor/worker
      fi
      if [ -f ${path_source}/$adaptor/worker/properties ]; then
        cp ${path_source}/$adaptor/worker/properties ${path_target}/$adaptor/worker
      fi
      if [ -d "${path_source}/$adaptor/scripts/" ]; then
        mkdir -p ${COMPSs_target}/Runtime/scripts/system/adaptors/$adaptor/
        cp -r ${path_source}/$adaptor/scripts/* ${COMPSs_target}/Runtime/scripts/system/adaptors/$adaptor/
      fi
    fi
  done
  find ${COMPSs_target}/Runtime/adaptors -name pom.xml | xargs rm -f

  for rt in ${release_types}; do
    echo " "
    echo "* Creating package structure for ${rt}..."
    mkdir -p tmp/DEBIAN
    chmod 755 .
    cp $arch/control tmp/DEBIAN/control
    cp docs tmp/DEBIAN/docs
    cp compat tmp/DEBIAN/compat
    cp conffiles tmp/DEBIAN/conffiles
    cp preinst tmp/DEBIAN/preinst
    cp postinst tmp/DEBIAN/postinst
    cp prerm tmp/DEBIAN/prerm
    cp postrm tmp/DEBIAN/postrm
    PKGVERSION=${COMPSs_version}.${distribution}
    if [ "$rt" != "stable" ]; then
      PKGVERSION="${COMPSs_version}.${distribution}-${rt}"
    fi
    sed -i '/Version:/cVersion: '${PKGVERSION}'' tmp/DEBIAN/control

    echo "  * Generating md5sums file..." 
    cd tmp/
    files=$(find . -type f | grep -v DEBIAN | cat)
    if [ "${files}" != "" ]; then
      md5sum ${files} > DEBIAN/md5sums
    else 
      touch DEBIAN/md5sums
    fi
    cd ../
    echo Installed-Size: $(du tmp/ | tail -1 | awk '{print $1}') >> tmp/DEBIAN/control

    echo "  * Generating DEB package..."
    dpkg -b tmp ${PKGNAME}_${PKGVERSION}_${arch}.deb
    if [ $? -ne 0 ]; then
      echo "Error creating deb package"
      exit 1
    fi

    echo "  * Cleaning tmp files..."
    rm -rf tmp/DEBIAN

    echo "  * Moving built DEB package to final location..."
    mkdir -p ${packages_target}/${distribution}/$PKGNAME 
    mv ${PKGNAME}_${PKGVERSION}_${arch}.deb ${packages_target}/${distribution}/$PKGNAME
  done

  # Clean COMPSs tmp files
  echo " "
  echo "* Cleaning COMPSs tmp files"
  rm -rf tmp/

