#!/usr/bin/env python3
#
#  Copyright 2002-2024 Barcelona Supercomputing Center (www.bsc.es)
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
import socket
import time
import typing
from pathlib import Path
from urllib.parse import urlsplit

from provenance.models.Parameter import Parameter
from provenance.models.Task import Task
from provenance.utils.datatype_mapping import map_datatype


def process_task_parameters(
        formal_params: list,
        actual_params: dict,
        method_name: str
) -> list[Parameter]:
    """

    :param formal_params:
    :param actual_params:
    :param method_name:
    :return:
    """
    parameters = []

    for formal_param in formal_params:
        name, direction, dtype = formal_param.split(".")
        if name in actual_params:
            value = actual_params[name]
        else:
            value = "None"

        parameters.append(
            Parameter(name=name, method=method_name, direction=direction, dtype=map_datatype(dtype), value=value)
        )

    return parameters


# TODO: rename this (or change logic), since it is not only file processing anymore
def process_accessed_files(dp_log: Path) -> typing.Tuple[list, list, list]:
    """
    Process all the files the COMPSs workflow has accessed. They will be the overall inputs needed and outputs
    generated of the whole workflow.
    - If a task that is an INPUT, was previously an OUTPUT, it means it is an intermediate file, therefore we discard it
    - Works fine with COLLECTION_FILE_IN, COLLECTION_FILE_OUT and COLLECTION_FILE_INOUT

    :param dp_log: Path object to the dataprovenance.log file

    :returns: List of Inputs and Outputs of the COMPSs workflow
    """

    part_time = time.time()

    inputs = set()
    outputs = set()
    l_tasks = []

    with open(dp_log, "r", encoding="UTF-8") as dp_file:
        ins_of_current_task = []
        outs_of_current_task = []
        actual_params = {}
        for line in dp_file:
            line_record = line.rstrip().split(" ")
            # Collect actual parameters:
            if line_record[0] == "parameter":
                actual_params[line_record[1]] = line_record[3]
                # Handle files separately:
                if line_record[2] in ["FILE_T", "DIRECTORY_T"]:
                    if (
                            line_record[4] == "IN" or line_record[4] == "IN_DELETE"
                    ):  # Can we have an IN_DELETE that was not previously an OUTPUT?
                        if (
                                line_record[3] not in outputs
                        ):  # A true INPUT, not an intermediate file
                            inputs.add(line_record[3])
                        ins_of_current_task.append(line_record[3])
                        #  Else, it is an intermediate file, not a true INPUT or OUTPUT. Not adding it as an input may
                        # be enough in most cases, since removing it as an output may be a bit radical
                        #     outputs.remove(line_record[0])
                    elif line_record[4] == "OUT":
                        outputs.add(line_record[3])
                        outs_of_current_task.append(line_record[3])
                    else:  # INOUT, COMMUTATIVE, CONCURRENT
                        if (
                                line_record[3] not in outputs
                        ):  # Not previously generated by another task (even a task using that same file), a true INPUT
                            inputs.add(line_record[3])
                        ins_of_current_task.append(line_record[3])
                        # else, we can't know for sure if it is an intermediate file, previous call using the INOUT may
                        # have inserted it at outputs, thus don't remove it from outputs
                        outputs.add(line_record[3])
                        outs_of_current_task.append(line_record[3])

            # Collect formal parameters and return values (TODO):
            if line_record[0] == "Task":
                task_id = line_record[1]
                signature = line_record[2]
                file_name, method_name = line_record[2].split(".")
                formal_params = line_record[3].split("::")
                params = process_task_parameters(formal_params, actual_params, method_name)
                l_tasks.append(
                    Task(tid=task_id,
                         signature=signature,
                         method_name=method_name,
                         file_name=file_name,
                         params=params
                ))
                ins_of_current_task, outs_of_current_task = [], []
                actual_params = {}
            # else dismiss the line

    l_ins = list(inputs)
    l_ins.sort()  # Put directories first
    l_outs = list(outputs)
    l_outs.sort()  # Put directories first

    # Fix dir:// references, they don't end with slash '/' at dataprovenance.log
    for data_list in [l_ins, l_outs]:
        for i, item in enumerate(data_list):
            url_parts = urlsplit(item)
            if url_parts.scheme == "dir":
                data_list[i] = "dir://" + socket.gethostname() + url_parts.path + "/"
            else:
                break  # File has been reached, all directories have been treated
        data_list.sort()

    print(f"PROVENANCE | COMPSs runtime detected inputs ({len(l_ins)})")
    print(f"PROVENANCE | COMPSs runtime detected outputs ({len(l_outs)})")
    print(
        f"PROVENANCE | dataprovenance.log processing TIME: "
        f"{time.time() - part_time} s"
    )

    return l_ins, l_outs, l_tasks
