#!/usr/bin/env python3
#
#  Copyright 2002-2026 Barcelona Supercomputing Center (www.bsc.es)
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
import socket
import time
import typing
import uuid
import sys
from pathlib import Path
from provenance.models.Parameter import Parameter
from provenance.models.Task import Task
from provenance.utils.type_mapping import map_datatype
from urllib.parse import urlsplit

STATUS_PRIORITY = {
    "UNKNOWN": -1,
    "CANCELED": 0,
    "FAILED": 1,
    "RECOVERED": 2,
    "FINISHED": 3,
}


def is_future_object(name: str):
    """
    Checks whether the given string format corresponds to a COMPSs future object
    """
    name = name.rsplit("-", 1)[
        0
    ]  # Remove the last trailing character that is added to the UUID
    try:
        val = uuid.UUID(name)
        return True
    except ValueError:
        return False

def classify_file(accessMode: str, param_path: str, inputs: set, outputs: set) -> None:
    """
    Classifies a file parameter as input, output, or intermediate based on its AccessMode.
    Updates the inputs and outputs sets accordingly.
    """
    def handle_read():
        if param_path not in outputs: # A true INPUT, not an intermediate file
            inputs.add(param_path)

    def handle_generate():
        outputs.add(param_path)       

    def handle_update():
        if param_path not in outputs: # Not previously generated by another task, a true INPUT
            inputs.add(param_path)
        # else, we can't know for sure if it is an intermediate file since a previous call using
        # the INOUT case may have inserted it at outputs, thus don't remove it from outputs
        outputs.add(param_path)

    def handle_read_and_delete():
        # Can we have an IN_DELETE that was not previously an OUTPUT? A user could do this
        # if a large file is downloaded and only parts of it are interesting
        # TODO: right now we keep it as an overall input, but it should probably be removed
        # from both inputs and outputs, since it will not exist at the end of the execution
        # (i.e., provenance generation time)
        if param_path not in outputs:  # First time referenced
            inputs.add(param_path)
        else:
            # This else assumes the following scenario: file A is generated by task 1 (an output)
            # and later consumed by task 2 with READ_AND_DELETE, which deletes it after use.
            # Since the file no longer exists once the workflow finishes, it should not remain
            # listed as a workflow output, so we remove it from 'outputs' here.
            outputs.remove(param_path)        

    ACCESS_MODE_HANDLERS = {
        "READ": handle_read,
        "READ_AND_DELETE": handle_read_and_delete,
        "GENERATE": handle_generate,
        "UPDATE": handle_update,
        "CONCURRENT_UPDATE": handle_update,
        "COMMUTATIVE_UPDATE": handle_update,
    }

    handler = ACCESS_MODE_HANDLERS.get(accessMode)

    if handler:
        handler()
    else:
        # Someone has defined a new AccessMode in the runtime, and it is not covered here
        # We record it at compss/runtime/engine/src/main/java/es/bsc/compss/api/impl/WorkflowImpl.java
        print(f"FATAL ERROR: a new AccessMode has been defined in the runtime ({accessMode}) and it is not understood in the provenance generation")
        print(f"Check AccessMode codes in the COMPSs runtime")
        sys.exit(-1)            

def process_master_log(dp_log: Path) -> typing.Tuple[list, list, list]:
    """
    Process all the files the COMPSs workflow has accessed. They will be the overall inputs needed and outputs
    generated of the whole workflow.
    - If a task that is an INPUT, was previously an OUTPUT, it means it is an intermediate file, therefore we discard it
    - Works fine with COLLECTION_FILE_IN, COLLECTION_FILE_OUT and COLLECTION_FILE_INOUT

    :param dp_log: Path object to the dataprovenance.log file

    :returns: List of Inputs and Outputs of the COMPSs workflow
    """

    part_time = time.time()

    inputs = set()
    outputs = set()
    tasks = {"master": Task(tid="master", status="FINISHED")}

    task_params: dict[str, dict] = (
        {}
    )  # Ad-hoc. Does not follow Parameter class defined in Parameter.py

    with open(dp_log, "r", encoding="UTF-8") as dp_file:
        for line in dp_file:
            line_record = line.rstrip().split(" ")
            
            if line_record[0] == "parameter":
                param_name, param_type, param_value, accessMode = (
                    line_record[1],
                    line_record[2],
                    line_record[3],
                    line_record[4],
                )

                param_name = param_name.replace("#kwarg_", "")

                if param_name not in task_params:
                    task_params[param_name] = {
                        "type": param_type,
                        "accessMode": accessMode,
                        "value": param_value,
                        "array": False,
                    }

            if line_record[0] == "file":
                param_name, param_type, param_value, accessMode = (
                    line_record[1],
                    line_record[2],
                    line_record[3],
                    line_record[4],
                )

                param_name = param_name.replace("#kwarg_", "")

                # Skip individual elements of a collection starting with @
                if "@" in param_name:
                    continue

                if param_name not in task_params:
                    task_params[param_name] = {
                        "type": param_type,
                        "accessMode": accessMode,
                        "value": param_value,
                        "array": False,
                    }
                else:
                    existing = task_params[param_name]["value"]
                    if isinstance(existing, list):
                        existing.append(param_value)
                    else:
                        task_params[param_name]["value"] = [existing, param_value]
                    # Force to add "multipleValues" property to COMPSs 'COLLECTION_T' type
                    task_params[param_name]["array"] = True

                # Handle inputs/outputs classification
                if param_type in ["FILE_T", "DIRECTORY_T"] and not is_future_object(param_value):
                    classify_file(accessMode, param_value, inputs, outputs)  
                    #classify_file("STOP", param_value, inputs, outputs) # With this line, we are checking the fatal 
                                                                        # error in case we have a new accessMode not correclty added to the code

            # -------------------- TASK DEFINITION -------------------- #
            # Here we add all the parameters to the task. Their types and values are not yet final,
            # since we only have the serialized version and the COMPSs type at this point
            if line_record[0] == "task":
                task_id = line_record[1]

                if line_record[2] == "status" and task_id in tasks:
                    new_status = line_record[3]

                    # Priority checking is needed because resubmitted tasks appear with more statuses
                    if (
                        STATUS_PRIORITY[new_status]
                        > STATUS_PRIORITY[tasks[task_id].status]
                    ):
                        tasks[task_id].status = new_status

                    continue

                signature = line_record[2]  # Signature = filename + methodname
                file_name, method_name = line_record[2].rsplit(".", 1)

                current_task = Task(
                    tid=task_id,
                    signature=signature,
                    method=method_name,
                    sourcefile=file_name,
                )

                raw_params = line_record[3].split("::") if line_record[3] else []

                for p in raw_params:
                    pname, ptype, accessMode = p.split(".")
                    pname = pname.replace("#kwarg_", "")
                    if pname not in task_params:
                        task_params[pname] = {
                            "type": ptype,
                            "accessMode": accessMode,
                            "value": "",
                            "array": False,
                        }

                for pname, p_dict in task_params.items():
                    ptype = p_dict["type"]
                    ptype = map_datatype(ptype)
                    accessMode = p_dict["accessMode"]
                    pvalue = p_dict["value"]
                    parray = p_dict["array"]

                    if accessMode in ["READ", "UPDATE", "READ_AND_DELETE", "CONCURRENT_UPDATE", "COMMUTATIVE_UPDATE"]:
                        current_task.in_params[pname] = Parameter(
                            name=pname,
                            method=method_name,
                            accessMode="IN",
                            dtype=ptype,
                            value=pvalue,
                            is_array=parray,
                        )

                    if accessMode in ["GENERATE", "UPDATE", "CONCURRENT_UPDATE", "COMMUTATIVE_UPDATE"]:
                        current_task.out_params[pname] = Parameter(
                            name=pname,
                            method=method_name,
                            accessMode="OUT",
                            dtype=ptype,
                            value=pvalue,
                            is_array=parray,
                        )

                tasks[task_id] = current_task

                # Reset for the next task scope
                task_params.clear()

            # -------------------- WORKFLOW STATUS -------------------- #
            if line_record[0] == "master":
                tasks["master"].status = line_record[2]

    l_ins = list(inputs)
    l_ins.sort()  # Put directories first
    l_outs = list(outputs)
    l_outs.sort()  # Put directories first

    # Fix dir:// references, they don't end with slash '/' at dataprovenance.log
    for data_list in [l_ins, l_outs]:
        for i, item in enumerate(data_list):
            url_parts = urlsplit(item)
            if url_parts.scheme == "dir":
                data_list[i] = "dir://" + socket.gethostname() + url_parts.path + "/"
            else:
                break  # File has been reached, all directories have been treated
        data_list.sort()

    print(f"PROVENANCE | COMPSs runtime detected inputs ({len(l_ins)})")
    print(f"PROVENANCE | COMPSs runtime detected outputs ({len(l_outs)})")
    print(
        f"PROVENANCE | dataprovenance.log processing TIME: "
        f"{time.time() - part_time} s"
    )

    return l_ins, l_outs, tasks
