interface type_tests {

    //Test with long, int, short and char
    //----------------------------------------------------------------------

    void split_long(in long a, out int[2] pair);

    void split_int(in int N, in int M, in int[N] a, out short[M] pair);

    void split_short(in int N, in int M, in short[N] a, out char[M] pair);

    //----------------------------------------------------------------------

    //Test with long and long*
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------

    //Test with int and int*
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    

    //Test with short and short*
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------


    //Test with char and char*
    //----------------------------------------------------------------------

    void make_string(in char a, in char b, in char c, out char[4] str);

    void split_string(in char[4] str);
    
    //----------------------------------------------------------------------

};
