#!/bin/bash

GENERATORS_DIR=$(dirname "$0")
. $GENERATORS_DIR/aux-functions

NUM_WORKERS=$1
COMPUTING_UNITS=$2
MEMORY=$3

echo -e "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?> \n"
echo -e "<ResourcesList> \n"

for i in $(seq 1 $NUM_WORKERS); do  
    echo -e "\
    <ComputeNode Name=\"worker$i\"> \n\
        <Processor Name=\"MainProcessor\"> \n\
            <ComputingUnits>${COMPUTING_UNITS}</ComputingUnits> \n\
        </Processor> \n\
        <Memory> \n\
            <Size>${MEMORY}</Size> \n\
        </Memory> \n\
        <Adaptors> \n\
            <Adaptor Name=\"integratedtoolkit.nio.master.NIOAdaptor\"> \n\
                <SubmissionSystem> \n\
                    <Interactive/> \n\
                </SubmissionSystem> \n\
                <Ports> \n\
                    <MinPort>$((40000 + 2*($i-1) + 1))</MinPort>\n \
                    <MaxPort>$((40000 + 2*($i-1) + 2))</MaxPort>\n \
                </Ports> \n\
            </Adaptor> \n\
            <Adaptor Name=\"integratedtoolkit.gat.master.GATAdaptor\"> \n\
                <SubmissionSystem> \n\
                    <Batch> \n\
                        <Queue>sequential</Queue> \n\
                    </Batch> \n\
                    <Interactive/> \n\
                </SubmissionSystem> \n\
                <BrokerAdaptor>sshtrilead</BrokerAdaptor> \n\
            </Adaptor> \n\
        </Adaptors> \n\
    </ComputeNode> \n\
"
done
echo "</ResourcesList>"
