//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.17 at 12:37:00 PM CET 
//


package es.bsc.compss.types.project.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ImageType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ImageType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="unbounded" minOccurs="2"&gt;
 *         &lt;element name="InstallDir" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="WorkingDir" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="User" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Application" type="{}ApplicationType" minOccurs="0"/&gt;
 *         &lt;element name="LimitOfTasks" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="Package" type="{}PackageType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Adaptors" type="{}AdaptorsListType" minOccurs="0"/&gt;
 *       &lt;/choice&gt;
 *       &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ImageType", propOrder = {
    "installDirOrWorkingDirOrUser"
})
public class ImageType {

    @XmlElementRefs({
        @XmlElementRef(name = "Adaptors", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "User", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Package", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "InstallDir", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "LimitOfTasks", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "WorkingDir", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Application", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> installDirOrWorkingDirOrUser;
    @XmlAttribute(name = "Name", required = true)
    protected String name;

    /**
     * Gets the value of the installDirOrWorkingDirOrUser property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the installDirOrWorkingDirOrUser property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInstallDirOrWorkingDirOrUser().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link AdaptorsListType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link PackageType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link ApplicationType }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getInstallDirOrWorkingDirOrUser() {
        if (installDirOrWorkingDirOrUser == null) {
            installDirOrWorkingDirOrUser = new ArrayList<JAXBElement<?>>();
        }
        return this.installDirOrWorkingDirOrUser;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
