#!/bin/bash -e
 
  #############################################################
  # Name: buildMT_aux
  # Description: SCRIPT FOR LOCAL COMPSs BUILD in MinoTauro
  # Parameters: <targetDir> Base Target Installation folder
  #
  # ATTENTION: DO NOT EXECUTE THIS FILE. IT IS AUTOMATICALLY 
  #            EXECUTED FROM buildMT script
  #############################################################

  usage() {
    echo "Incorrect number of parameters"
    echo " Usage: buildMT_aux <FullTargetPath>"
    echo " "
    exit 1
  }

  ####################
  # MAIN
  ####################
  # Get parameters
  if [ $# -ne 1 ]; then
    usage
  fi

  # SET SCRIPT VARIABLES
  targetDir=$1
  scriptDir=$(dirname $0)

  modules="java gcc/7.1.0 mkl/2018.1 python/2.7.14 bullxmpi/bullxmpi-1.2.9.1 boost/1.67.0"
  additionalExports="export BOOST_CPPFLAGS=-I\${BOOST_INCLUDE} PATH=/apps/CEPBATOOLS/deps/libxml2/2.9.4/bin:$PATH"
  queues_cfg="mt.cfg"
  extrae_with_openmpi="false"
  openmpi_version=""
  extrae_with_impi="false"
  impi_version=""

  ${scriptDir}/buildSC_aux ${targetDir} "${modules}" "${additionalExports}" "${queues_cfg}" "${extrae_with_openmpi}" "${openmpi_version}" "${extrae_with_impi}" "${impi_version}"
