#!/bin/bash -e

  #############################################################
  # Name: buildMT_aux
  # Description: SCRIPT FOR LOCAL COMPSs BUILD in MinoTauro
  # Parameters: <targetDir> Base Target Installation folder
  #
  # ATTENTION: DO NOT EXECUTE THIS FILE. IT IS AUTOMATICALLY
  #            EXECUTED FROM buildMT script
  #############################################################

  usage() {
    echo "Incorrect number of parameters"
    echo " Usage: buildMT_aux <FullTargetPath>"
    echo " "
    exit 1
  }

  ####################
  # MAIN
  ####################
  # Get parameters
  if [ $# -ne 1 ]; then
    usage
  fi

  # SET SCRIPT VARIABLES
  targetDir=$1
  SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

  # DEFINE MODULES
  modules="intel java gcc/9.2.0 mkl/2018.1 bullxmpi/bullxmpi-1.2.9.1 boost/1.67.0 dlb/git"
  unload_before_python="ignore"
  run_before_py3_modules="module load cuda/10.1"
  py3_modules="python/3.7.10"
  run_before_py3_other_modules="ignore"
  py3_other_modules="python/3.8.2"

  # DEFINE CONFIGURATION PARAMETERS
  #(Environment vars must be scaped to get the correct value if not it could take a value previous to load the modules)
  # WARN: Add autotools and libxml from BSC_TOOLS due to compilation issues with Extrae
  additionalExports="export BOOST_CPPFLAGS=-I\${BOOST_INCLUDE} PATH=/apps/BSCTOOLS/deps/libxml/2.9.4/bin:/apps/BSCTOOLS/deps/autotools/bin:\$PATH"
  additional_module_use_folder="ignore"
  queues_cfg="mt.cfg"
  extrae_with_openmpi="false"
  openmpi_version=""
  extrae_with_impi="false"
  impi_version=""
  autoparallel="false"
  c_binding="true"
  extrae_no_mpi="true"
  r_binding="false"

  # CALL buildSC_aux
  "${SCRIPT_DIR}"/buildSC_aux "${targetDir}" "${modules}" "${unload_before_python}" "${run_before_py3_modules}" "${py3_modules}" "${run_before_py3_other_modules}" "${py3_other_modules}" "${additionalExports}" "${additional_module_use_folder}" "${queues_cfg}" "${extrae_with_openmpi}" "${openmpi_version}" "${extrae_with_impi}" "${impi_version}" "${autoparallel}" "${c_binding}" "${extrae_no_mpi}" "${r_binding}"
  ev=$?

  # End
  if [ $ev -ne 0 ]; then
    echo "ERROR: Exception in auxiliar script"
    exit $ev
  fi
  exit 0
