#!/bin/bash -e
  
  #Obtain parameter
  source_base_dir=$1
  target_base_dir=$2
  
  # Compile and deploy binary
  mkdir ${target_base_dir}/bin/
  mpicc -o ${target_base_dir}/bin/matmul ${source_base_dir}/src/main/c/matmul.c
  
  # Copy files
  cp -f ${source_base_dir}/target/matmul.jar ${target_base_dir}/matmul.jar

  cp -f ${source_base_dir}/project.xml ${target_base_dir}/project.xml                  
  cp -f ${source_base_dir}/resources.xml ${target_base_dir}/resources.xml
  
  cp -f ${source_base_dir}/execution ${target_base_dir}/execution
  cp -f ${source_base_dir}/result ${target_base_dir}/result 
 
