#!/bin/bash

  # Obtain parameters
  COMPSs_exec=$1
  comm=$2
  base_app_dir=$3
  COMPSs_log_folder=$4
  target_log_folder=$5
  retryNum=$6
  
  # Global exit variable
  exitValue=0
  
  #----------------------------------------------------------------------------------
  # Generate Project.xml according to system
  sed -i '/<InstallDir>/c<InstallDir>'${IT_HOME}'<\/InstallDir>' ${base_app_dir}/project.xml
  
  #----------------------------------------------------------------------------------
  # Create all working dir folders
  mkdir -p /tmp/COMPSsWorker01/
  mkdir -p /tmp/COMPSsWorker02/
  
  #----------------------------------------------------------------------------------
  # Run application 1 - MATMUL
  echo
  echo "*** RUNNING JAVA APPLICATION MATMUL"
  output_log="${target_log_folder}/matmul_0${retryNum}.outputlog"
  error_log="${target_log_folder}/matmul_0${retryNum}.errorlog"
  expectedTime=180s
 
  binary=${base_app_dir}/bin/matmul
  TYPE=1 # 1 method, 2 mpi
  MSIZE=2
  BSIZE=128 
  export MATMUL_BINARY=$binary
  export NODES_PER_MPI_TASK=2
  export CUS_PER_MPI_TASK=1

  timeout --signal=2 $expectedTime ${COMPSs_exec} \
     --project=${base_app_dir}/project.xml \
     --resources=${base_app_dir}/resources.xml \
     --debug \
     -tg \
     --summary \
     --lang=java \
     --comm=$comm \
     --classpath=${base_app_dir}/matmul.jar \
     matmul.files.Matmul $TYPE $MSIZE $BSIZE > >(tee ${output_log}) 2> >(tee ${error_log} >&2)
  
  # Check timeout
  if [[ "$?" = "124" ]]; then
     # Copy LOG files
     cp -rf ${COMPSs_log_folder}/matmul.files.Matmul_${retryNum}/* ${target_log_folder}
     
     # Report time out
     echo "[WARNING] Java Application timed out" >> ${output_log}
     exitValue=124
  else
     # Copy LOG files
     cp -rf ${COMPSs_log_folder}/matmul.files.Matmul_0${retryNum}/* ${target_log_folder}
  
     # Check result
     ${base_app_dir}/result ${output_log} ${target_log_folder} ${error_log}
     exitValue=$?
  fi
  
  #----------------------------------------------------------------------------------
  # Return execution status
  exit $exitValue
