#!/bin/bash

# Setting up COMPSs_HOME
if [ -z "${COMPSS_HOME}" ]; then
  COMPSS_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )"/../../.. && pwd )/"
fi
if [ ! "${COMPSS_HOME: -1}" = "/" ]; then
  COMPSS_HOME="${COMPSS_HOME}/"
fi
export COMPSS_HOME=${COMPSS_HOME}


# 1st: generate COMPSs trace
cd trace
compss_gentrace
cd ..
# 2nd: generate EAR trace
cd energy
compss_genenergy
cd ..
# 3rd: Merge both traces
compss_energy_merger