#!/bin/bash

# Setting up COMPSs_HOME
if [ -z "${COMPSS_HOME}" ]; then
  export COMPSS_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )"/../../.. && pwd )"
fi

# Run the Reproducibility Service
python3 ${COMPSS_HOME}/Tools/reproducibility_service/reproducibility_service.py $@
