#!/bin/bash

# Setting up COMPSs_HOME
if [ -z "${COMPSS_HOME}" ]; then
  export COMPSS_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )"/../../.. && pwd )"
fi


# 1st: generate COMPSs trace
cd trace
compss_gentrace
cd ..
# 2nd: generate EAR trace
cd energy
compss_genenergy
cd ..
# 3rd: Merge both traces
compss_energy_merger