#!/bin/bash

  # shellcheck disable=SC2009
  ps -elfa | grep -E "COMPSsWorker|pipers|worker.py|nio_worker_c|worker_c|runcompss|pycompss/runtime/launch.py" | grep -v "grep" | awk '{ print $4 }' | xargs -r kill -9

