#!/bin/bash

# Setting up COMPSs_HOME
if [ -z "${COMPSS_HOME}" ]; then
  export COMPSS_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )"/../../.. && pwd )"
fi

# Run the energy merger tool
python3 ${COMPSS_HOME}/Runtime/scripts/system/trace/energy_merger.py $@
