#!/bin/bash -e 
 
  #############################################################
  # Name: buildTX
  # Description: SCRIPT FOR ThunderX COMPSs BUILD
  # Parameters: <TX_user> ThunderX user account. Preferable with ssh keys inserted
  #             <FullTmpPath> Tmp path on ThunderX for deployment
  #             <FullTargetPath> Base Target Installation folder on ThunderX
  #############################################################

  ####################
  # FUNCTIONS
  ####################
  usage() {
    echo " Usage: buildTX <TX_user> <FullTmpPath> <FullTargetPath>"
    echo " "
  }


  ####################
  # MAIN
  ####################
  # Get parameters
  if [ $# -eq 1 ]; then
    if [ "$1" == "usage" ]; then
      usage
      exit 0
    fi
  fi
  if [ $# -ne 3 ]; then
    echo "Incorrect number of parameters"
    usage
    exit 1
  fi

  # SET SCRIPT VARIABLES
  SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
  
  TXuser=$1
  TXtmpDir=$2
  TXtargetDir=$3
  TXloginNode=merlin
  TXauxScript=${SCRIPT_DIR}/buildTX_aux
  PRELOAD_ENV=""

  # Perform installation
  cd "${SCRIPT_DIR}"/../commons/
  ./buildSC "${TXuser}" "${TXloginNode}" "${TXtmpDir}" "${TXtargetDir}" "${TXauxScript}" "${PRELOAD_ENV}"
  exitStatus=$?
  cd "${SCRIPT_DIR}"

  # END
  exit $exitStatus

