#!/bin/bash -e

  #############################################################
  # Name: buildTX_aux
  # Description: SCRIPT FOR LOCAL COMPSs BUILD in ThunderX
  # Parameters: <targetDir>           Base Target Installation folder
  #
  # ATTENTION: DO NOT EXECUTE THIS FILE. IT IS AUTOMATICALLY
  #            EXECUTED FROM buildTX script
  #############################################################

  usage() {
    echo "Incorrect number of parameters"
    echo " Usage: buildTX_aux <FullTargetPath>"
    echo " "
    exit 1
  }

  ####################
  # MAIN
  ####################
  # Get parameters
  if [ $# -ne 1 ]; then
    usage
  fi

  # SET SCRIPT VARIABLES
  targetDir=$1
  SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

  modules="gcc/5.3.0 papi/5.4.3 boost/1.63.0"
  py2_modules="boost/1.63.0"
  py3_modules="boost/1.63.0"
  additionalExports=""
  queues_cfg="thunder.cfg"
  extrae_with_openmpi="false"
  openmpi_version="/1.10.2"
  extrae_with_impi="true"
  impi_version=""

  /home/mdominguez/modules.sh

  "${SCRIPT_DIR}"/buildSC_aux "${targetDir}" "${modules}" "${py2_modules}" "${py3_modules}" "${additionalExports}" "${queues_cfg}" "${extrae_with_openmpi}" "${openmpi_version}" "${extrae_with_impi}" "${impi_version}" "true"
