#!/bin/bash
 
  #############################################################
  # Name: buildArcher_aux
  # Description: SCRIPT FOR LOCAL COMPSs BUILD in Archer
  # Parameters: <targetDir>           Base Target Installation folder
  #
  # ATTENTION: DO NOT EXECUTE THIS FILE. IT IS AUTOMATICALLY 
  #            EXECUTED FROM buildArcher script
  #############################################################

  usage() {
    echo "Incorrect number of parameters"
    echo " Usage: buildArcher_aux <FullTargetPath>"
    echo " "
    exit 1
  }

  ####################
  # MAIN
  ####################
  # Get parameters
  if [ $# -ne 1 ]; then
    usage
  fi

  # SET SCRIPT VARIABLES
  targetDir=$1
  scriptDir=$(dirname $0)

  modules="packages-archer PrgEnv-cray/5.2.56 java/jdk1.8.0_51 boost/1.55 python-compute/2.7.6 gcc/7.2.0"
  additionalExports=""
  queues_cfg="archer.cfg"
  extrae_with_openmpi="false"
  openmpi_version=""
  extrae_with_impi="false"
  impi_version=""

  ${scriptDir}/buildSC_aux ${targetDir} "${modules}" "${additionalExports}" "${queues_cfg}" "${extrae_with_openmpi}" "${openmpi_version}" "${extrae_with_impi}" "${impi_version}"

  # END
  exit 0

