#!/bin/bash

  #############################################################
  # Name: buildArcher_aux
  # Description: SCRIPT FOR LOCAL COMPSs BUILD in Archer
  # Parameters: <targetDir>           Base Target Installation folder
  #
  # ATTENTION: DO NOT EXECUTE THIS FILE. IT IS AUTOMATICALLY
  #            EXECUTED FROM buildArcher script
  #############################################################

  usage() {
    echo "Incorrect number of parameters"
    echo " Usage: buildArcher_aux <FullTargetPath>"
    echo " "
    exit 1
  }

  ####################
  # MAIN
  ####################
  # Get parameters
  if [ $# -ne 1 ]; then
    usage
  fi

  # SET SCRIPT VARIABLES
  targetDir=$1
  SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

  # DEFINE MODULES
  modules="packages-archer PrgEnv-cray/5.2.56 java/jdk1.8.0_51 boost/1.55 python-compute/2.7.6 gcc/7.2.0"
  unload_before_python="ignore"
  py2_modules="python-compute/2.7.6"
  py3_modules="python-compute/3.4.3"
  py3_other_modules="ignore"

  # DEFINE CONFIGURATION PARAMETERS
  additionalExports=""
  additional_module_use_folder="ignore"
  queues_cfg="archer.cfg"
  extrae_with_openmpi="false"
  openmpi_version=""
  extrae_with_impi="false"
  impi_version=""
  autoparallel="false"

  # CALL buildSC_aux
  "${SCRIPT_DIR}"/buildSC_aux "${targetDir}" "${modules}" "${unload_before_python}" "${py2_modules}" "${py3_modules}" "${py3_other_modules}" "${additionalExports}" "${additional_module_use_folder}" "${queues_cfg}" "${extrae_with_openmpi}" "${openmpi_version}" "${extrae_with_impi}" "${impi_version}" "${autoparallel}"
  ev=$?

  # End
  if [ $ev -ne 0 ]; then
    echo "ERROR: Exception in auxiliar script"
    exit $ev
  fi
  exit 0
