#!/bin/bash -e
  
  #Obtain parameter
  source_base_dir=$1
  target_base_dir=$2
  
  #Copy files
  cp -f ${source_base_dir}/target/1-faultTolerance.jar ${target_base_dir}/faultTolerance.jar   
                  
  cp -f ${source_base_dir}/projectFileTransfer.xml ${target_base_dir}/project_fileTransfer.xml                  
  cp -f ${source_base_dir}/resourcesFileTransfer.xml ${target_base_dir}/resources_fileTransfer.xml
  cp -f ${source_base_dir}/projectTaskSubmission.xml ${target_base_dir}/project_taskSubmission.xml                  
  cp -f ${source_base_dir}/resourcesTaskSubmission.xml ${target_base_dir}/resources_taskSubmission.xml
  
  cp -f ${source_base_dir}/execution ${target_base_dir}/execution
  cp -f ${source_base_dir}/result_fileTransfer ${target_base_dir}/result_fileTransfer
  cp -f ${source_base_dir}/result_taskSubmission ${target_base_dir}/result_taskSubmission
  