#!/bin/bash

start_profiling() {
  if [ ${provenance} ]; then
    profiling_status=$(echo "${specific_log_dir}.status_profiling")
    # echo $profiling_status
    echo true >$profiling_status
    python3 "${COMPSS_HOME}Runtime/scripts/system/profiling/profiler.py" ${profiling_status} ${specific_log_dir} ${resFile} &
    PROFILING_PID=$!
  fi
}

stop_profiling() {
  if [ ${provenance} ]; then
    echo false > $profiling_status
    wait $PROFILING_PID
    # rm $profiling_status
    echo "PROVENANCE | ENDED PROFILING SCRIPT"
  fi
}