#!/bin/bash

start_profiling() {
  if [ ${provenance} ]; then
    # specific_log_dir=$(pwd)
    # profiling_status=$(echo "${specific_log_dir}/.status_profiling")

    if [ -z "${COMPSS_PROFILING_INTERVAL}" ]; then
      export COMPSS_PROFILING_INTERVAL=5
    fi

    if [ -z "${logDir}" ]; then
      working_directory="$(dirname ${wdir_in_master})/stats"
      mkdir $working_directory
    else
      working_directory="${logDir}"
    fi

    # launch the profiling script
    OLD_LD_PRELOAD=$LD_PRELOAD
    unset LD_PRELOAD
    python3 "${COMPSS_HOME}Runtime/scripts/system/profiling/profiler.py" "${working_directory}" &
    LD_PRELOAD=$OLD_LD_PRELOAD

    PROFILING_PID=$!
  fi
}
