#!/bin/bash

  # Obtain parameters
  COMPSs_exec=$1
  comm=$2
  runcompss_opts=$3
  base_app_dir=$4
  COMPSs_log_folder=$5
  target_log_folder=$6
  retry_num=$7
  execution_envs=$8
  
  # Global variables
  exit_value=0
  jar_name="1_annotation_commutative.jar"
  app_name="testCommutative.TestCommutative"
  
#----------------------------------------------------------------------------------
  # Generate Project.xml according to system
  sed -i '/<InstallDir>/c<InstallDir>'"${COMPSS_HOME}"'<\/InstallDir>' "${base_app_dir}"/project.xml
  
  #----------------------------------------------------------------------------------
  # Create all working dir folders
  mkdir -p /tmp/COMPSsWorker01/
  mkdir -p /tmp/COMPSsWorker02/
  mkdir -p /tmp/sharedDisk/
  
  #----------------------------------------------------------------------------------
  # Create storage Conf
  storageConf=${target_log_folder}/storage.conf
  cat > "$storageConf" << EOF
COMPSsWorker01
COMPSsWorker02
EOF
  
  # Add trap to clean folder
  clean() {
    rm -rf /tmp/PSCO/
    rm -rf /tmp/sharedDisk/
  }
  trap clean EXIT

  #----------------------------------------------------------------------------------
  # Set Storage implementation location
  storageImplPath=${base_app_dir}/jars/compss-dummyPSCO.jar

  
  #----------------------------------------------------------------------------------
  # Run application
  echo
  echo "*** RUNNING JAVA APPLICATION COMMUTATIVE"
  output_log="${target_log_folder}/commutative_annotation_0${retry_num}.outputlog"
  error_log="${target_log_folder}/commutative_anotation_0${retry_num}.errorlog"
  final_graph_expected="${base_app_dir}/final_graph.dot"
  expectedTime=100s
  
  # shellcheck disable=SC2086
  timeout --signal=2 $expectedTime "${COMPSs_exec}" \
     --project="${base_app_dir}"/project.xml \
     --resources="${base_app_dir}"/resources.xml \
     \
     --comm="$comm" \
     \
     --debug \
     ${runcompss_opts} \
     -g \
     --storage_conf=${storageConf} \
     --classpath="${base_app_dir}/${jar_name}":${storageImplPath} \
     \
     "${app_name}" > >(tee "${output_log}") 2> >(tee "${error_log}" >&2)
  
  # Check timeout
  if [[ "$?" = "124" ]]; then
     # Copy LOG files
     cp -rf "${COMPSs_log_folder}/${app_name}_0${retry_num}"/* "${target_log_folder}"
     
     # Report time out
     echo "[WARNING] Java Application timed out" >> "${output_log}"
     exit_value=124
  else
     # Copy LOG files
     cp -rf "${COMPSs_log_folder}/${app_name}_0${retry_num}"/* "${target_log_folder}"
  
     # Check result
     "${base_app_dir}"/result "${output_log}" "${error_log}" "${target_log_folder}" "${final_graph_expected}"
     exit_value=$?
  fi
  
  #----------------------------------------------------------------------------------
  # Return execution status
  exit ${exit_value}
