#!/bin/bash

  #############################################################
  # Name: buildSalomon_aux
  # Description: SCRIPT FOR LOCAL COMPSs BUILD in Salomon
  # Parameters: <targetDir>           Base Target Installation folder
  #
  # ATTENTION: DO NOT EXECUTE THIS FILE. IT IS AUTOMATICALLY
  #            EXECUTED FROM buildSalomon script
  #############################################################

  usage() {
    echo "Incorrect number of parameters"
    echo " Usage: buildSalomon_aux <FullTargetPath>"
    echo " "
    exit 1
  }

  ####################
  # MAIN
  ####################
  # Get parameters
  if [ $# -ne 1 ]; then
    usage
  fi

  # SET SCRIPT VARIABLES
  targetDir=$1
  SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
  #Old Configuration
  # DEFINE MODULES
  #modules="GCCcore/6.3.0 libxml2/2.9.9 binutils/2.27-GCCcore-6.3.0 icc/2017.7.259-GCC-6.3.0-2.27 ifort/2017.7.259-GCC-6.3.0-2.27 iccifort/2017.7.259-GCC-6.3.0-2.27 impi/2017.4.239-iccifort-2017.7.259-GCC-6.3.0-2.27 iimpi/2017c imkl/2017.4.239-iimpi-2017c intel/2017c bzip2/1.0.6 zlib/1.2.11 Boost/1.68.0-intel-2017c-serial Java/1.8.0_144"
  #unload_before_python="ignore"
  #py2_modules="Boost/1.63.0-intel-2017a-Python-2.7.13 Python/2.7.13"
  #py3_modules="Boost/1.63.0-foss-2017a-Python-3.6.1 Python/3.6.1"
  # py3_other_modules="ignore"
  #
  # DEFINE CONFIGURATION PARAMETERS
  #additionalExports=""
  #queues_cfg="salomon.cfg"
  #extrae_with_openmpi="false"
  #openmpi_version=""
  #extrae_with_impi="true"
  #impi_version=""

  #new configuration
  # DEFINE MODULES
  #modules="GCCcore/8.3.0 libxml2/2.9.9 binutils/2.32-GCCcore-8.3.0 icc/2019.5.281-GCC-8.3.0-2.32 ifort/2019.5.281-GCC-8.3.0-2.32 iccifort/2019.5.281-GCC-8.3.0-2.3 impi/2019.6.154-iccifort-2019.5.281-GCC-8.3.0-2.32 iimpi/2019a imkl/2019.5.281-iimpi-2019a intel/2019a bzip2/1.0.8 zlib/1.2.11-GCCcore-8.3.0 Boost/1.72.0-intel-2020a Java/1.8.0_202"
  modules="GCCcore/8.3.0 libxml2/2.9.9 binutils/2.32-GCCcore-8.3.0 bzip2/1.0.6 zlib/1.2.11 OpenMPI/3.1.5-GCCcore-8.3.0 boost-1.72.0-gcc-8.3.0-weqcjtk Java/1.8.0_202"
  unload_before_python="ignore"
  py2_modules="Python/2.7.13"
  py3_modules="Python/3.6.1"
  py3_other_modules="ignore"

  # DEFINE CONFIGURATION PARAMETERS
  additionalExports=""
  additional_module_use_folder="ignore"
  queues_cfg="salomon.cfg"
  extrae_with_openmpi="true"
  openmpi_version=""
  extrae_with_impi="false"
  impi_version=""
  autoparallel="false"

  # CALL buildSC_aux
  "${SCRIPT_DIR}"/buildSC_aux "${targetDir}" "${modules}" "${unload_before_python}" "${py2_modules}" "${py3_modules}" "${py3_other_modules}" "${additionalExports}" "${additional_module_use_folder}" "${queues_cfg}" "${extrae_with_openmpi}" "${openmpi_version}" "${extrae_with_impi}" "${impi_version}" "${autoparallel}"

  # END
  exit 0
