#!/bin/bash

  #############################################################
  # Name: buildSalomon_aux
  # Description: SCRIPT FOR LOCAL COMPSs BUILD in Salomon
  # Parameters: <targetDir>           Base Target Installation folder
  #
  # ATTENTION: DO NOT EXECUTE THIS FILE. IT IS AUTOMATICALLY
  #            EXECUTED FROM buildSalomon script
  #############################################################

  usage() {
    echo "Incorrect number of parameters"
    echo " Usage: buildSalomon_aux <FullTargetPath>"
    echo " "
    exit 1
  }

  ####################
  # MAIN
  ####################
  # Get parameters
  if [ $# -ne 1 ]; then
    usage
  fi

  # SET SCRIPT VARIABLES
  targetDir=$1
  SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
  
  # DEFINE MODULES
  modules="GCCcore/8.3.0 libxml2/2.9.9 binutils/2.32-GCCcore-8.3.0 bzip2/1.0.6 zlib/1.2.11 OpenMPI/3.1.5-GCCcore-8.3.0 boost-1.72.0-gcc-8.3.0-weqcjtk Java/1.8.0_202"
  unload_before_python="ignore"
  py2_modules="Python/2.7.13"
  py3_modules="Python/3.6.1"
  py3_other_modules="ignore"

  # DEFINE CONFIGURATION PARAMETERS
  additionalExports=""
  additional_module_use_folder="ignore"
  queues_cfg="salomon.cfg"
  extrae_with_openmpi="true"
  openmpi_version=""
  extrae_with_impi="false"
  impi_version=""
  autoparallel="false"

  # CALL buildSC_aux
  "${SCRIPT_DIR}"/buildSC_aux "${targetDir}" "${modules}" "${unload_before_python}" "${py2_modules}" "${py3_modules}" "${py3_other_modules}" "${additionalExports}" "${additional_module_use_folder}" "${queues_cfg}" "${extrae_with_openmpi}" "${openmpi_version}" "${extrae_with_impi}" "${impi_version}" "${autoparallel}"
  ev=$?

  # End
  if [ $ev -ne 0 ]; then
    echo "ERROR: Exception in auxiliar script"
    exit $ev
  fi
  exit 0
