#!/bin/bash -e
  
  # Obtain parameter
  source_base_dir=$1
  target_base_dir=$2
  
  # Copy files
  app_name="servicesTest"

  cp "${source_base_dir}"/project.xml "${target_base_dir}"/project.xml
  cp "${source_base_dir}"/resources.xml "${target_base_dir}"/resources.xml

  cp "${source_base_dir}"/execution "${target_base_dir}"/execution
  cp "${source_base_dir}"/result "${target_base_dir}"/result

  # Deploy the test
  cp "${source_base_dir}"/servicesTest/target/${app_name}.jar "${target_base_dir}"/${app_name}.jar
  
  # Deploy also the service
  cp "${source_base_dir}"/groupService/target/groupService.jar "${target_base_dir}"/groupService.jar
