# Autogenerated file (see generate_datatype_enums.py). Used DataType.java as the source template.  # noqa


class DataType(object):
    BOOLEAN = 0
    CHAR = 1
    BYTE = 2
    SHORT = 3
    INT = 4
    LONG = 5
    FLOAT = 6
    DOUBLE = 7
    STRING = 8
    FILE = 9
    OBJECT = 10
    PSCO = 11
    EXTERNAL_PSCO = 12
    BINDING_OBJECT = 13
    WCHAR = 14
    WSTRING = 15
    LONGLONG = 16
    VOID = 17
    ANY = 18
    ARRAY_CHAR = 19
    ARRAY_BYTE = 20
    ARRAY_SHORT = 21
    ARRAY_INT = 22
    ARRAY_LONG = 23
    ARRAY_FLOAT = 24
    ARRAY_DOUBLE = 25
    COLLECTION = 26
    STREAM = 27
    EXTERNAL_STREAM = 28
    ENUM = 29
    NULL = 30
