#!/bin/bash

  # Retrieve script variables
  targetDir=$1
  scriptDir=$(pwd)/$(dirname $0)

  # Setup Extrae for PAPI (or not) 
  papiPath=$(which papi_avail 2> /dev/null)
  if [ -z ${papiPath} ]; then
    # No PAPI available
    papiArg="--without-papi"
  else
    # PAPI available
    papiBaseDir=${papiPath%/bin**}
    papiArg="--with-papi=${papiBaseDir}"
  fi

  # Setup MPI for parallel merge (or not)
  mpiPath=$(which mpirun 2> /dev/null)
  if [ -z ${mpiPath} ]; then
    # No MPI available
    mpiArg="--without-mpi"
  else
    # MPI available
    mpiBaseDir=${mpiPath%/bin**}
    mpiArg="--with-mpi=${mpiBaseDir} --enable-parallel-merge"
  fi

  # Create installation folder
  mkdir -p ${targetDir}

  # Configure, compile and install
  autoreconf --force --install
  ./configure --enable-gettimeofday-clock \
              --without-unwind \
              --without-dyninst \
              --without-binutils \
              ${mpiArg} \
              ${papiArg} \
              --with-java-jdk=${JAVA_HOME} \
              --disable-openmp \
              --disable-nanos \
              --disable-smpss \
              --prefix=${targetDir} \
              --enable-parallel-merge \
              --libdir=${targetDir}/lib

  make clean install
  if [ $? -ne 0 ]; then
    exit 1
  fi  

  # Exit normal
  exit 0

