#!/bin/bash

  #Obtain parameters
  COMPSs_exec=$1
  comm=$2
  runcompss_opts=$3
  base_app_dir=$4
  COMPSs_log_folder=$5
  target_log_folder=$6
  retryNum=$7
  
  #Global exit variable
  exitValue=0
  
  #----------------------------------------------------------------------------------
  #Generate Project.xml according to system
  sed -i '/<InstallDir>/c<InstallDir>'${COMPSS_HOME}'<\/InstallDir>' ${base_app_dir}/project.xml
  
  #----------------------------------------------------------------------------------
  #Create all working dir folders
  mkdir -p /tmp/COMPSsWorker01/
  
  #----------------------------------------------------------------------------------
  #Run application 1 - Monitor
  echo
  echo "*** RUNNING JAVA APPLICATION MONITOR - MATMUL Arrays"
  output_log="${target_log_folder}/monitor_0${retryNum}.outputlog"
  error_log="${target_log_folder}/monitor_0${retryNum}.errorlog"
  expectedTime=1200s
  Ain="${base_app_dir}/java_matmul_A8x8.in"
  Bin="${base_app_dir}/java_matmul_B8x8.in"
  CoutExpected="${base_app_dir}/java_matmul_C8x8.out"
  CoutGot="${target_log_folder}/C8x8gotArrays.out"
  
  timeout --signal=2 $expectedTime ${COMPSs_exec} \
     --lang=java \
     --classpath=${base_app_dir}/monitor.jar \
     --debug \
     -m \
     --comm=$comm \
     --project=${base_app_dir}/project.xml \
     --resources=${base_app_dir}/resources.xml \
     ${runcompss_opts} \
     monitor.Matmul $Ain $Bin $CoutGot > >(tee ${output_log}) 2> >(tee ${error_log} >&2)
  
  #Check timeout
  if [[ "$?" = "124" ]]; then
     #Copy LOG files
     cp -rf ${COMPSs_log_folder}/monitor.Matmul_0${retryNum}/* ${target_log_folder}
     
     #Report time out
     echo "[WARNING] Java Application timed out" >> ${output_log}
     exitValue=124
  else
     #Copy LOG files
     cp -rf ${COMPSs_log_folder}/monitor.Matmul_0${retryNum}/* ${target_log_folder}
  
     #Check result
     ${base_app_dir}/result ${output_log} ${target_log_folder} $CoutExpected $CoutGot
     exitValue=$?
  fi
 
  #----------------------------------------------------------------------------------
  #Return execution status
  exit $exitValue

