#!/bin/bash -e
  
  # Obtain parameters
  source_base_dir=$1
  target_base_dir=$2
  
  # Compile C sub-program with MPI
  mkdir ${target_base_dir}/bin/
  mpicc -o ${target_base_dir}/bin/addVector ${source_base_dir}/src/main/c/addVector.c
  
  # Copy files
  cp -f ${source_base_dir}/target/30-mpi.jar ${target_base_dir}/mpi.jar   
                  
  cp -f ${source_base_dir}/project.xml ${target_base_dir}/project.xml                  
  cp -f ${source_base_dir}/resources.xml ${target_base_dir}/resources.xml
  
  cp -f ${source_base_dir}/execution ${target_base_dir}/execution
  cp -f ${source_base_dir}/result ${target_base_dir}/result
