#!/bin/bash

  # Obtain parameters
  COMPSs_exec=$1
  comm=$2
  base_app_dir=$3
  COMPSs_log_folder=$4
  target_log_folder=$5
  retryNum=$6
  
  # Global exit variable
  exitValue=0
  
  #----------------------------------------------------------------------------------
  # Generate Project.xml according to system
  sed -i '/<InstallDir>/c<InstallDir>'${IT_HOME}'<\/InstallDir>' ${base_app_dir}/project.xml
  
  #----------------------------------------------------------------------------------
  # Create all working dir folders
  mkdir -p /tmp/COMPSsWorker01/
  
  #----------------------------------------------------------------------------------
  # MPICC binary path
  binary="${base_app_dir}/bin/addVector"
  export VEC_SUM_MPI_BINARY=${binary}
  
  #----------------------------------------------------------------------------------
  # Run application 1 - Java MPI
  echo
  echo "*** RUNNING JAVA APPLICATION MPI"
  
  echo "MPI Binary: $VEC_SUM_MPI_BINARY"
    
  output_log="${target_log_folder}/testMPI_0${retryNum}.outputlog"
  error_log="${target_log_folder}/testMPI_0${retryNum}.errorlog"
  expectedTime=180s
  
  timeout --signal=2 $expectedTime ${COMPSs_exec} \
     --project=${base_app_dir}/project.xml \
     --resources=${base_app_dir}/resources.xml \
     --debug \
     --lang=java \
     --comm=$comm \
     --classpath=${base_app_dir}/mpi.jar \
     testMPI.Main > >(tee ${output_log}) 2> >(tee ${error_log} >&2)
  
  
  #Check timeout
  if [[ "$?" = "124" ]]; then
     #Copy LOG files
     cp -rf ${COMPSs_log_folder}/testMPI.Main_0${retryNum}/* ${target_log_folder}
     
     #Report time out
     echo "[WARNING] Java Application timed out" >> ${output_log}
     exitValue=124
  else
     #Copy LOG files
     cp -rf ${COMPSs_log_folder}/testMPI.Main_0${retryNum}/* ${target_log_folder}
  
     #Check result
     ${base_app_dir}/result ${output_log} ${target_log_folder} 
     exitValue=$?
  fi
  
  
  #----------------------------------------------------------------------------------
  #Return execution status
  exit $exitValue
