#!/bin/bash

  #Obtain parameters
  COMPSs_exec=$1
  comm=$2
  runcompss_opts=$3
  base_app_dir=$4
  COMPSs_log_folder=$5
  target_log_folder=$6
  retryNum=$7
  
  #Global exit variable
  exitValue=0
  
  #----------------------------------------------------------------------------------
  #Generate Project.xml according to system
  sed -i '/<InstallDir>/c<InstallDir>'${IT_HOME}'<\/InstallDir>' ${base_app_dir}/project.xml
  
  #----------------------------------------------------------------------------------
  #Create all working dir folders
  mkdir -p /tmp/COMPSsWorker01/
  
  #----------------------------------------------------------------------------------
  #Run application 24 - No Task
  echo
  echo "*** RUNNING JAVA APPLICATION NO_TASK"
  output_log="${target_log_folder}/noTask_0${retryNum}.outputlog"
  error_log="${target_log_folder}/noTask_0${retryNum}.errorlog"
  expectedTime=20s
  
  timeout --signal=2 $expectedTime ${COMPSs_exec} \
     --project=${base_app_dir}/project.xml \
     --resources=${base_app_dir}/resources.xml \
     --debug \
     --lang=java \
     --comm=$comm \
     ${runcompss_opts} \
     --classpath=${base_app_dir}/noTask.jar \
     noTask.Main > >(tee ${output_log}) 2> >(tee ${error_log} >&2)
  
  
  #Check timeout
  if [[ "$?" = "124" ]]; then
     #Copy LOG files
     cp -rf ${COMPSs_log_folder}/noTask.Main_0${retryNum}/* ${target_log_folder}
     
     #Report time out
     echo "[WARNING] Java Application timed out" >> ${output_log}
     exitValue=124
  else
     #Copy LOG files
     cp -rf ${COMPSs_log_folder}/noTask.Main_0${retryNum}/* ${target_log_folder}
  
     #Check result
     ${base_app_dir}/result ${output_log} ${target_log_folder} 
     exitValue=$?
  fi
  
  
  #----------------------------------------------------------------------------------
  #Return execution status
  exit $exitValue

