#!/bin/bash -e
  
  # Obtain parameter
  source_base_dir=$1
  target_base_dir=$2
  
  # Copy files
  app_name="6_3_agents_transfers_files_java"

  cp "${source_base_dir}"/target/${app_name}.jar "${target_base_dir}"/${app_name}.jar

  cp "${source_base_dir}"/projectAgent1.xml "${target_base_dir}"/projectAgent1.xml
  cp "${source_base_dir}"/projectAgent2.xml "${target_base_dir}"/projectAgent2.xml
  cp "${source_base_dir}"/projectAgent3.xml "${target_base_dir}"/projectAgent3.xml

  cp "${source_base_dir}"/resources.xml "${target_base_dir}"/resources.xml

  cp "${source_base_dir}"/execution "${target_base_dir}"/execution