#!/bin/bash

  # Obtain parameters
  COMPSs_exec=$1
  comm=$2
  runcompss_opts=$3
  base_app_dir=$4
  COMPSs_log_folder=$5
  target_log_folder=$6
  retry_num=$7
  execution_envs=$8
  
  # Global variables
  AGENT_PIDS=""
  exit_value=0
  NUM_RETRIES="50"
  app_name="5.4_1_agents_python_collections"
  expectedTime="60s"

  # Traps and Handlers
  function kill_agents() {
    for pid in ${AGENT_PIDS}; do
      kill -SIGINT ${pid}
    done
  }
  trap kill_agents EXIT

  #----------------------------------------------------------------------------------
  # Generate Project.xml according to system
  sed -i '/<InstallDir>/c<InstallDir>'"${COMPSS_HOME}"'<\/InstallDir>' "${base_app_dir}"/project.xml
  
  #----------------------------------------------------------------------------------
  # Create all working dir folders
  mkdir -p /tmp/COMPSsWorker01/
  
  #----------------------------------------------------------------------------------
  # Run application
  echo ""
  echo "*** RUNNING AGENTS TEST: nested compss 1 agent"
  log_dir="${COMPSs_log_folder}/${app_name}_0${retry_num}/"
  mkdir -p "${log_dir}"
  output_log="${log_dir}test.outputlog"
  error_log="${log_dir}test.errorlog"
  touch "${output_log}"
  touch "${error_log}"

  # Starting agent
agent1_log_dir="${log_dir}/COMPSsWorker01/"
mkdir -p "${agent1_log_dir}" 
compss_agent_start_service \
  --agent_name_prefix="COMPSsWorker" \
  --pythonpath="${base_app_dir}/src" \
  --log_dir="${log_dir}" \
  -d \
  --exec_time=${expectedTime} \
  ${runcompss_opts} \
  --project="${base_app_dir}/project.xml" \
  --resources="${base_app_dir}/resources.xml" \
   --lang="PYTHON" \
   --method_name="main" \
   "nested_collection_detection"


  job1_method=$( grep "\"method_name\"" "${agent1_log_dir}/jobs/job1_NEW.out" | cut -c 24- | jq -r '.method_name')
  if [ ! "${job1_method}" == "main" ]; then
    echo "Unexpected method (${job1_method}) for job 1." > >(tee -a "${error_log}")
    exit 1
  fi
  echo  "main method properly started" > >(tee -a "${output_log}")
  created_jobs=$(ls "${agent1_log_dir}jobs" | grep -c NEW.out)
  if [ ! "${created_jobs}" == "5" ]; then
    echo "COMPSs has generated ${created_jobs} tasks and only 5 expected." > >(tee -a "${error_log}")
    exit 1
  fi 
  job2_method=$( grep "\"method_name\"" "${agent1_log_dir}/jobs/job2_NEW.out" | cut -c 24- | jq -r '.method_name')
  job3_method=$( grep "\"method_name\"" "${agent1_log_dir}/jobs/job3_NEW.out" | cut -c 24- | jq -r '.method_name')
  job4_method=$( grep "\"method_name\"" "${agent1_log_dir}/jobs/job4_NEW.out" | cut -c 24- | jq -r '.method_name')
  job5_method=$( grep "\"method_name\"" "${agent1_log_dir}/jobs/job4_NEW.out" | cut -c 24- | jq -r '.method_name')
  
sleep 5 
  printIntColl_value=$( grep printIntCollResult: ${agent1_log_dir}/jobs/* | cut -d ":" -f3)
  printObjColl_value=$( grep printObjCollResult: ${agent1_log_dir}/jobs/* | cut -d ":" -f3)
  createIntColl_value=$( grep createIntCollectionResult: ${agent1_log_dir}/jobs/* | cut -d ":" -f3)
  createObjColl_value=$( grep createObjCollectionResult: ${agent1_log_dir}/jobs/* | cut -d ":" -f3)


  if [ ! "${printIntColl_value}" == "[1, 2, 3, [41, 42, 43]]" ]; then
    echo "Unexpected value (${printIntColl_value}) for tag printIntCollResult." > >(tee -a "${error_log}")
    exit 1
  fi
  if [ ! "${printObjColl_value}" == "[D[1], D[2], D[3], [D[41], D[42], D[43]]]" ]; then
    echo "Unexpected value (${printObjColl_value}) for tag printObjCollResult." > >(tee -a "${error_log}")
    exit 1
  fi
  if [ ! "${createIntColl_value}" == "[1, 2, 3, [41, 42, 43]]" ]; then
    echo "Unexpected value (${createIntColl_value}) for tag createIntCollectionResult." > >(tee -a "${error_log}")
    exit 1
  fi
  if [ ! "${createObjColl_value}" == "[D[1], D[2], D[3], [D[41], D[42], D[43]]]" ]; then
    echo "Unexpected value (${createObjColl_value}) for tag createObjcollectionResult." > >(tee -a "${error_log}")
    exit 1
  fi
  echo "All task executed as expected and with the expected values." 


  # Copy LOG files
  cp -rf "${COMPSs_log_folder}/${app_name}_0${retry_num}"/* "${target_log_folder}"
  exit_value=0

  #----------------------------------------------------------------------------------
  # Return execution status
  exit ${exit_value}

