#!/bin/bash -e

  #############################################################
  # Name: buildJureca_aux
  # Description: SCRIPT FOR LOCAL COMPSs BUILD in Jureca
  # Parameters: <targetDir> Base Target Installation folder
  #
  # ATTENTION: DO NOT EXECUTE THIS FILE. IT IS AUTOMATICALLY
  #            EXECUTED FROM buildJureca script
  #############################################################

  usage() {
    echo "Incorrect number of parameters"
    echo " Usage: buildJureca_aux <FullTargetPath>"
    echo " "
    exit 1
  }


  ####################
  # MAIN
  ####################
  # Get parameters
  if [ $# -ne 1 ]; then
    usage
  fi

  # SET SCRIPT VARIABLES
  targetDir=$1
  SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

  modules="GCCcore/.5.4.0 Intel/2017.0.098-GCC-5.4.0 Java IntelMPI Python/2.7.12 Boost PAPI/5.5.0 Autotools/20150215"
  py2_modules="Python/2.7.12"
  py3_modules=""
  additionalExports=""
  queues_cfg="jureca.cfg"
  extrae_with_openmpi="false"
  openmpi_version=""
  extrae_with_impi="false"
  impi_version=""

  "${SCRIPT_DIR}"/buildSC_aux "${targetDir}" "${modules}" "${py2_modules}" "${py3_modules}" "${additionalExports}" "${queues_cfg}" "${extrae_with_openmpi}" "${openmpi_version}" "${extrae_with_impi}" "${impi_version}" "false"
