#!/bin/bash -e

  # Obtain parameter
  source_base_dir=$1
  target_base_dir=$2

  # Copy files
  cp "${source_base_dir}"/execution "${target_base_dir}"/execution
  cp "${source_base_dir}"/resultInMaster "${target_base_dir}"/resultInMaster
  cp "${source_base_dir}"/resultInMasterAfterTasks1 "${target_base_dir}"/resultInMasterAfterTasks1
  cp "${source_base_dir}"/resultInMasterAfterTasks2 "${target_base_dir}"/resultInMasterAfterTasks2
  cp "${source_base_dir}"/resultInWorker "${target_base_dir}"/resultInWorker

  cp -r "${source_base_dir}"/src "${target_base_dir}"

  cp "${source_base_dir}"/project.xml "${target_base_dir}"/project.xml
  cp "${source_base_dir}"/resources.xml "${target_base_dir}"/resources.xml
