#!/bin/bash


  # Obtain parameters
  COMPSs_exec=$1
  comm=$2
  runcompss_opts=$3
  base_app_dir=$4
  COMPSs_log_folder=$5
  target_log_folder=$6
  retry_num=$7
  execution_envs=$8
  
  # Global variables
  exit_value=1
  app_name="0_destroy_env"
  
  #----------------------------------------------------------------------------------
  # Run application
  echo
  echo "*** DELETING ALL ENVIRONMENTS"
  output_log="${target_log_folder}/destroy_env_0${retry_num}.outputlog"
  error_log="${target_log_folder}/destroy_env_0${retry_num}.errorlog"
  expectedTime=60s

  # Get all the directories inside `~/.COMPSs/envs`
   envs_dirs=$(find ~/.COMPSs/envs -mindepth 1 -maxdepth 1 ! -name 'default' -type d -printf '%f ' | sort -n)
  
  # shellcheck disable=SC2086
  timeout --signal=2 $expectedTime \
    /bin/bash -e "${base_app_dir}/src/test.sh" ${envs_dirs} > >(tee "${output_log}") 2> >(tee "${error_log}" >&2)
  
  # Check timeout
  if [[ "$?" = "124" ]]; then
     # Report time out
     echo "[WARNING] Deleting ALL Environments timed out" >> "${output_log}"
     exit_value=124
  else
     # Check result
     "${base_app_dir}"/result "${output_log}" "${error_log}" "${target_log_folder}" "${base_app_dir}"
     exit_value=$?
  fi
  
  #----------------------------------------------------------------------------------
  # Return execution status
  exit ${exit_value}

