#!/bin/bash -e

  trunk_rel_path=../../../../
  COMPSs_target=$(pwd)/tmp/opt/COMPSs

  if [ -z "$JAVA_HOME" ]; then
    echo "Please define \$JAVA_HOME"
    exit 1
  fi

  mkdir -p ${COMPSs_target}/Bindings/bindings-common
  cd ${trunk_rel_path}/compss/programming_model/bindings/bindings-common
  ./install_common ${COMPSs_target}/Bindings/bindings-common
  cd -

