#!/bin/bash

  #---------------------------------------------------------------------------------------------------------------------
  # Functions
  #---------------------------------------------------------------------------------------------------------------------
  usage() {
    echo "*************************************************************************"
    echo "*                                                                       *"
    echo "*  Usage:   exec_sc <vm_type> <log_base_folder> <package_base_folder>   *"
    echo "*                                                                       *"
    echo "*  Arguments:                                                           *"
    echo "*    - Available vm_types: sc                                           *"
    echo "*    - Log and package folders refer to the base of this distribution   *"
    echo "*                                                                       *"
    echo "*************************************************************************"
  }

  display_error() {
    local errMsg=$1
    echo " "
    echo "ERROR: $errMsg"
    echo " "
  }


  #---------------------------------------------------------------------------------------------------------------------
  # MAIN PROGRAM
  #---------------------------------------------------------------------------------------------------------------------
  #Define user variables
  jenkins_job="COMPSs_Framework_Trunk_Build_SC"                                #Jenkins Trunk job name


  #---------------------------------------------------------------------------------------------------------------------
  # WARNING: DO NOT MODIFY ANYTHING BELOW THIS MESSAGE UNLESS YOU KNOW WHAT YOU ARE DOING
  #---------------------------------------------------------------------------------------------------------------------
  #Get parameters
  vm_type=$1
  log_folder=$2
  jenkins_package_folder=$3

  #Check parameters
  if [[ "$#" -ne 3 ]]; then
     display_error "Incorrect number of parameters"
     usage
     exit 1
  fi

  if [ "${vm_type}" != "sc" ]; then
     display_error "Incorrect distribution. Only sc allowed."
     usage
     exit 1
  fi

  #Define script variables
  script_dir=$(dirname $0)

  #---------------------------------------------------------------------------------------------------------------------
  #Create packages
  ${script_dir}/../packages/build_and_package_sc.sh ${jenkins_package_folder}
  if [ $? -ne 0 ]; then
     display_error "COMPSs compile, build and package FAILED"
     exit 1
  fi

  #---------------------------------------------------------------------------------------------------------------------
  #Deploy unstable packages to repository
  ${script_dir}/../repos/main ${jenkins_job} ${vm_type} "unstable"
  if [ $? -ne 0 ]; then
     display_error "Deploying UNSTABLE packages FAILED"
     exit 1
  fi

  #---------------------------------------------------------------------------------------------------------------------
  #Deploy testing packages to repository
  ${script_dir}/../repos/main ${jenkins_job} ${vm_type} "testing"
  if [ $? -ne 0 ]; then
     display_error "Deploying TESTING packages FAILED"
     exit 1
  fi


  #---------------------------------------------------------------------------------------------------------------------
  #End value
  echo " "
  echo " CONGRATULATIONS! The ${vm_type} process succeeded"
  echo " "
  exit 0

