#!/bin/bash -e

  #---------------------------------------------------------------------------------------------------------------------
  # MAIN PROGRAM
  #---------------------------------------------------------------------------------------------------------------------
  #Define script variables
  script_dir=$(dirname $0)
  WS=${script_dir}/../../../

  #---------------------------------------------------------------------------------------------------------------------
  #Prepare vm to lauch tests.
  echo -e "\e[0m"
  echo "**************************"
  echo "*** Package COMPSs SVN ***"
  echo "**************************"
  echo -e "\e[0m"
  echo "--- Clearing previous packaging..."
  rm -rf ${script_dir}/../packages/compss.tar.gz
  echo "   Success"

  echo "--- Copying trunk files..."
  mkdir -p $WS/tmpTrunk
  
  cp -r $WS/builders $WS/tmpTrunk
  cp $WS/changelog $WS/tmpTrunk
  cp -r $WS/compss $WS/tmpTrunk
  cp -r $WS/dependencies $WS/tmpTrunk
  cp -r $WS/doc $WS/tmpTrunk
  cp -r $WS/files $WS/tmpTrunk
  cp $WS/LICENSE $WS/tmpTrunk
  cp -r $WS/maven-plugins $WS/tmpTrunk
  cp $WS/NOTICE $WS/tmpTrunk
  cp $WS/pom.xml $WS/tmpTrunk
  cp $WS/README $WS/tmpTrunk
  cp $WS/RELEASE_NOTES $WS/tmpTrunk
  cp -r $WS/tests $WS/tmpTrunk
  echo "   Success"

  echo "--- Packaging files..."
  cd $WS
  tar -czvf compss.tar.gz tmpTrunk/
  cd ${script_dir}
  echo "   Success"

  echo "--- Clearing tmp files..."
  mv $WS/compss.tar.gz ${script_dir}/../packages/
  rm -r $WS/tmpTrunk
  echo "   Success"

  #Process completed
  exit 0

