#!/bin/bash

############################
#       DEFAULT.CFG        #
############################
# This file specifies the environment in which an
# application is going to be built. 
# Is useful to specify compilers and environment
# variables, thus cross compiling can be performed 
# without changing the inner scripts of COMPSs. 

# For COMPSs we need the following :
#   * Environment variables:
#
#       For compilers:      CC, CXX
#       For JAVA:           JAVA_HOME
#       For LIBS:           BOOST_LIB
#       For GNU Configure:  TARGET_HOST 

x86_64() {
    export CC=gcc
    export CXX=g++
    export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64
}

armhf() {
    export CC=arm-linux-gnueabihf-gcc
    export CXX=arm-linux-gnueabihf-g++ 
    export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-armhf
    export BOOST_LIB=/opt/install-arm/libboost
    export TARGET_HOST=--host=arm-linux-gnueabihf
}
