#!/bin/bash

  #---------------------------------------------------------------------------------------------------------------------
  # Functions
  #---------------------------------------------------------------------------------------------------------------------
  usage() {
    echo "***********************************************************"
    echo "  Usage: main"
    echo "***********************************************************"
  }

  display_error() {
    local errMsg=$1
    echo " "
    echo "ERROR: $errMsg"
    echo " "
  }



  #---------------------------------------------------------------------------------------------------------------------
  # MAIN PROGRAM
  #---------------------------------------------------------------------------------------------------------------------
  #Define script variables
  script_dir=$(pwd)/$(dirname $0)

  #Define user variables
  log_base_folder=${script_dir}/../../logs/                            #Folder to store logs
  package_base_folder=${script_dir}/../../builders/packages/           #Folder to store packages and upload them to repository
  declare -a distributions_name=('ubuntu' 'suse' 'centos' 'debian' 'sc')
  declare -a distributions_static_vm_id=('9082' '9083' '9198' '9674' 'None')
  declare -a distributions_static_vm_ip=('172.16.8.229' '172.16.8.231' '172.16.8.219' '172.16.8.213' 'None')
  declare -a distributions_pid=('' '' '' '' '')                        
  TIME_BETWEEN_DISTR=1800s						# 30 min

  #---------------------------------------------------------------------------------------------------------------------
  # WARNING: DO NOT MODIFY ANYTHING BELOW THIS MESSAGE UNLESS YOU KNOW WHAT YOU ARE DOING
  #---------------------------------------------------------------------------------------------------------------------
  # Check no parameters
  if [[ "$#" -ne 0 ]]; then
     display_error "Incorrect number of parameters"
     usage
     exit 1
  fi
  
  #---------------------------------------------------------------------------------------------------------------------
  # Create package base folder if needed
  mkdir -p ${package_base_folder}

  #---------------------------------------------------------------------------------------------------------------------
  # Package COMPSs SVN Revision
  ${script_dir}/pre_process/package_compss_svn
  if [ $? -ne 0 ]; then
    display_error "Error Packaging COMPSs SVN Revision"
    exit 1
  fi

  #---------------------------------------------------------------------------------------------------------------------
  #Compile COMPSs SVN Revision
  ${script_dir}/pre_process/compile_compss_svn
  if [ $? -ne 0 ]; then
    display_error "Error Compiling COMPSs SVN Revision"
    exit 1
  fi

  #---------------------------------------------------------------------------------------------------------------------
  #Compile and prepare tests structure
  ${script_dir}/tests_pre_process/prepare_tests
  if [ $? -ne 0 ]; then
    display_error "Error Preparing Tests"
    exit 1
  fi

  #---------------------------------------------------------------------------------------------------------------------
  # Execute process in all distributions
  i=0
  while [ $i -lt ${#distributions_name[@]} ]; do
     distr=${distributions_name[$i]}
     static_id=${distributions_static_vm_id[$i]}
     static_ip=${distributions_static_vm_ip[$i]}
     echo -e "\e[0m"
     echo "********************************"
     echo "*** Start process on ${distr}  ***"
     echo "********************************"
     echo -e "\e[0m"

     # Wipe and create log folder
     rm -rf ${log_base_folder}/${distr}
     mkdir -p ${log_base_folder}/${distr}

     # Execute distribution process
     if [ "${distr}" != "sc" ]; then 
       ${script_dir}/pre_process/exec_distribution ${distr} ${static_id} ${static_ip} ${log_base_folder}/${distr} ${package_base_folder} > ${log_base_folder}/${distr}/full_exec.log &
       distributions_pid[$i]=$!
     else
       ${script_dir}/pre_process/exec_sc ${distr} ${log_base_folder}/${distr} ${package_base_folder} > ${log_base_folder}/${distr}/full_exec.log &
       distributions_pid[$i]=$!
     fi
     sleep ${TIME_BETWEEN_DISTR}
     i=$((i+1))
  done

  #---------------------------------------------------------------------------------------------------------------------
  # Waiting all tasks to finish
  echo " "
  echo "--- Main program is waiting all executions to finish @1h..."
  echo " "
  errorStatus=0
  i=0
  while [ $i -lt ${#distributions_name[@]} ]; do
     distr=${distributions_name[$i]}
     pid=${distributions_pid[$i]}
     wait $pid || let "errorStatus+=1"

     echo -e "\e[0m"
     echo "**********************************"
     echo "*** FULL EXECUTION LOG: ${distr}  ***"
     echo "**********************************"
     echo -e "\e[0m"
     cat ${log_base_folder}/${distr}/full_exec.log
     i=$((i+1))
  done

  if [ $errorStatus -ne 0 ]; then
      display_error "A distribution process failed. Please check errors above"
      exit 1
  fi

  #---------------------------------------------------------------------------------------------------------------------
  #End value
  echo " "
  echo " SUCCESS!"
  echo " "
  exit 0

