#!/bin/bash

  #############################################################
  # Name: buildMN_aux
  # Description: SCRIPT FOR LOCAL COMPSs BUILD in MareNostrum
  # Parameters: <targetDir>           Base Target Installation folder
  #
  # ATTENTION: DO NOT EXECUTE THIS FILE. IT IS AUTOMATICALLY
  #            EXECUTED FROM buildMN script
  #############################################################

  usage() {
    echo "Incorrect number of parameters"
    echo " Usage: buildMN5_aux <FullTargetPath>"
    echo " "
    exit 1
  }

  ####################
  # MAIN
  ####################
  # Get parameters
  if [ $# -ne 1 ]; then
    usage
  fi

  # SET SCRIPT VARIABLES
  targetDir=$1
  SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

  # DEFINE MODULES
  modules="impi/2021.10.0 mkl/2023.2.0 oneapi/2023.2.0 intel/2024.0.1-sycl_cuda java-openjdk/11.0.18+10 ear-tools/ear-lite/5.0 papi/7.1.0 gcc/11.4.0"
  unload_before_python=""
  # Plain python modules:
  run_before_py3_modules="ignore"
  py3_modules="python/3.12.1"
  run_before_py3_other_modules="module load impi/2021.10.0 intel/2024.0.1-sycl_cuda mkl/2023.2.0 oneapi/2023.2.0 hdf5/1.14.1-2"
  py3_other_modules="python/3.8.1 MINIFORGE/24.3.0-0 python/3.11.5-gcc python/3.13.0-gcc"
  # MINIFORGE/24.3.0-0 has python 3.10
  # ANACONDA/2023.07 has python 3.11


  # DEFINE CONFIGURATION PARAMETERS
  # (Environment vars must be scaped to get the correct value if not it could take a value previous to load the modules)
  additionalExports='export CFLAGS="-I/usr/include/libxml2/ $CFLAGS"'

  additional_module_use_folder="ignore"
  queues_cfg="mn5_acc.cfg"
  extrae_with_openmpi="false"  # Disabled due to an openmpi error
  openmpi_version="/4.1.5"
  extrae_with_impi="false"  # Disabled due to a fortran error (asked tools)
  impi_version="/2021.10.0"
  autoparallel="false"
  c_binding="false"
  extrae_no_mpi="true"
  r_binding="false"

  # CALL buildSC_aux
  "${SCRIPT_DIR}"/buildSC_aux "${targetDir}" "${modules}" "${unload_before_python}" "${run_before_py3_modules}" "${py3_modules}" "${run_before_py3_other_modules}" "${py3_other_modules}" "${additionalExports}" "${additional_module_use_folder}" "${queues_cfg}" "${extrae_with_openmpi}" "${openmpi_version}" "${extrae_with_impi}" "${impi_version}" "${autoparallel}" "${c_binding}" "${extrae_no_mpi}" "${r_binding}"
  ev=$?

  # End
  if [ $ev -ne 0 ]; then
    echo "ERROR: Exception in auxiliar script"
    exit $ev
  fi
  exit 0
