#!/bin/bash -e
  
  # Obtain parameters
  source_base_dir=$1
  target_base_dir=$2
  
  # Copy dummy Storage jar
  mkdir -p ${target_base_dir}/jars/
  
  cd ${source_base_dir}/../../../../utils/storage/dummyPSCO/
  mvn clean package
  cp -f ./target/compss-dummyPSCO.jar ${target_base_dir}/jars/compss-dummyPSCO.jar
  cd ${source_base_dir}
  
  
  # Copy files
  cp -f ${source_base_dir}/target/29-pscos.jar ${target_base_dir}/pscos.jar   
                  
  cp -f ${source_base_dir}/project.xml ${target_base_dir}/project.xml                  
  cp -f ${source_base_dir}/resources.xml ${target_base_dir}/resources.xml
  
  cp -f ${source_base_dir}/execution ${target_base_dir}/execution
  cp -f ${source_base_dir}/result ${target_base_dir}/result
  
