#!/bin/bash -e
  
  # Obtain parameters
  source_base_dir=$1
  target_base_dir=$2
  
  # Copy dummy Storage jar
  mkdir -p ${target_base_dir}/jars/
  
  cd ${source_base_dir}/../../../../utils/storage/dummyPSCO/
  mvn clean package
  cd -
  cp -f ${source_base_dir}/../../../../utils/storage/dummyPSCO/target/compss-dummyPSCO.jar ${target_base_dir}/jars/compss-dummyPSCO.jar
  
  # Copy files
  cp -f ${source_base_dir}/target/29-pscos.jar ${target_base_dir}/pscos.jar   
                  
  cp -f ${source_base_dir}/project.xml ${target_base_dir}/project.xml                  
  cp -f ${source_base_dir}/resources.xml ${target_base_dir}/resources.xml
  
  cp -f ${source_base_dir}/execution ${target_base_dir}/execution
  cp -f ${source_base_dir}/result_internal ${target_base_dir}/result_internal
  cp -f ${source_base_dir}/result_external ${target_base_dir}/result_external
  
