#!/bin/bash

  # Obtain parameters
  COMPSs_exec=$1
  comm=$2
  runcompss_opts=$3
  base_app_dir=$4
  COMPSs_log_folder=$5
  target_log_folder=$6
  retryNum=$7
  
  # Global exit variable
  exitValue=0
  
  #----------------------------------------------------------------------------------
  # Generate Project.xml according to system
  sed -i '/<InstallDir>/c<InstallDir>'${IT_HOME}'<\/InstallDir>' ${base_app_dir}/project.xml
  
  #----------------------------------------------------------------------------------
  # Create all working dir folders
  mkdir -p /tmp/COMPSsWorker01/
  
  #----------------------------------------------------------------------------------
  # Create storage Conf
  storageConf=${target_log_folder}/storage.conf
  cat > $storageConf << EOF
COMPSsWorker01
EOF
  
  # Add trap to clean folder
  clean() {
    rm -rf /tmp/PSCO/
  }
  trap clean EXIT

  #----------------------------------------------------------------------------------
  # Set Storage implementation location
  storageImplPath=${base_app_dir}/jars/compss-dummyPSCO.jar
  
  #----------------------------------------------------------------------------------
  # Run application 1 - Java PSCOs internalExecution
  echo
  echo "*** RUNNING JAVA APPLICATION PSCOs internalExecution"
  log_folder="${target_log_folder}/internalExecution"
  mkdir -p ${log_folder}
  output_log="${log_folder}/testPSCO_internalExecution_0${retryNum}.outputlog"
  error_log="${log_folder}/testPSCO_internalExecution_0${retryNum}.errorlog"
  expectedTime=60s
  
  timeout --signal=2 $expectedTime ${COMPSs_exec} \
     --project=${base_app_dir}/project.xml \
     --resources=${base_app_dir}/resources.xml \
     --debug \
     --lang=java \
     --comm=$comm \
     --storage_conf=${storageConf} \
     --jvm_workers_opts="-Dit.worker.removeWD=true" \
     ${runcompss_opts} \
     --classpath=${base_app_dir}/pscos.jar:${storageImplPath} \
     testPSCOInternal.Internal > >(tee ${output_log}) 2> >(tee ${error_log} >&2)
  
  
  #Check timeout
  if [[ "$?" = "124" ]]; then
     #Copy LOG files
     cp -rf ${COMPSs_log_folder}/testPSCOInternal.Internal_0${retryNum}/* ${log_folder}
     
     #Report time out
     echo "[WARNING] Java Application timed out" >> ${output_log}
     ev1=124
  else
     #Copy LOG files
     cp -rf ${COMPSs_log_folder}/testPSCOInternal.Internal_0${retryNum}/* ${log_folder}
  
     #Check result
     ${base_app_dir}/result_internal ${output_log} ${log_folder} 
     ev1=$?
  fi
  
  #----------------------------------------------------------------------------------
  # Sleep between applications
  sleep 2s 
  
  #----------------------------------------------------------------------------------
  #Create all working dir folders
  mkdir -p /tmp/COMPSsWorker01/
  
  #----------------------------------------------------------------------------------
  # Run application 2 - Java PSCOs externalExecution
  echo
  echo "*** RUNNING JAVA APPLICATION PSCOs externalExecution"
  log_folder="${target_log_folder}/externalExecution"
  mkdir -p ${log_folder}
  output_log="${log_folder}/testPSCO_externalExecution_0${retryNum}.outputlog"
  error_log="${log_folder}/testPSCO_externalExecution_0${retryNum}.errorlog"
  expectedTime=60s
  
  timeout --signal=2 $expectedTime ${COMPSs_exec} \
     --project=${base_app_dir}/project.xml \
     --resources=${base_app_dir}/resources.xml \
     --debug \
     --lang=java \
     --comm=$comm \
     --storage_conf=${storageConf} \
     --jvm_workers_opts="-Dit.worker.removeWD=true" \
     --task_execution=external \
     --classpath=${base_app_dir}/pscos.jar:${storageImplPath} \
     testPSCOExternal.External > >(tee ${output_log}) 2> >(tee ${error_log} >&2)
  
  
  #Check timeout
  if [[ "$?" = "124" ]]; then
     #Copy LOG files
     cp -rf ${COMPSs_log_folder}/testPSCOExternal.External_0${retryNum}/* ${log_folder}
     
     #Report time out
     echo "[WARNING] Java Application timed out" >> ${output_log}
     ev2=124
  else
     #Copy LOG files
     cp -rf ${COMPSs_log_folder}/testPSCOExternal.External_0${retryNum}/* ${log_folder}
  
     #Check result
     ${base_app_dir}/result_external ${output_log} ${log_folder} 
     ev2=$?
  fi
  
  #----------------------------------------------------------------------------------
  #Return execution status
  if [ $ev1 -ne 0 ]; then
     exitValue=$ev1
  else
     exitValue=$ev2
  fi
  exit $exitValue
