#!/bin/bash -e

  action=$1

  if [ "$action" == "install" ]; then
    if [ $# -eq 2 ]; then
      # Installation knowing previous old version
      oldversion=$2
      echo " "
      echo " * Installing COMPSs Tools from previous version ${oldversion}..."
      echo " "
    else
      # Clean installation
      echo " "
      echo " * Installing COMPSs Tools..."
      echo " "
    fi
  elif [ "$action" == "upgrade" ]; then
    # Upgrade from previous version
    oldversion=$2
    echo " "
    echo " * Upgrading COMPSs Tools from previous version ${oldversion}..."
    echo " "
  elif [ "$action" == "abort-upgrade" ]; then
    # Update failed, recover previous version
    newversion=$2
    echo " "
    echo " * COMPSs Tools $newversion upgrade aborted. Please check errors above."
    echo " "
  fi

