#!/bin/bash -e

  action=$1

  if [ "$action" == "install" ]; then
    if [ $# -eq 2 ]; then
      # Installation knowing previous old version
      oldversion=$2
      echo " "
      echo " * Installing COMPSs Bindings Common from previous version ${oldversion}..."
      echo " "
      rm -rf /opt/COMPSs/Bindings/bindings-common/
    else
      # Clean installation
      echo " "
      echo " * Installing COMPSs Bindings Common..."
      echo " "
    fi
  elif [ "$action" == "upgrade" ]; then
    # Upgrade from previous version
    oldversion=$2
    echo " "
    echo " * Upgrading COMPSs Bindings Common from previous version ${oldversion}..."
    echo " "
    if [ -d "/opt/COMPSs/Bindings/bindings-common" ]; then
      mv /opt/COMPSs/Bindings/bindings-common /tmp/COMPSs_bindings_common.bkp
    fi
  elif [ "$action" == "abort-upgrade" ]; then
    # Update failed, recover previous version
    newversion=$2
    echo " "
    echo " * COMPSs Bindings Common $newversion upgrade aborted. Please check errors above."
    echo " "
    if [ -d "/tmp/COMPSs_bindings_common.bkp" ]; then
      mv /tmp/COMPSs_bindings_common.bkp /opt/COMPSs/Bindings/bindings-common
    fi
  fi

