#!/bin/bash -e

  #############################################################
  # Name: buildAsgard_aux
  # Description: SCRIPT FOR LOCAL COMPSs BUILD in Asgard
  # Parameters: <targetDir> Base Target Installation folder
  #
  # ATTENTION: DO NOT EXECUTE THIS FILE. IT IS AUTOMATICALLY
  #            EXECUTED FROM buildAsgard script
  #############################################################

  usage() {
    echo "Incorrect number of parameters"
    echo " Usage: buildAsgard_aux <FullTargetPath>"
    echo " "
    exit 1
  }

  ####################
  # MAIN
  ####################
  # Get parameters
  if [ $# -ne 1 ]; then
    usage
  fi

  # SET SCRIPT VARIABLES
  targetDir=$1
  SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

  # DEFINE MODULES
  modules="GASNet/1.30.0_17.11.2 OpenMPI/3.1.2_18.08.2 SLURM/18.08 PrgEnv-gcc/1.0.0 OpenSHMEM/1.3 pmix/2.1.4 cmake/3.8.2_gcc UCX/1.2.1 likwid/4.2.0 Eva/1.0.1"
  unload_before_python="ignore"
  run_before_py3_modules="ignore"
  py3_modules="ignore"
  run_before_py3_other_modules="ignore"
  py3_other_modules="ignore"

  # DEFINE CONFIGURATION PARAMETERS
  #(Environment vars must be scaped to get the correct value if not it could take a value previous to load the modules)
  #additionalExports="export BOOST_CPPFLAGS=-I\${BOOST_INCLUDE} PATH=/apps/CEPBATOOLS/deps/libxml2/2.9.4/bin:$PATH"
  #additionalExports="$PATH" #commented because it is not doing anything
  additional_module_use_folder="ignore"
  queues_cfg="asgard.cfg"
  extrae_with_openmpi="true"
  openmpi_version=""
  extrae_with_impi="true"
  impi_version=""
  autoparallel="false"
  c_binding="true"
  extrae_no_mpi="true"
  r_binding="false"

  # CALL buildSC_aux
  "${SCRIPT_DIR}"/buildSC_aux "${targetDir}" "${modules}" "${unload_before_python}" "${run_before_py3_modules}" "${py3_modules}" "${run_before_py3_other_modules}" "${py3_other_modules}" "${additionalExports}" "${additional_module_use_folder}" "${queues_cfg}" "${extrae_with_openmpi}" "${openmpi_version}" "${extrae_with_impi}" "${impi_version}" "${autoparallel}" "${c_binding}" "${extrae_no_mpi}" "${r_binding}"
  ev=$?

  # End
  if [ $ev -ne 0 ]; then
    echo "ERROR: Exception in auxiliar script"
    exit $ev
  fi
  exit 0
