#!/bin/bash -e

  #############################################################
  # Name: buildAsgard_aux
  # Description: SCRIPT FOR LOCAL COMPSs BUILD in Asgard
  # Parameters: <targetDir> Base Target Installation folder
  #
  # ATTENTION: DO NOT EXECUTE THIS FILE. IT IS AUTOMATICALLY
  #            EXECUTED FROM buildAsgard script
  #############################################################

  usage() {
    echo "Incorrect number of parameters"
    echo " Usage: buildAsgard_aux <FullTargetPath>"
    echo " "
    exit 1
  }

  ####################
  # MAIN
  ####################
  # Get parameters
  if [ $# -ne 1 ]; then
    usage
  fi

  # SET SCRIPT VARIABLES
  targetDir=$1
  SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

  modules=""
  py2_modules="ignore"
  py3_modules="ignore"
  #additionalExports="export BOOST_CPPFLAGS=-I\${BOOST_INCLUDE} PATH=/apps/CEPBATOOLS/deps/libxml2/2.9.4/bin:$PATH"
  additionalExports="$PATH"
  queues_cfg="asgard.cfg"
  extrae_with_openmpi="true"
  openmpi_version=""
  extrae_with_impi="true"
  impi_version=""

  "${SCRIPT_DIR}"/buildSC_aux "${targetDir}" "${modules}" "${py2_modules}" "${py3_modules}" "${additionalExports}" "${queues_cfg}" "${extrae_with_openmpi}" "${openmpi_version}" "${extrae_with_impi}" "${impi_version}" "false"
