#!/bin/bash -e
  
  # Obtain parameter
  source_base_dir=$1
  target_base_dir=$2

  # Copy files
  app_name="1_matmul_arrays_gat_java"

  cp "${source_base_dir}"/target/${app_name}.jar "${target_base_dir}"/${app_name}.jar

  cp "${source_base_dir}"/project.xml "${target_base_dir}"/project.xml
  cp "${source_base_dir}"/resources.xml "${target_base_dir}"/resources.xml

  cp "${source_base_dir}"/execution "${target_base_dir}"/execution
  cp "${source_base_dir}"/result "${target_base_dir}"/result

  # Copy result files
  cp "${source_base_dir}"/A2x2.in "${target_base_dir}"/java_matmul_gat_A2x2.in
  cp "${source_base_dir}"/B2x2.in "${target_base_dir}"/java_matmul_gat_B2x2.in
  cp "${source_base_dir}"/C2x2.out "${target_base_dir}"/java_matmul_gat_C2x2.out
