#!/bin/bash

native_environment() {
    export CC=gcc
    export CXX=g++
    export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64/
    export TARGET_HOST=x86_64-linux-gnu
}

target_environment() {
    export CC=arm-linux-gnueabihf-gcc
    export CXX=arm-linux-gnueabihf-g++
    export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-armhf/
    export TARGET_HOST=arm-linux-gnueabihf
}
