#!/bin/bash

  # Obtain parameters
  COMPSs_exec=$1
  comm=$2
  runcompss_opts=$3
  base_app_dir=$4
  COMPSs_log_folder=$5
  target_log_folder=$6
  retry_num=$7
  execution_envs=$8
  
  # Global variables
  AGENT_PIDS=""
  exit_value=0
  NUM_RETRIES="50"
  app_name="5.2_1_agent_blocks_python"
  expectedTime="60s"

  # Traps and Handlers
  function kill_agents() {
    for pid in ${AGENT_PIDS}; do
      kill -SIGINT ${pid}
    done
  }
  trap kill_agents EXIT

  function validate_parallel_running_tasks() {
    starts="${1}"
    ends="${2}"
    min_parallel_tasks=${3}
    limit_parallel_tasks=${4}
    
    already_started=0
    max_parallel_tasks=0
    for start in ${starts}; do
      already_started=$((already_started + 1))
      already_ended="0";
      for end in ${ends}; do
        if [ "${end}" -le "${start}" ]; then
          already_ended=$((already_ended + 1))
        fi
      done
      running_tasks=$((already_started - already_ended))
      if [ "${running_tasks}" -gt "${max_parallel_tasks}" ]; then
        max_parallel_tasks=${running_tasks}
      fi
    done
    if [ ${max_parallel_tasks} -lt "${min_parallel_tasks}" ]; then
      echo "Simultaneous tasks not properly managed. Found ${max_parallel_tasks} running in parallel and at least ${min_parallel_tasks} expected."  > >(tee -a "${error_log}")
      exit 1
    fi
    if [ ${max_parallel_tasks} -gt "${limit_parallel_tasks}" ]; then
      echo "Simultaneous tasks not properly managed. Found ${max_parallel_tasks} running in parallel and only ${limit_parallel_tasks} expected."  > >(tee -a "${error_log}")
      exit 1
    fi
  }


  #----------------------------------------------------------------------------------
  # Generate Project.xml according to system
  sed -i '/<InstallDir>/c<InstallDir>'"${COMPSS_HOME}"'<\/InstallDir>' "${base_app_dir}"/project.xml
  
  #----------------------------------------------------------------------------------
  # Create all working dir folders
  mkdir -p /tmp/COMPSsWorker01/
  
  #----------------------------------------------------------------------------------
  # Run application
  echo ""
  echo "*** RUNNING AGENTS TEST: nested pycompss with multiple agents"
  log_dir="${COMPSs_log_folder}/${app_name}_0${retry_num}/"
  mkdir -p "${log_dir}"
  output_log="${log_dir}test.outputlog"
  error_log="${log_dir}test.errorlog"
  touch "${output_log}"
  touch "${error_log}"

  agent1_log_dir="${log_dir}/COMPSsWorker01"
  agent2_log_dir="${log_dir}/COMPSsWorker02"

  # Starting agent
  compss_agent_start_service \
    --num_agents=2 \
    --agent_name_prefix="COMPSsWorker" \
    --pythonpath="${base_app_dir}/src" \
    --log_dir="${log_dir}" \
    -d \
    --exec_time=${expectedTime} \
    ${runcompss_opts} \
    --project="${base_app_dir}/project.xml" \
    --resources="${base_app_dir}/resources.xml" \
    --lang="PYTHON" \
    --method_name="main" \
    "simple"

  job1_method=$( grep "\"method_name\":" "${agent1_log_dir}/jobs/job1_NEW.out" | cut -c 24- | jq -r '.method_name')
  job2_method=$( grep "\"method_name\":" "${agent2_log_dir}/jobs/job1_NEW.out" | cut -c 24- | jq -r '.method_name')

  if [ ! "${job1_method}" == "main" ]; then
    echo "Unexpected method (${job1_method}) for job 1." > >(tee -a "${error_log}")
    exit 1
  fi
  if [ ! "${job2_method}" == "increment" ]; then
    echo "Unexpected method (${job2_method}) for job 2." > >(tee -a "${error_log}")
    exit 1
  fi
  job1_start=$(grep "hello main" "${agent1_log_dir}/jobs/job1_NEW.out")
  job2_start=$(grep "hello increment" "${agent2_log_dir}/jobs/job1_NEW.out")
  job2_in_value=$(echo "${job2_start}" | cut -d ' ' -f3)
  job2_in_str=$(echo "${job2_start}" | cut -d ' ' -f4)
  job1_end=$(grep "Updated object" "${agent1_log_dir}/jobs/job1_NEW.out")
  job1_end_value=$(echo "${job1_end}" | cut -d ' ' -f3)
  job1_end_str=$(echo "${job1_end}" | cut -d ' ' -f4)

  if [ ! "${job1_start}" == "hello main" ]; then
    echo "Main task didn't reach start point." > >(tee -a "${error_log}")
    exit 1
  fi
  job2_message=$(echo "${job2_start}" | awk '{print $1 " " $2}')
  if [ ! "${job2_message}" == "hello increment" ]; then
    echo "Increment task didn't reach start point." > >(tee -a "${error_log}")
    exit 1
  fi
  job1_message=$(echo "${job1_end}" | awk '{print $1 " " $2}')
  if [ ! "${job1_message}" == "Updated object" ]; then
    echo "Main task didn't reach start point." > >(tee -a "${error_log}")
    exit 1
  fi
  expected_value=$((job2_in_value + 1))
  if [ ! "${job1_end_value}" == "${expected_value}" ]; then
    echo "Unexpected integer value obtained from the test. Expecting ${expected_value} and ${job1_end_val} observed!" > >(tee -a "${error_log}")
    exit 1
  fi
  if [ ! "${job1_end_str}" == "${job2_in_str}" ]; then
    echo "Test modified the string value of the object and it shouldn't." > >(tee -a "${error_log}")
    exit 1
  fi

  echo "All task executed as expected and with the expected values." 

  # Copy LOG files
  cp -rf "${COMPSs_log_folder}/${app_name}_0${retry_num}"/* "${target_log_folder}"
  exit_value=0

  #----------------------------------------------------------------------------------
  # Return execution status
  exit ${exit_value}

