#!/bin/bash -e
  #Get parameters
  vm_type=$1
  vm_user=$2

  #---------------------------------------------------------------------------------------------------------------------
  #Prepare vm to lauch tests.
  ssh -t -t -o StrictHostKeyChecking=no -o BatchMode=yes -o ChallengeResponseAuthentication=no bscgrid20.bsc.es "~/manageVM/create_VM ${vm_type} ${vm_user}"

  #All process OK. Exit
  exit 0

