#!/bin/bash -e

  # Get parameters
  vm_id=$1
  vm_type=$2
  log_folder=$3

  echo "- Performing live snapshot"

  #---------------------------------------------------------------------------------------------------------------------
  # Perform live snapshot
  echo "--- Creating live snapshot..."
  ssh -t -t -o StrictHostKeyChecking=no -o BatchMode=yes -o ChallengeResponseAuthentication=no bscgrid20.bsc.es "~/manageVM/do_live_snapshot_VM ${vm_id} ${vm_type}" > >(tee ${log_folder}/snapshot.log)    
  snapshot_id=$(cat ${log_folder}/snapshot.log | grep " - New snapshot ID: " | cut -c 21- | tr -d '\r')
  echo "       Sucess"

  # Wait for OpenNebula to release created snapshot
  sleep 120s
  
  # Save snapshot
  echo "--- Saving snapshot..."
  ssh -t -t -o StrictHostKeyChecking=no -o BatchMode=yes -o ChallengeResponseAuthentication=no bscgrid20.bsc.es "~/manageVM/save_snapshot_VM ${snapshot_id} ${vm_type}"
  echo "       Sucess"

  # All process OK. Exit
  echo "- Snapshot DONE"
  exit 0

