#!/bin/bash

  # Get parameters
  vm_type=$1
  vm_user=$2
  vm_ip=$3

  # Script variables
  script_dir=$(dirname $0)
  clean_script=clean_${vm_type}.sh

  echo "- Final clean VM"

  #---------------------------------------------------------------------------------------------------------------------
  # Deploy scripts
  scp -r -o StrictHostKeyChecking=no ${script_dir}/${clean_script} ${vm_user}@${vm_ip}:/home/${vm_user}/

  #---------------------------------------------------------------------------------------------------------------------
  # Clean VM
  echo "-- Cleaning COMPSs installation"
  ssh -t -t -o StrictHostKeyChecking=no -o BatchMode=yes -o ChallengeResponseAuthentication=no ${vm_user}@${vm_ip} "/home/${vm_user}/${clean_script}"
  ssh -t -t -o StrictHostKeyChecking=no -o BatchMode=yes -o ChallengeResponseAuthentication=no ${vm_user}@${vm_ip} "rm -f /home/${vm_user}/${clean_script}"

  # All process OK. Exit
  echo "- DONE: Image fully cleaned"
  exit 0

