#!/bin/bash

  # Obtain parameters
  COMPSs_exec=$1
  comm=$2
  runcompss_opts=$3
  base_app_dir=$4
  COMPSs_log_folder=$5
  target_log_folder=$6
  retry_num=$7
  execution_envs=$8
  
  # Global variables
  exit_value=1
  jar_name="3_object_deregister.jar"
  app_name="objectDeregister.ObjectDeregister"
  
  #----------------------------------------------------------------------------------
  # Generate Project.xml according to system
  sed -i '/<InstallDir>/c<InstallDir>'"${COMPSS_HOME}"'<\/InstallDir>' "${base_app_dir}"/project.xml

  #----------------------------------------------------------------------------------
  # Create all working dir folders
  mkdir -p /tmp/COMPSsWorker01/
 
  gcc -g -ggdb -shared -fPIC -o libagent.so -I"${JAVA_HOME}"/include -I"${JAVA_HOME}"/include/linux c/agent.cpp

  #----------------------------------------------------------------------------------
  # Run application
  echo
  echo "*** RUNNING JAVA APPLICATION OBJECT DEREGISTER"
  output_log="${target_log_folder}/objectDeregister_0${retry_num}.outputlog"
  error_log="${target_log_folder}/objectDeregister_0${retry_num}.errorlog"
  expectedTime=120s
  
  # shellcheck disable=SC2086
  timeout --signal=2 $expectedTime "${COMPSs_exec}" \
     --project="${base_app_dir}"/project.xml \
     --resources="${base_app_dir}"/resources.xml \
     \
     --jvm_master_opts="-agentpath:${base_app_dir}/libagent.so,-Djava.library.path=${base_app_dir}" \
     \
     --jvm_workers_opts="-agentpath:${base_app_dir}/libagent.so,-Djava.library.path=${base_app_dir}" \
     \
     --comm="$comm" \
     \
     --debug \
     --summary \
     ${runcompss_opts} \
     \
     --classpath="${base_app_dir}/${jar_name}" \
     \
     "${app_name}" 1 > >(tee "${output_log}") 2> >(tee "${error_log}" >&2)

  # For checking JVM: 
     #--jmx_port=9011
     #--jvm_master_opts="-Dcom.sun.management.jmxremote,\
     #-Dcom.sun.management.jmxremote.port=9011,-Dcom.sun.management.jmxremote.local.only=false,\
     #-Dcom.sun.management.jmxremote.authenticate=false,-Dcom.sun.management.jmxremote.ssl=false"\
     
  # Check timeout
  res=$?
  
  if [[ "$res" = "124" ]]; then
     # Copy LOG files
     cp -rf "${COMPSs_log_folder}/${app_name}_0${retry_num}"/* "${target_log_folder}"
     
     # Report time out
     echo "[WARNING] Java Application timed out" >> "${output_log}"
     exit_value=124
  else
     # Copy LOG files
     cp -rf "${COMPSs_log_folder}/${app_name}_0${retry_num}"/* "${target_log_folder}"
  
     # Check result
     "${base_app_dir}"/result "${output_log}" "${error_log}" "${target_log_folder}"
     exit_value=$?
  fi
  
  #----------------------------------------------------------------------------------
  # Return execution status
  exit ${exit_value}
