#!/bin/bash -e
  
  # Obtain parameters
  source_base_dir=$1
  target_base_dir=$2
  
  # Copy files
  cp "${source_base_dir}"/target/90-compss.jar "${target_base_dir}"/compss.jar

  cp "${source_base_dir}"/project.xml "${target_base_dir}"/project.xml
  cp "${source_base_dir}"/resources.xml "${target_base_dir}"/resources.xml
  
  cp "${source_base_dir}"/execution "${target_base_dir}"/execution
  cp "${source_base_dir}"/result "${target_base_dir}"/result
  
