#!/bin/bash -e

  #############################################################
  # Name: buildMN_aux
  # Description: SCRIPT FOR LOCAL COMPSs BUILD in Nord 3
  # Parameters: <targetDir>           Base Target Installation folder
  #
  # ATTENTION: DO NOT EXECUTE THIS FILE. IT IS AUTOMATICALLY
  #            EXECUTED FROM buildMN script
  #############################################################

  usage() {
    echo "Incorrect number of parameters"
    echo " Usage: buildNord_aux <FullTargetPath>"
    echo " "
    exit 1
  }

  ####################
  # MAIN
  ####################
  # Get parameters
  if [ $# -ne 1 ]; then
    usage
  fi

  # SET SCRIPT VARIABLES
  targetDir=$1
  SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

  modules="intel/13.0.1 transfer/1.0 bsc/current BOOST/1.52.0_py_3.3.0 java/1.8.0u66 PAPI/5.4.1 gcc/7.2.0"
  py2_modules="PYTHON/2.7.3"
  py3_modules="module load PYTHON/3.3.0 Boost/1.52.0_py_3.3.0"
  additionalExports=""
  queues_cfg="nord.cfg"
  extrae_with_openmpi="true"
  openmpi_version="/1.8.1"
  extrae_with_impi="true"
  impi_version=""

  "${SCRIPT_DIR}"/buildSC_aux "${targetDir}" "${modules}" "${py2_modules}" "${py3_modules}" "${additionalExports}" "${queues_cfg}" "${extrae_with_openmpi}" "${openmpi_version}" "${extrae_with_impi}" "${impi_version}" "false"
