#!/bin/bash -e

  #############################################################
  # Name: buildMN_aux
  # Description: SCRIPT FOR LOCAL COMPSs BUILD in Nord 3
  # Parameters: <targetDir>           Base Target Installation folder
  #
  # ATTENTION: DO NOT EXECUTE THIS FILE. IT IS AUTOMATICALLY
  #            EXECUTED FROM buildMN script
  #############################################################

  usage() {
    echo "Incorrect number of parameters"
    echo " Usage: buildNord_aux <FullTargetPath>"
    echo " "
    exit 1
  }

  ####################
  # MAIN
  ####################
  # Get parameters
  if [ $# -ne 1 ]; then
    usage
  fi

  # SET SCRIPT VARIABLES
  targetDir=$1
  SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

  # DEFINE MODULES
  modules="intel/13.0.1 transfer/1.0 bsc/current PYTHON/2.7.3 BOOST/1.52.0 java/1.8.0u66 PAPI/5.4.1 gcc/7.2.0"
  unload_before_python="ignore"
  py2_modules="PYTHON/2.7.3"
  py3_modules="PYTHON/3.5.1-INTEL"
  py3_other_modules="ignore"

  # DEFINE CONFIGURATION PARAMETERS
  additionalExports="PATH=/apps/BSCTOOLS/deps/libxml/2.9.4/bin:/apps/BSCTOOLS/deps/autotools/bin:$PATH"
  additional_module_use_folder="ignore"
  queues_cfg="nord.cfg"
  extrae_with_openmpi="true"
  openmpi_version="/1.8.1"
  extrae_with_impi="true"
  impi_version=""
  autoparallel="false"

  # CALL buildSC_aux
  "${SCRIPT_DIR}"/buildSC_aux "${targetDir}" "${modules}" "${unload_before_python}" "${py2_modules}" "${py3_modules}" "${py3_other_modules}" "${additionalExports}" "${additional_module_use_folder}" "${queues_cfg}" "${extrae_with_openmpi}" "${openmpi_version}" "${extrae_with_impi}" "${impi_version}" "${autoparallel}"
  ev=$?

  # End
  if [ $ev -ne 0 ]; then
    echo "ERROR: Exception in auxiliar script"
    exit $ev
  fi
  exit 0
