#!/bin/bash

  # Obtain parameters
  COMPSs_exec=$1
  comm=$2
  runcompss_opts=$3
  base_app_dir=$4
  COMPSs_log_folder=$5
  target_log_folder=$6
  retry_num=$7
  execution_envs=$8
  
  # Global variables
  AGENT_PIDS=""
  exit_value=0
  NUM_RETRIES="50"
  jar_name="1.1_1_agent_10000_tasks.jar"
  app_name="1.1_1_agent_10000_tasks"

  # Traps and Handlers
  function kill_agents() {
    for pid in ${AGENT_PIDS}; do
      kill -SIGINT ${pid}
    done
  }
  trap kill_agents EXIT


  #----------------------------------------------------------------------------------
  # Generate Project.xml according to system
  sed -i '/<InstallDir>/c<InstallDir>'"${COMPSS_HOME}"'<\/InstallDir>' "${base_app_dir}"/project.xml
  
  #----------------------------------------------------------------------------------
  # Create all working dir folders
  mkdir -p /tmp/COMPSsWorker01/
  
  #----------------------------------------------------------------------------------
  # Run application
  echo ""
  echo "*** RUNNING AGENTS TEST: 1 agent compss - 10000 tasks"
  log_dir="${COMPSs_log_folder}/${app_name}_0${retry_num}/"
  mkdir -p "${log_dir}"
  output_log="${log_dir}test.outputlog"
  error_log="${log_dir}test.errorlog"
  touch "${output_log}"
  touch "${error_log}"

  # Starting agent
  agent1_log_dir="${log_dir}/agent1/"
  mkdir -p "${agent1_log_dir}" 
  agent1_output_log="${log_dir}agent1.outputlog"
  agent1_error_log="${log_dir}agent1.errorlog"

  compss_agent_start \
    --hostname="COMPSsWorker01" \
    --classpath="${base_app_dir}/${jar_name}" \
    --log_dir="${agent1_log_dir}" \
    --rest_port="46101" \
    --comm_port="46102" \
    --reuse_resources_on_block="false" \
    --scheduler=es.bsc.compss.scheduler.orderstrict.fifo.FifoTS \
    -d \
    ${runcompss_opts} \
    --project="${base_app_dir}/project.xml" \
    --resources="${base_app_dir}/resources.xml" 1>"${agent1_output_log}" 2>"${agent1_error_log}" &

  agent_pid="$!"
  AGENT_PIDS="${AGENT_PIDS} ${agent_pid}"

  retries="${NUM_RETRIES}"
  curl -XGET http://127.0.0.1:46101/COMPSs/test 1>/dev/null 2>/dev/null
  ev=$?
  while [ "$ev" != "0" ] && [ "${retries}" -gt "0" ]; do
    sleep 2s
    retries=$((retries - 1 ))
    curl -XGET http://127.0.0.1:46101/COMPSs/test 1>/dev/null 2>/dev/null
    ev=$?
  done

  RESULT=$(grep "test invoked" "${agent1_output_log}")
  if [ -z "${RESULT}" ]; then  
     echo "Agent failed to start" > >(tee -a "${error_log}")
     exit 1
  fi
  echo "Agent started" > >(tee -a "${output_log}")
  sleep 2s
 
  # CHECK WHETHER THE PROJECT FILE HAS BEEN PROPERLY READ
  RESOURCES=$(curl -XGET http://127.0.0.1:46101/COMPSs/resources 2>/dev/null)
  num_RESOURCES=$(echo "${RESOURCES}" | jq '.resources | length')
  if [ ! "${num_RESOURCES}" == "1" ]; then
    echo "Wrong number of RESOURCE tags on the agent's output. Found .${num_RESOURCES}.; 1 expected." > >(tee -a "${error_log}")
    exit 1
  fi
  RESOURCE=$(echo "${RESOURCES}" | jq '.resources[] | select(.name=="COMPSsWorker01")')
  if [ -z "${RESOURCE}" ]; then
    echo "Wrong Resource on Agent; COMPSsWorker01 expected." > >(tee -a "${error_log}")
    exit 1
  fi
  DESCRIPTION=$(echo "${RESOURCE}" | jq '.description ')
  PROCESSOR_COUNT=$(echo "${DESCRIPTION}" | jq '.processors | length')
  if [ ! "${PROCESSOR_COUNT}" == "1" ]; then
    echo "Wrong number of Processors configured for the Agent. Found ${PROCESSOR_COUNT}; 1 expected." > >(tee -a "${error_log}")
    exit 1
  fi
  CPU_COUNT=$(echo "${DESCRIPTION}" | jq '.processors[] | select(.name=="MainProcessor") | .units')
  if [ ! "${CPU_COUNT}" == "4" ]; then
    echo "Wrong number of CPU cores configured for the Agent. Found ${CPU_COUNT}; 4 expected." > >(tee -a "${error_log}")
    exit 1
  fi

  NUM_TASKS="10000"
  # Invoking DemoFunction method
  "${COMPSS_HOME}/Runtime/scripts/user/compss_agent_call_operation" \
   --master_node="127.0.0.1" \
   --master_port="46101" \
   --method_name="demoFunction" \
   --cei="es.bsc.compss.test.DemoClassItf" \
   --stop \
   es.bsc.compss.test.DemoClass "${NUM_TASKS}" > >(tee -a "${output_log}") 2> >(tee -a "${error_log}")
   ev=$?

  echo "Waiting for ${agent_pid} to end"
  wait ${agent_pid}
  submitted_jobs=$(ls "${agent1_log_dir}jobs" | grep -c out)
  expected_jobs=$(( NUM_TASKS + 1))
  if [ ! "${submitted_jobs}" == "${expected_jobs}" ]; then
    echo "Unexpected number of submitted jobs; ${expected_jobs} expected and ${submitted_jobs} executed." > >(tee -a "${error_log}")
    exit 1
  fi

  #----------------------------------------------------------------------------------
  # Return execution status
  exit ${exit_value}
  
