#!/bin/bash -e


  #Obtain parameters
  COMPSs_exec=$1
  comm=$2
  runcompss_opts=$3
  base_app_dir=$4
  COMPSs_log_folder=$5
  target_log_folder=$6
  retryNum=$7

  #Global exit variable
  exitValue=0

  # Download the specified Redis Version, unzip it, compile the redis-server
  # utility, move it to the main folder and execute the main test
  REDIS_VERSION=$(cat REDIS-VERSION)
  REDIS_URL=http://download.redis.io/releases
  REDIS_FOLDER=redis-${REDIS_VERSION}
  REDIS_TAR_NAME=${REDIS_FOLDER}.tar.gz
  # Download Redis
  wget ${REDIS_URL}/${REDIS_TAR_NAME}
  # Uncompress it
  tar -xzvf ${REDIS_TAR_NAME}
  rm ${REDIS_TAR_NAME}
  # Go to the Redis directory and compile the redis-server utility
  cd ${REDIS_FOLDER}
  make redis-server
  cd ..
  # Move the redis-server executable to the main folder
  cp ${REDIS_FOLDER}/src/redis-server redis-server
  rm -rf ${REDIS_FOLDER}

  # Bundle-related variables
  bundle_path=${base_app_dir}/COMPSs-Redis-bundle

  # Set a single standalone Redis instance
  ./redis-server --daemonize yes

  # Create a storage_conf file
  storage_conf=${base_app_dir}/storage.conf
  cat > $storage_conf << EOF
COMPSsWorker01
EOF

  # Add trap to kill redis instance/s
  clean() {
    pkill redis
  }
  trap clean EXIT

  #----------------------------------------------------------------------------------
  #Generate Project.xml according to system
  sed -i '/<InstallDir>/c<InstallDir>'${COMPSS_HOME}'<\/InstallDir>' ${base_app_dir}/project.xml

  #----------------------------------------------------------------------------------
  #Create all working dir folders
  mkdir -p /tmp/COMPSsWorker01/

  #----------------------------------------------------------------------------------
  #Run application 1 - Test
  echo
  echo "*** RUNNING PYTHON REDIS PSCO TEST"
  output_log="${target_log_folder}/python_test_0${retryNum}.outputlog"
  error_log="${target_log_folder}/python_test_0${retryNum}.errorlog"
  expectedTime=360s

  echo "Storage conf path is ${storage_conf}"

  timeout --signal=2 $expectedTime ${COMPSs_exec} \
     --storage_conf=${storage_conf} \
     --pythonpath=${base_app_dir}/src:${bundle_path}/python \
     --classpath=${bundle_path}/compss-redisPSCO.jar \
     --project=${base_app_dir}/project.xml \
     --resources=${base_app_dir}/resources.xml \
     --debug \
     --comm=$comm \
     ${runcompss_opts} \
     --lang=python \
     ${base_app_dir}/src/testredis.py > >(tee ${output_log}) 2> >(tee ${error_log} >&2)

  #Check timeout
  if [[ "$?" = "124" ]]; then
     #Copy LOG files
     cp -rf ${COMPSs_log_folder}/testredis.py_0${retryNum}/* ${target_log_folder}

     #Report timeout
     echo "[WARNING] Python Application timed out" >> ${output_log}
     exitValue=124
  else
     #Copy LOG files
     cp -rf ${COMPSs_log_folder}/testredis.py_0${retryNum}/* ${target_log_folder}

     #Check result
     ${base_app_dir}/result ${output_log} ${error_log} ${target_log_folder}
     exitValue=$?
  fi

  #----------------------------------------------------------------------------------
  #Return execution status
  exit $exitValue
