#!/bin/bash -e
  
  # Obtain parameter
  source_base_dir=$1
  target_base_dir=$2

  # Copy files
  cp "${source_base_dir}"/execution "${target_base_dir}"/execution
  cp "${source_base_dir}"/result "${target_base_dir}"/result
  cp "${source_base_dir}"/result2.sh "${target_base_dir}"/result2
  cp "${source_base_dir}"/result3.sh "${target_base_dir}"/result3

  cp -r "${source_base_dir}"/src "${target_base_dir}"

  cp "${source_base_dir}"/project.xml "${target_base_dir}"/project.xml
  cp "${source_base_dir}"/resources.xml "${target_base_dir}"/resources.xml