#!/bin/bash

  # Obtain parameters
  COMPSs_exec=$1
  comm=$2
  runcompss_opts=$3
  base_app_dir=$4
  COMPSs_log_folder=$5
  target_log_folder=$6
  retry_num=$7
  execution_envs=$8
  
  # Global variables
  jar_name="0_graph.jar"
  
  #----------------------------------------------------------------------------------
  # Generate Project.xml according to system
  sed -i '/<InstallDir>/c<InstallDir>'"${COMPSS_HOME}"'<\/InstallDir>' "${base_app_dir}"/project.xml
  
  #----------------------------------------------------------------------------------
  # Create all working dir folders
  mkdir -p /tmp/COMPSsWorker01/
  
  #----------------------------------------------------------------------------------
  applications="simpleTests.Barrier simpleTests.Independent simpleTests.IndependentWithSync simpleTests.SingleChain simpleTests.SingleLongChain complexTests.TripleChainNoSync complexTests.TripleChainOneSync complexTests.TripleChainDoubleSync"
  for app in $applications; do
    echo
    echo "*** RUNNING JAVA APPLICATION $app"
    appLogFolder=${target_log_folder}/$app
    mkdir -p "${appLogFolder}"
    output_log="${appLogFolder}/${app}_0${retry_num}.outputlog"
    error_log="${appLogFolder}/${app}_0${retry_num}.errorlog"
    ev=1
    expectedTime=240s
    # shellcheck disable=SC2086
    timeout --signal=2 $expectedTime "${COMPSs_exec}" \
      --project="${base_app_dir}"/project.xml \
      --resources="${base_app_dir}"/resources.xml \
      \
      --comm="$comm" \
      \
      --debug \
      -g \
      ${runcompss_opts} \
      \
      --classpath="${base_app_dir}/${jar_name}" \
      \
      --specific_log_dir="${COMPSs_log_folder}/${app}_0${retry_num}" \
      \
      $app > >(tee "${output_log}") 2> >(tee "${error_log}" >&2)
      
    # Check timeout
    if [[ "$?" = "124" ]]; then
      # Copy LOG files
      cp -rf "${COMPSs_log_folder}/${app}_0${retry_num}"/* "${appLogFolder}"
     
      # Report time out
      echo "[WARNING] Java Application timed out" >> "${output_log}"
      ev=124
    else
      # Copy LOG files
      cp -rf "${COMPSs_log_folder}/${app}_0${retry_num}"/* "${appLogFolder}"
    
      # Check result
      "${base_app_dir}"/result "${output_log}" "${error_log}" "${appLogFolder}" "${base_app_dir}" "${app}"
      ev=$?
    fi
    
    if [ $ev -ne 0 ]; then
      exit $ev
    fi
  done

  #----------------------------------------------------------------------------------
  # Return execution status
  exit 0
