#!/bin/bash

  #Obtain parameters
  COMPSs_exec=$1
  comm=$2
  runcompss_opts=$3
  base_app_dir=$4
  COMPSs_log_folder=$5
  target_log_folder=$6 
  master_template_id=$7
  os_type=$8
  owner=$9
  appName=Simple
  
  #Global variables
  exitValue=0
  cert_suffix=.pem
  remote_certs_dir=${base_app_dir}/certs
  remote_apps_dir=${base_app_dir}/apps
  
  mkdir -p ${remote_certs_dir}
  mkdir -p ${remote_apps_dir}
  
  #----------------------------------------------------------------------------------
  #Create project and resources XML
  cp -f ${base_app_dir}/project_multiProvider_base.xml ${base_app_dir}/project_multiProvider.xml
  sed -i 's/<Image Name=\"uuid_XX_compss_testing_XX\">/<Image Name=\"uuid_'$os_type'_compss_testing_'$master_template_id'\">/g' ${base_app_dir}/project_multiProvider.xml 
  sed -i '/<Value>jenkins-test.pem<\/Value>/c<Value>'${remote_certs_dir}'\/jenkins-test.pem<\/Value>' ${base_app_dir}/project_multiProvider.xml
  sed -i '/<Source>'$appName'.tar.gz<\/Source>/c<Source>'${remote_apps_dir}'\/'$appName'.tar.gz<\/Source>' ${base_app_dir}/project_multiProvider.xml
  cp -f ${base_app_dir}/resources_multiProvider_base.xml ${base_app_dir}/resources_multiProvider.xml
  sed -i 's/<Image Name=\"uuid_XX_compss_testing_XX\">/<Image Name=\"uuid_'$os_type'_compss_testing_'$master_template_id'\">/g' ${base_app_dir}/resources_multiProvider.xml
  
  #Create package
  mkdir ${base_app_dir}/tmp
  cp ${base_app_dir}/project_multiProvider.xml ${base_app_dir}/tmp/project_multiProvider.xml
  cp ${base_app_dir}/resources_multiProvider.xml ${base_app_dir}/tmp/resources_multiProvider.xml
  cp ${base_app_dir}/${appName}.jar ${base_app_dir}/tmp/${appName}.jar
  cd ${base_app_dir}/tmp/
  tar zcf ${appName}.tar.gz *
  cd $(dirname $0)
  cp -f ${base_app_dir}/tmp/${appName}.tar.gz ${remote_apps_dir}
  
  #Create cert structure
  cp -f ${base_app_dir}/${owner}${cert_suffix} ${remote_certs_dir};
    
  #----------------------------------------------------------------------------------
  #Run application 1 - MULTI Provider
  echo
  echo "*** RUNNING JAVA APPLICATION ELASTICITY - MULTI PROVIDER"
  output_log="${target_log_folder}/multiProvider.outputlog"
  error_log="${target_log_folder}/multiProvider.errorlog"
  
  expectedTime=2400s
  counterVal=1
  numTasks=50
  minVM=1
  maxVM=3
  creationTime=120
  
  timeout --signal=2 $expectedTime ${COMPSs_exec} \
     --project=${base_app_dir}/project_multiProvider.xml \
     --resources=${base_app_dir}/resources_multiProvider.xml \
     --debug \
     --comm=$comm \
     ${runcompss_opts} \
     --lang=java \
     --classpath=${base_app_dir}/${appName}.jar \
     simple.Simple $counterVal $numTasks $minVM $maxVM $creationTime > >(tee ${output_log}) 2> >(tee ${error_log} >&2)
    
  #Check timeout
  if [[ "$?" = "124" ]]; then  
     #Copy LOG files
     cp -rf ${COMPSs_log_folder}/simple.Simple_01/* ${target_log_folder}

     #Report time out
     echo "[WARNING] Java Application timed out" >> ${output_log}
     exitValue=124
  else
     #Copy LOG files
     cp -rf ${COMPSs_log_folder}/simple.Simple_01/* ${target_log_folder}
  
     #Check result
     sleep 60
     ${base_app_dir}/result ${output_log} ${target_log_folder} $minVM $maxVM
     exitValue=$?
  fi
  
  
  #----------------------------------------------------------------------------------
  #Return execution status
  exit $exitValue
  
  
