#!/bin/bash -e

  # Get parameters
  vm_ip=$1
  vm_type=$2
  vm_user=$3

  # Define script variables
  script_dir=$(dirname $0)
  installer_script=install_compss_${vm_type}.sh

  #---------------------------------------------------------------------------------------------------------------------
  # Installing COMPSs from repository
  echo -e "\e[0m"
  echo "*****************************"
  echo "*** Install COMPSs on VM  ***"
  echo "*****************************"
  echo -e "\e[0m"

  # Deploy install script
  echo "--- Deploying install script..."
  scp -o StrictHostKeyChecking=no ${script_dir}/${installer_script} ${vm_user}@${vm_ip}:/home/${vm_user}/
  echo "      Success"

  # Installing COMPSs
  echo "--- Installing COMPSs..."
  ssh -t -t -o StrictHostKeyChecking=no -o BatchMode=yes -o ChallengeResponseAuthentication=no ${vm_user}@${vm_ip} "sudo sh /home/${vm_user}/${installer_script}"
  echo "      Success"

  # Clearing COMPSs installing script
  echo "--- Clearing COMPSs install script..."
  ssh -t -t -o StrictHostKeyChecking=no -o BatchMode=yes -o ChallengeResponseAuthentication=no ${vm_user}@${vm_ip} "rm -f /home/${vm_user}/${installer_script}"
  echo "      Success"

  # All process OK. Exit
  exit 0

