#!/bin/bash

  # Obtain parameters
  COMPSs_exec=$1
  comm=$2
  runcompss_opts=$3
  base_app_dir=$4
  COMPSs_log_folder=$5
  target_log_folder=$6
  retryNum=$7
  
  # Global variables
  exitValue=0
  appName=SimpleExtAdaptation
  
  #----------------------------------------------------------------------------------
  # Create project and resources XML
  sed -i '/<InstallDir>/c<InstallDir>'"${COMPSS_HOME}"'<\/InstallDir>' "${base_app_dir}"/project.xml
  
  #----------------------------------------------------------------------------------
  # Run application 1 - One Provider
  echo
  echo "*** RUNNING JAVA APPLICATION ELASTICITY - ONE PROVIDER"
  output_log="${target_log_folder}/oneProvider.outputlog"
  error_log="${target_log_folder}/oneProvider.errorlog"
  
  expectedTime=4600s
  counterVal=1
  numTasks=15
  minVM=1
  maxVM=3
  creationTime=20
  set -m

  # shellcheck disable=SC2086
  timeout --signal=2 $expectedTime "${COMPSs_exec}" \
     --project="${base_app_dir}"/project.xml \
     --resources="${base_app_dir}"/resources.xml \
     \
     --comm="$comm" \
     --conn=es.bsc.compss.connectors.DefaultNoSSHConnector \
     --enable_external_adaptation=true \
     \
     --debug \
     ${runcompss_opts} \
     \
     --classpath="${base_app_dir}"/"${appName}".jar \
     \
     simple.SimpleExtAdaptation $counterVal $numTasks $minVM $maxVM $creationTime > >(tee "${output_log}") 2> >(tee "${error_log}" >&2) &

  sleep $creationTime
  sleep 1
  compss_adapt_resources localhost simple.SimpleExtAdaptation_0"${retryNum}" CREATE BSC small image_2 > >(tee "${output_log}") 2> >(tee "${error_log}" >&2)
  sleep 1
  compss_adapt_resources localhost simple.SimpleExtAdaptation_0"${retryNum}" CREATE BSC small image_3 > >(tee "${output_log}") 2> >(tee "${error_log}" >&2)
  sleep $creationTime
  sleep 10
  compss_adapt_resources localhost simple.SimpleExtAdaptation_0"${retryNum}" REMOVE BSC 127.0.0.100 > >(tee "${output_log}") 2> >(tee "${error_log}" >&2)
  sleep 1
  compss_adapt_resources localhost simple.SimpleExtAdaptation_0"${retryNum}" REMOVE BSC 127.0.0.101 > >(tee "${output_log}") 2> >(tee "${error_log}" >&2)
  fg %1

  # Check timeout
  if [[ "$?" = "124" ]]; then
     # Copy LOG files
     cp -rf "${COMPSs_log_folder}"/simple.SimpleExtAdaptation_0"${retryNum}"/* "${target_log_folder}"
     
     # Report time out
     echo "[WARNING] Java Application timed out" >> "${output_log}"
     exitValue=124
  else
     # Copy LOG files
     cp -rf "${COMPSs_log_folder}"/simple.SimpleExtAdaptation_0"${retryNum}"/* "${target_log_folder}"
  
     # Check result
     sleep 10
     "${base_app_dir}"/result "${output_log}" "${target_log_folder}" $minVM $maxVM
     exitValue=$?
  fi
  
  #----------------------------------------------------------------------------------
  # Return execution status
  exit $exitValue
