#!/bin/bash

  #
  # SCRIPT GLOBAL CONSTANTS
  #

  SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"


  #
  # SCRIPT GLOBAL HELPERS
  #

  source ${SCRIPT_DIR}/commons


  #
  # SCRIPT HELPERS
  #

  remove_symbolic_links (){
      get_packages_folder $1
      echo "Cleaning PyCOMPSs symbolic links from ${packages_folder}"
      rm ${packages_folder}/pycompss
      rm ${packages_folder}/compss*.so
      rm ${packages_folder}/thread_affinity*.so
  }

  #
  # MAIN
  #

  if [ -d "${SCRIPT_DIR}/2" ]; then
      remove_symbolic_links python2
  fi
  if [ -d "${SCRIPT_DIR}/3" ]; then
      remove_symbolic_links python3
  fi