#!/usr/bin/env python3
#
#  Copyright 2002-2026 Barcelona Supercomputing Center (www.bsc.es)
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

"""
Generate semantics script that reads from a source directory and creates files in target directory.
"""

import argparse
import os
import sys
import re

# Destination files header comments:
NOTIFICATION = [
    "Autogenerated file (see generate_enum.py).",
    " - Uses DataType.java as the source template.",
]

# Enable/disable debugging
DEBUG = True


def validate_arguments(args):
    """Validate command-line arguments."""
    if not os.path.exists(args.source):
        print(f"Error: Source path '{args.source}' does not exist", file=sys.stderr)
        sys.exit(1)

    if not os.path.isfile(args.source):
        print(f"Error: Source path '{args.source}' is not a file", file=sys.stderr)
        sys.exit(1)

    return True



def parse_java_enum(file_path):
    """
    Parse a Java enum file and extract class name and enum values with their IDs.

    Returns a dict with 'enum_class_name' and 'values' (map of value names to IDs).
    Returns None if the file doesn't contain a valid enum.
    """
    if DEBUG:
        print(f"- Getting enum values...")

    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()

        # Extract enum class name
        enum_class_pattern = r'public\s+enum\s+(\w+)'
        enum_match = re.search(enum_class_pattern, content)
        if not enum_match:
            return None
        enum_class_name = enum_match.group(1)

        # Extract enum body (content between first { and last })
        enum_start = content.find('{', enum_match.start())
        enum_end = content.rfind('}')
        if enum_start == -1 or enum_end == -1:
            return None

        enum_body = content[enum_start + 1:enum_end]

        # Find the end of enum constants (marked by the first semicolon)
        constants_end = enum_body.find(';')
        if constants_end == -1:
            # If no semicolon found, use entire body (unlikely in valid enum)
            constants_section = enum_body
        else:
            # Extract only the constants definition part (before the semicolon)
            constants_section = enum_body[:constants_end]

        # Extract enum constants and their first constructor argument (the ID)
        enum_values = {}

        # Match enum constants with their arguments
        # Match word characters followed by parentheses with content
        constant_pattern = r'(\w+)\s*\(\s*([^,\)]+)'
        for match in re.finditer(constant_pattern, constants_section):
            constant_name = match.group(1)
            id_value = match.group(2).strip()

            # Remove quotes if present
            id_value = id_value.strip('\'"')

            # Only include if it looks like an enum constant (starts with uppercase)
            if constant_name[0].isupper():
                enum_values[constant_name] = id_value

        return enum_class_name, enum_values

    except Exception as e:
        print(f"Error parsing {file_path}: {e}", file=sys.stderr)
        return None



def create_python_types(target_file, classname, enum_values={}):
    """Create the Python file to match types from the Python binding.

    :param target_file: file where to leave the values.
    :param classname: name of the enum
    :param enum_values: values of the enum
    :return: None.
    """
    if DEBUG:
        print(f"- Creating Python {classname} file...")

    module_docstring = ['"""',
                            f"Python binding to runtime {classname} matching.",
                            ""
        ]
    module_docstring = module_docstring + NOTIFICATION
    module_docstring.append('"""')

    # Create parent directories if they don't exist
    os.makedirs(os.path.dirname(target_file), exist_ok=True)

    with open(target_file, "w", encoding="utf-8") as f:
        for module_docstring_line in module_docstring:
            f.write("%s\n" % module_docstring_line)
        f.write("\n\n")
        f.write(f"class Supported{classname}:  # pylint: disable=too-few-public-methods\n")
        f.write(f'    """Python binding to runtime {classname}."""\n\n')
        for val, id in enum_values.items():
            f.write("    %s = %s\n" % (val.replace("_T", ""), id))
        f.write("\n\n")
        f.write(f"{classname} = Supported{classname}()")
        f.write("\n")
    if DEBUG:
        print(f"- Created Python {classname} file")


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Generate semantics header file"
    )
    parser.add_argument(
        "source",
        help="Source path: directory containing input files"
    )

    parser.add_argument(
        "target",
        help="Target File: where generated files will be created"
    )

    args = parser.parse_args()

    print(f"Generating semantics with source: {args.source} and target: {args.target}")

    # Validate arguments
    validate_arguments(args)



    # Process source files and extract semantics
    classname, enum_values = parse_java_enum(args.source)

    # Create data_type file
    create_python_types(args.target, classname, enum_values)


if __name__ == "__main__":
    main()
