#!/bin/bash

  #
  # HELPER FUNCTIONS
  #

  clean() {
    rm -rf "${SCRIPT_DIR}"/build
  }


  #
  # SCRIPT GLOBAL CONSTANTS
  #

  SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"


  #
  # MAIN
  #

  # Retrieve script arguments
  targetDir=$1

  # Add trap for clean
  trap clean EXIT

  # Install
  echo "Installing in ${targetDir}"
  PYCOMPSS_HOME=${targetDir}
  export PYTHONPATH=$PYCOMPSS_HOME:$PYTHONPATH

  CC="g++" python "${SCRIPT_DIR}"/setup.py install --install-lib="${PYCOMPSS_HOME}" -O2
  exitCode=$?
  if [ $exitCode -ne 0 ]; then
    echo "ERROR: Cannot install PyCOMPSs"
    exit $exitCode
  fi
    
  # Normal exit
  exit 0

