#!/bin/bash -e

  action=$1

  if [ "$action" == "configure" ]; then
    # Configure new version successfully installed
    newversion=$1
    echo " - Setting COMPSs Python Binding..."
    chmod 755 -R /opt/COMPSs/Bindings/python
    echo " - COMPSs Python Binding permissions set"
    echo " "

    # echo " - Adding PyCOMPSs to user profile..."  # No need. Symlinks instead.
    # echo "export PYTHONPATH=\$PYTHONPATH:/opt/COMPSs/Bindings/python/" >> /etc/profile.d/compss.sh
    # echo " - PyCOMPSs added to user profile"
    # echo " "

    echo " - Adding PyCOMPSs symlinks to site-packages or dist-packages folder..."
    source /opt/COMPSs/Bindings/python/commons
    if [ -d /opt/COMPSs/Bindings/python/2 ]; then
      create_symbolic_links 2 /opt/COMPSs/Bindings/python/2
    fi
    if [ -d /opt/COMPSs/Bindings/python/3 ]; then
      create_symbolic_links 3 /opt/COMPSs/Bindings/python/3
    fi
    echo " - PyCOMPSs symlinks added to site-packages or dist-packages folder."

    echo " "
    echo "Congratulations!"
    echo " * COMPSs Python Binding $newversion successfully installed!"
    echo " "
  elif [ "$action" == "abort-remove" ]; then
    if [ $# -eq 1 ]; then
      # Generic abort remove
      echo " "
      echo " * Remove aborted."
      echo " "
    else
      # Abort remove in favour to a given package ($2=in-favour)
      package=$3
      newversion=$4
      echo " "
      echo " * Remove aborted in favour to $package - $newversion"
      echo " "
    fi
  elif [ "$action" == "abort-deconfigure" ]; then
    # $2=in-favour
    failedpackage=$3
    failedversion=$4
    echo " "
    echo " * Deconfigure aborted in favour to $failedpackage - $failedversion"
    echo " "
    if [ $# -eq 4 ]; then
      # Without external removals
      failedpackage=$3
      failedversion=$4
    else
      # With removals ($5=removing)
      removedpackage=$6
      removedversion=$7
    fi
  fi
