#!/bin/bash -e
  
  action=$1

  if [ "$action" == "configure" ]; then
    # Configure new version successfully installed
    newversion=$1
    echo " - Setting COMPSs Python Binding..."
    chmod 755 -R /opt/COMPSs/Bindings/python
    echo " - COMPSs Python Binding permissions set"
    echo " "
   
    echo " - Adding PyCOMPSs to user profile..."
    echo "export PYTHONPATH=\$PYTHONPATH:/opt/COMPSs/Bindings/python/" >> /etc/profile.d/compss.sh
    echo " - PyCOMPSs added to user profile"
    echo " "

    echo " "
    echo "Congratulations!"
    echo " * COMPSs Python Binding $newversion successfully installed!"
    echo " "
  elif [ "$action" == "abort-remove" ]; then
    if [ $# -eq 1 ]; then
      # Generic abort remove
      echo " "
      echo " * Remove aborted."
      echo " "
    else 
      # Abort remove in favour to a given package ($2=in-favour)
      package=$3
      newversion=$4
      echo " "
      echo " * Remove aborted in favour to $package - $newversion"
      echo " "
    fi
  elif [ "$action" == "abort-deconfigure" ]; then
    # $2=in-favour
    failedpackage=$3
    failedversion=$4
    echo " "
    echo " * Deconfigure aborted in favour to $failedpackage - $failedversion"
    echo " "
    if [ $# -eq 4 ]; then
      # Without external removals
      failedpackage=$3
      failedversion=$4
    else
      # With removals ($5=removing)
      removedpackage=$6
      removedversion=$7
    fi
  fi

