#!/bin/bash

# Obtain parameters
COMPSs_exec=$1
comm=$2
runcompss_opts=$3
base_app_dir=$4
COMPSs_log_folder=$5
target_log_folder=$6
retry_num=$7
execution_envs=$8

# Global variables
AGENT_PIDS=""
exit_value=0
NUM_RETRIES="50"
jar_name="0.2_1_agent_stop.jar"
app_name="0.2_1_agent_stop"
expectedTime="60s"

# Traps and Handlers
function kill_agents() {
  for pid in ${AGENT_PIDS}; do
    kill -SIGINT ${pid} 1>/dev/null 2>/dev/null
  done
}
trap kill_agents EXIT

#----------------------------------------------------------------------------------
# Generate Project.xml according to system
sed -i '/<InstallDir>/c<InstallDir>'"${COMPSS_HOME}"'<\/InstallDir>' "${base_app_dir}"/project.xml

#----------------------------------------------------------------------------------
# Create all working dir folders
mkdir -p /tmp/COMPSsWorker01/
mkdir -p /tmp/COMPSsWorker02/
mkdir -p /tmp/COMPSsWorker03/
mkdir -p /tmp/COMPSsWorker04/
mkdir -p /tmp/COMPSsWorker05/

#----------------------------------------------------------------------------------
# Run application
echo ""
echo "*** RUNNING AGENTS TEST: 0.2_1 agent stop"
log_dir="${COMPSs_log_folder}/${app_name}_0${retry_num}"
mkdir -p "${log_dir}"
output_log="${log_dir}test.outputlog"
error_log="${log_dir}test.errorlog"
touch "${output_log}"
touch "${error_log}"

# STARTING AGENT TO STOP IT WITH CURL
test1_log_dir="${log_dir}/test1"

compss_agent_start_service \
  --num_agents=1 \
  --agent_name_prefix="COMPSsWorker" \
  --classpath="${base_app_dir}/${jar_name}" \
  --log_dir="${test1_log_dir}" \
  -d \
  ${runcompss_opts} \
  --project="${base_app_dir}/project.xml" \
  --resources="${base_app_dir}/resources.xml"


sleep 1

RESULT=$(grep "test invoked" "${test1_log_dir}/COMPSsWorker01.outputlog")
if [ -z "${RESULT}" ]; then  
  echo "Agent failed to start" > >(tee -a "${error_log}")
  exit 1
fi
echo "Agent started" > >(tee -a "${output_log}")

# STOPING AGENT WITH CURL AND CHECKING IF IT WORKED
curl -XDELETE http://127.0.0.1:46101/COMPSs 1>/dev/null 2>/dev/null
CONFIRMATION=$(grep "Agent was shutdown" "${test1_log_dir}/COMPSsWorker01/agent.log")
retries="${NUM_RETRIES}"
while [ -z "${CONFIRMATION}" ] && [ "${retries}" -gt "0" ]; do
  sleep 1
  CONFIRMATION=$(grep "Agent was shutdown" "${test1_log_dir}/COMPSsWorker01/agent.log")
done
if [ -z "${CONFIRMATION}" ]; then  
  echo "Agent failed to stop with curl" > >(tee -a "${error_log}")
  exit 1
fi
echo  "The agent properly shuts down with curl" > >(tee -a "${output_log}")
AGENT_PIDS=""

# STARTING AGENT TO STOP IT WITH A --stop OPERATION CALL

agent2_log_dir="${log_dir}/test2"

compss_agent_start_service \
  --num_agents=1 \
  --agent_name_prefix="COMPSsWorker" \
  --classpath="${base_app_dir}/${jar_name}" \
  --log_dir=${agent2_log_dir} \
  -d \
  --exec_time=${expectedTime} \
  ${runcompss_opts} \
  --project="${base_app_dir}/project.xml" \
  --resources="${base_app_dir}/resources.xml" \
  es.bsc.compss.test.DemoClass 1

sleep 1
pid_info=""
CONFIRMATION=$(grep "Agent was shutdown" "${test1_log_dir}/COMPSsWorker01/agent.log")
if [ -z "${CONFIRMATION}" ]; then  
  echo "Agent failed to stop with --stop operation" > >(tee -a "${error_log}")
  exit 1
fi
echo  "The agent properly shuts down calling operation with flag --stop" > >(tee -a "${output_log}")
AGENT_PIDS=""


# STARTING MULTIPLE AGENTS TO KILL THEM WITH A --stop OPERATION CALL AND FORWARD_TO
test3_log_dir="${log_dir}/test3"

compss_agent_start_service \
  --num_agents=3 \
  --agent_name_prefix="COMPSsWorker" \
  --classpath="${base_app_dir}/${jar_name}" \
  --log_dir="${test3_log_dir}" \
  -d \
  --exec_time=${expectedTime} \
  ${runcompss_opts} \
  --project="${base_app_dir}/project.xml" \
  --resources="${base_app_dir}/resources.xml" \
  es.bsc.compss.test.DemoClass 1

CONFIRMATION3=$(grep "Agent was shutdown" "${test3_log_dir}/COMPSsWorker01/agent.log")
CONFIRMATION4=$(grep "Agent was shutdown" "${test3_log_dir}/COMPSsWorker02/agent.log")
CONFIRMATION5=$(grep "Agent was shutdown" "${test3_log_dir}/COMPSsWorker03/agent.log")
if [ -z "${CONFIRMATION3}" ] || [ -z "${CONFIRMATION4}" ] || [ -z "${CONFIRMATION5}" ]; then
  echo "Failed to stop agent with flags --stop and --forward_to on compss_agent_call_operation." > >(tee -a "${error_log}")
  exit 1
fi

echo "All Agents were properly shuts down using the flags --stop and --forward_to"

# Copy LOG files
cp -rf "${COMPSs_log_folder}/${app_name}_0${retry_num}"/* "${target_log_folder}"


# STARTING AGENT WITH --stop TO STOP IT WITH A FAILURE IN THE EXECUTION

test4_log_dir="${log_dir}/test4"

compss_agent_start_service \
  --num_agents=1 \
  --agent_name_prefix="COMPSsWorker" \
  --classpath="${base_app_dir}/${jar_name}" \
  --log_dir=${test4_log_dir} \
  -d \
  --exec_time=${expectedTime} \
  ${runcompss_opts} \
  --project="${base_app_dir}/project.xml" \
  --resources="${base_app_dir}/resources.xml" \
  es.bsc.compss.test.DemoClassError 1

sleep 1
CONFIRMATION=$(grep "Agent was shutdown" "${test4_log_dir}/COMPSsWorker01/agent.log")
if [ -z "${CONFIRMATION}" ]; then
  echo "Failed to stop agent with a failure on the execution of compss_agent_call_operation." > >(tee -a "${error_log}")
  exit 1
fi
echo  "The agent properly shuts when an error occurs on the execution" > >(tee -a "${output_log}")
AGENT_PIDS=""

exit_value=0

#----------------------------------------------------------------------------------
# Return execution status
exit ${exit_value}
