#!/bin/bash -e

  #############################################################
  # Name: buildNord3_aux
  # Description: SCRIPT FOR LOCAL COMPSs BUILD in Nord 3
  # Parameters: <targetDir>           Base Target Installation folder
  #
  # ATTENTION: DO NOT EXECUTE THIS FILE. IT IS AUTOMATICALLY
  #            EXECUTED FROM buildMN script
  #############################################################

  usage() {
    echo "Incorrect number of parameters"
    echo " Usage: buildNord3_aux <FullTargetPath>"
    echo " "
    exit 1
  }

  ####################
  # MAIN
  ####################
  # Get parameters
  if [ $# -ne 1 ]; then
    usage
  fi

  # SET SCRIPT VARIABLES
  targetDir=$1
  SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

  # DEFINE MODULES
  modules="intel/2021.4.0 bsc/current oneapi-rt/2021.4.0 impi/2021.4.0 tbb/2021.4.0 mkl/2021.4.0 boost/1.78.0 papi/6.0.0 dlb/git"
  unload_before_python="ignore"
  run_before_py3_modules="ignore"
  py3_modules="python/3.9.10" # "python/3.7.12"  # too old setuptools
  run_before_py3_other_modules="ignore"
  py3_other_modules=""

  # DEFINE CONFIGURATION PARAMETERS
  additionalExports='export JAVA_HOME=/apps/COMPSs/JAVA/jdk-11.0.2 PATH=$JAVA_HOME/bin:$PATH EXTRAE_MPI_LIBS=\${I_MPI_ROOT}/lib/release CFLAGS="-I/usr/include/libxml2/ $CFLAGS"'
  additional_module_use_folder="ignore"
  queues_cfg="nord3.cfg"
  extrae_with_openmpi="false"
  openmpi_version=""
  extrae_with_impi="true"
  impi_version="/2021.4.0"
  autoparallel="false"
  c_binding="true"
  extrae_no_mpi="true"
  r_binding="false"

  # CALL buildSC_aux
  "${SCRIPT_DIR}"/buildSC_aux "${targetDir}" "${modules}" "${unload_before_python}" "${run_before_py3_modules}" "${py3_modules}" "${run_before_py3_other_modules}" "${py3_other_modules}" "${additionalExports}" "${additional_module_use_folder}" "${queues_cfg}" "${extrae_with_openmpi}" "${openmpi_version}" "${extrae_with_impi}" "${impi_version}" "${autoparallel}" "${c_binding}" "${extrae_no_mpi}" "${r_binding}"
  ev=$?

  # End
  if [ $ev -ne 0 ]; then
    echo "ERROR: Exception in auxiliar script"
    exit $ev
  fi
  exit 0
