#!/bin/bash -e
  
  #Obtain parameter
  source_base_dir=$1
  target_base_dir=$2
  
  #Copy files
  cp -f ${source_base_dir}/target/23-concurrent.jar ${target_base_dir}/concurrent.jar   
                  
  cp -f ${source_base_dir}/project.xml ${target_base_dir}/project_concurrent.xml                  
  cp -f ${source_base_dir}/resources.xml ${target_base_dir}/resources_concurrent.xml
  
  cp -f ${source_base_dir}/execution ${target_base_dir}/execution
  cp -f ${source_base_dir}/result_appConcurrent ${target_base_dir}/result_appConcurrent
  cp -f ${source_base_dir}/result_threadConcurrent ${target_base_dir}/result_threadConcurrent

  
