#!/bin/bash -e
  
  #Obtain parameter
  source_base_dir=$1
  target_base_dir=$2
    
  #Copy files
  cp -f ${source_base_dir}/execution ${target_base_dir}/execution
  cp -f ${source_base_dir}/result ${target_base_dir}/result

  cp -f ${source_base_dir}/project.xml ${target_base_dir}/project.xml
  cp -f ${source_base_dir}/resources.xml ${target_base_dir}/resources.xml

  cp -rf ${source_base_dir}/src ${target_base_dir}/src
  cp -f ${source_base_dir}/mo_config.properties ${target_base_dir}/mo_config.properties
  cp -f ${source_base_dir}/matmul_mo_in.profile ${target_base_dir}/matmul_mo_in.profile
  cp -f ${source_base_dir}/Matmul_mo.cc ${target_base_dir}/Matmul_mo.cc
  cp -f ${source_base_dir}/Matmul_mo-functions.cc ${target_base_dir}/Matmul_mo-functions.cc
  cp -f ${source_base_dir}/Matmul_mo.idl ${target_base_dir}/Matmul_mo.idl

  #cp -f ${source_base_dir}/skip ${target_base_dir}/skip
