#!/bin/bash

  #--------------------------------------------------------- 
  # HELPER FUNCTIONS
  #---------------------------------------------------------
  process_lookup() {
    local lookupSrcFile=$1
    local datarh=$2
    local lookupOutFile=$3

    echo "SRC FILE: $lookupSrcFile"
    echo "DATA RH:  $datarh"
    echo "OUT FILE: $lookupOutFile"
  
    # Clean previous binary
    rm -f ${scriptDir}/lookup_aerosol.x
  
    # Compile
    ifort -mcmodel=large \
          -shared-intel \
          -convert big_endian \
          -traceback \
          -assume byterecl \
          -O3 \
          -fp-model precise \
          -fp-stack-check \
          -o ${scriptDir}/lookup_aerosol.x \
          ${lookupSrcFile}
  
    # Clean temp source
    rm -f ${lookupSrcFile}
  
    # Execute
    ${scriptDir}/lookup_aerosol.x ${datarh} > ${lookupOutFile}
    cat ${scriptDir}/fort.7 >> ${lookupOutFile}
    cat ${scriptDir}/fort.8 >> ${lookupOutFile}
  
    # Clean fort files
    rm -f ${scriptDir}/fort.?
  }

  clean() {
    rm -f ${scriptDir}/lookup_aerosol.x
    rm -f ${scriptDir}/LOOKUP_aerosol_ssa_rh??.f
    rm -f ${scriptDir}/fort.?
  }


  #--------------------------------------------------------- 
  # MAIN PROCESS
  #---------------------------------------------------------
  
  # Trap exit to clean tmp files
  trap clean EXIT

  scriptDir=$(dirname $0)
  SRC_FILE=${scriptDir}/LOOKUP_aerosol_ssa-rh.f

  # This script receives a parameter for each lookup_aerosol2.dat.rhXX file
  datarh00=$1
  datarh50=$2
  datarh70=$3
  datarh80=$4
  datarh90=$5
  datarh95=$6
  datarh99=$7

  #--------------------------------------------------------- 
  # lookup_aerosol2.dat.rh00         D2WF=1.0
  tmpSrcFile=${scriptDir}/LOOKUP_aerosol_ssa_rh00.f
  outFile=${scriptDir}/lookup_aerosol.out.rh00
  
  sed -e 's/CCCC/1.0/g' ${SRC_FILE} > ${tmpSrcFile}
  
  process_lookup ${tmpSrcFile} $datarh00 ${outFile}
  
  #---------------------------------------------------------
  # lookup_aerosol2.dat.rh50         D2WF=1.6
  tmpSrcFile=${scriptDir}/LOOKUP_aerosol_ssa_rh50.f
  outFile=${scriptDir}/lookup_aerosol.out.rh50
  
  sed -e 's/CCCC/1.6/g' ${SRC_FILE} > ${tmpSrcFile}
  
  process_lookup ${tmpSrcFile} $datarh50 ${outFile}
  
  #---------------------------------------------------------
  # lookup_aerosol2.dat.rh70         D2WF=1.8
  tmpSrcFile=${scriptDir}/LOOKUP_aerosol_ssa_rh70.f
  outFile=${scriptDir}/lookup_aerosol.out.rh70
  
  sed -e 's/CCCC/1.8/g' ${SRC_FILE} > ${tmpSrcFile}
  
  process_lookup ${tmpSrcFile} $datarh70 ${outFile}
  
  #---------------------------------------------------------
  # lookup_aerosol2.dat.rh80         D2WF=2.0
  tmpSrcFile=${scriptDir}/LOOKUP_aerosol_ssa_rh80.f
  outFile=${scriptDir}/lookup_aerosol.out.rh80
  
  sed -e 's/CCCC/2.0/g' ${SRC_FILE} > ${tmpSrcFile}
  
  process_lookup ${tmpSrcFile} $datarh80 ${outFile}
  
  #---------------------------------------------------------
  # lookup_aerosol2.dat.rh90         D2WF=2.4
  tmpSrcFile=${scriptDir}/LOOKUP_aerosol_ssa_rh90.f
  outFile=${scriptDir}/lookup_aerosol.out.rh90
  
  sed -e 's/CCCC/2.4/g' ${SRC_FILE} > ${tmpSrcFile}
  
  process_lookup ${tmpSrcFile} $datarh90 ${outFile}
  
  #---------------------------------------------------------
  # lookup_aerosol2.dat.rh95         D2WF=2.9
  tmpSrcFile=${scriptDir}/LOOKUP_aerosol_ssa_rh95.f
  outFile=${scriptDir}/lookup_aerosol.out.rh95
  
  sed -e 's/CCCC/2.9/g' ${SRC_FILE} > ${tmpSrcFile}
  
  process_lookup ${tmpSrcFile} $datarh95 ${outFile}
  
  #---------------------------------------------------------
  # lookup_aerosol2.dat.rh99         D2WF=4.8
  tmpSrcFile=${scriptDir}/LOOKUP_aerosol_ssa_rh99.f
  outFile=${scriptDir}/lookup_aerosol.out.rh99
  
  sed -e 's/CCCC/4.8/g' ${SRC_FILE} > ${tmpSrcFile}
  
  process_lookup ${tmpSrcFile} $datarh99 ${outFile}
  
  #---------------------------------------------------------
  # END
  exit

