#!/bin/bash

  #Obtain parameters
  COMPSs_exec=$1
  comm=$2
  runcompss_opts=$3
  base_app_dir=$4
  COMPSs_log_folder=$5
  target_log_folder=$6
  retryNum=$7
  
  #Global exit variable
  exitValue=0
  
  #----------------------------------------------------------------------------------
  #Generate Project.xml according to system
  sed -i '/<InstallDir>/c<InstallDir>'${IT_HOME}'<\/InstallDir>' ${base_app_dir}/project.xml
  
  #----------------------------------------------------------------------------------
  # Create all working dir folders
  mkdir -p /tmp/COMPSsWorker01/
  
  #----------------------------------------------------------------------------------
  # Run application 39 - barrierTest
  echo
  echo "*** RUNNING PYTHON APPLICATION PYTHON BARRIER"
  output_log="${target_log_folder}/barrier_python_0${retryNum}.outputlog"
  error_log="${target_log_folder}/barrier_python_0${retryNum}.errorlog"
  expectedTime=80s
  
  timeout --signal=2 $expectedTime ${COMPSs_exec} \
     --project=${base_app_dir}/project.xml \
     --resources=${base_app_dir}/resources.xml \
     --debug \
     --lang=python \
     --comm=$comm \
     --pythonpath=${base_app_dir}/src/ \
     ${runcompss_opts} \
     ${base_app_dir}/src/barrierTest.py > >(tee ${output_log}) 2> >(tee ${error_log} >&2)
  
  
  #Check timeout
  if [[ "$?" = "124" ]]; then
     #Copy LOG files
     cp -rf ${COMPSs_log_folder}/barrierTest.py_0${retryNum}/* ${target_log_folder}
     
     #Report time out
     echo "[WARNING] Python Application timed out" >> ${output_log}
     exitValue=124
  else
     #Copy LOG files
     cp -rf ${COMPSs_log_folder}/barrierTest.py_0${retryNum}/* ${target_log_folder}
  
     #Check result
     ${base_app_dir}/result ${output_log} ${error_log} ${target_log_folder} ${comm}
     exitValue=$?
  fi
  
  
  #----------------------------------------------------------------------------------
  # Return execution status
  exit $exitValue

