#!/bin/bash

  # Obtain parameters
  COMPSs_exec=$1
  comm=$2
  runcompss_opts=$3
  base_app_dir=$4
  target_log_folder=$5
  compss_module=$6
  queue=$7
  qos=$8
  project_name=$9
  #Execution_envs should be the last parameter because it is a list
  execution_envs=${10}
  if [ "$queue" != 'none' ]; then
    runcompss_opts="${runcompss_opts} --queue=${queue}"
  fi
  if [ "$qos" != 'none' ]; then
    runcompss_opts="${runcompss_opts} --qos=${qos}"
  fi
  if [ "$project_name" != 'none' ]; then
    runcompss_opts="${runcompss_opts} --project_name=${project_name}"
  fi


  # Global variables
  app_name="decorator_container_mpi.py"

  #----------------------------------------------------------------------------------
  # Load COMPSs module + application
  export COMPSS_PYTHON_VERSION=3.12.1
  module load ${compss_module}

  # module load xxx
  export COMPSS_MPIRUN_TYPE="openmpi"
  export MDCU=112
  module load singularity/3.11.5

  #----------------------------------------------------------------------------------
  # Run application
  echo
  echo "*** RUNNING DECORATOR CONTAINER-MPI PYTHON TESTS"
  #----------------------------------------------------------------------------------
  # Run application
  echo

  echo "*** RUNNING OPENMPI"
  module unload impi
  module load openmpi/4.1.5
  export COMPSS_MPIRUN_TYPE="openmpi"

#  for exec_env in ${execution_envs}; do
    echo "- Running with Environment: ${exec_env}"
    output_log="${target_log_folder}/${app_name}_${exec_env}.outputlog"
    error_log="${target_log_folder}/${app_name}_${exec_env}.errorlog"
    specific_log_dir="${target_log_folder}/${app_name}_${exec_env}"
    mkdir -p "${specific_log_dir}"

    master_working_dir=${target_log_folder}
#    if [ "$exec_env" == 'shared_disk' ]; then
#        worker_working_dir=${specific_log_dir}
#    fi
#    if [ "$exec_env" == 'local_disk' ]; then
        worker_working_dir="local_disk"
#    fi

    expectedTime=5
    # shellcheck disable=SC2086
    "${COMPSs_exec}" --exec_time=${expectedTime} \
      --num_nodes=1 \
      --worker_in_master_cpus=${MDCU} \
      --comm="$comm" \
      --job_execution_dir=${master_working_dir} \
      --worker_working_dir=${worker_working_dir} \
      --log_dir=${target_log_folder} \
      --debug \
      --summary \
      ${runcompss_opts} \
      --lang=python \
      --pythonpath="${base_app_dir}" \
      \
      "${base_app_dir}/src/${app_name}" > >(tee "${output_log}") 2> >(tee "${error_log}" >&2)

#  done
