#!/bin/bash -e
  
  # Obtain parameter
  source_base_dir=$1
  target_base_dir=$2
  
  # Compile C sub-programs
  mkdir "${target_base_dir}"/bin/
  in_out_err_binary="${target_base_dir}/bin/testIN_OUT_ERR"
  out_err_binary="${target_base_dir}/bin/testOUT_ERR"
  g++ -o "${in_out_err_binary}" "${source_base_dir}"/src/main/c/testIN_OUT_ERR.cc
  g++ -o "${out_err_binary}" "${source_base_dir}"/src/main/c/testOUT_ERR.cc
  
  # Copy files
  cp -f "${source_base_dir}"/target/37-nonNativeTasks.jar "${target_base_dir}"/nonNativeTasks.jar   
                  
  cp -f "${source_base_dir}"/project.xml "${target_base_dir}"/project.xml                  
  cp -f "${source_base_dir}"/resources.xml "${target_base_dir}"/resources.xml
  
  cp -f "${source_base_dir}"/execution "${target_base_dir}"/execution
  cp -f "${source_base_dir}"/result "${target_base_dir}"/result
  
