#!/bin/bash -e
  
  # Obtain parameter
  source_base_dir=$1
  target_base_dir=$2
  
  # Compile C sub-program with MPI
  mkdir ${target_base_dir}/bin/
  gcc -o ${target_base_dir}/bin/helloWorldBINARY ${source_base_dir}/src/main/c/helloWorldBINARY.c
  gcc -o ${target_base_dir}/bin/helloWorldOMPSS ${source_base_dir}/src/main/c/helloWorldOMPSS.c
  mpicc -o ${target_base_dir}/bin/helloWorldMPI ${source_base_dir}/src/main/c/helloWorldMPI.c
  
  # Copy files
  cp -f ${source_base_dir}/target/37-nonNativeTasks.jar ${target_base_dir}/nonNativeTasks.jar   
                  
  cp -f ${source_base_dir}/project.xml ${target_base_dir}/project.xml                  
  cp -f ${source_base_dir}/resources.xml ${target_base_dir}/resources.xml
  
  cp -f ${source_base_dir}/execution ${target_base_dir}/execution
  cp -f ${source_base_dir}/result ${target_base_dir}/result
  
