#!/bin/bash

  #Obtain parameters
  COMPSs_exec=$1
  comm=$2
  base_app_dir=$3
  COMPSs_log_folder=$4
  target_log_folder=$5
  retryNum=$6
  
  #Global exit variable
  exitValue=0
  
  #----------------------------------------------------------------------------------
  #Generate Project.xml according to system
  sed -i '/<InstallDir>/c<InstallDir>'${IT_HOME}'<\/InstallDir>' ${base_app_dir}/project.xml
  
  #----------------------------------------------------------------------------------
  #Create all working dir folders
  mkdir -p /tmp/COMPSsWorker01/
  
  #----------------------------------------------------------------------------------
  # Binaries paths
  in_out_err_binary="${base_app_dir}/bin/testIN_OUT_ERR"
  out_err_binary="${base_app_dir}/bin/testOUT_ERR"
  export IN_OUT_ERR_BINARY=${in_out_err_binary}
  export OUT_ERR_BINARY=${out_err_binary}
  
  #----------------------------------------------------------------------------------
  # Run application 37 - Non Native Tasks
  echo
  echo "*** RUNNING JAVA APPLICATION NON NATIVE TASK"
  
  echo "IN OUT ERR Binary: ${IN_OUT_ERR_BINARY}"
  echo "OUT ERR Binary: ${OUT_ERR_BINARY}"
  
  output_log="${target_log_folder}/nonNativeTasks_0${retryNum}.outputlog"
  error_log="${target_log_folder}/nonNativeTasks_0${retryNum}.errorlog"
  expectedTime=60s
  
  timeout --signal=2 $expectedTime ${COMPSs_exec} \
     --project=${base_app_dir}/project.xml \
     --resources=${base_app_dir}/resources.xml \
     --debug \
     --lang=java \
     --comm=$comm \
     --classpath=${base_app_dir}/nonNativeTasks.jar \
     nonNativeTasks.Main > >(tee ${output_log}) 2> >(tee ${error_log} >&2)
  
  
  #Check timeout
  if [[ "$?" = "124" ]]; then
     #Copy LOG files
     cp -rf ${COMPSs_log_folder}/nonNativeTasks.Main_0${retryNum}/* ${target_log_folder}
     
     #Report time out
     echo "[WARNING] Java Application timed out" >> ${output_log}
     exitValue=124
  else
     #Copy LOG files
     cp -rf ${COMPSs_log_folder}/nonNativeTasks.Main_0${retryNum}/* ${target_log_folder}
  
     #Check result
     ${base_app_dir}/result ${output_log} ${target_log_folder}
     exitValue=$?
  fi
  
  
  #----------------------------------------------------------------------------------
  #Return execution status
  exit $exitValue
