#!/bin/bash

set -e

export PATH=$PATH:/usr/bin:

working_dir=`pwd`

function exittrap {
        rc=$?      
        if test x"$rc" != x"0" ; then
                echo "ERROR: Command exited with status" $rc"." 1>&2
                exit $rc                                            
        fi                                                          
}                                                                   

trap exittrap 0


# message functions
usage() {

        echo " "
        echo  Usage\: `basename $0` build \<component\> \<appname\>
        echo  Usage\: `basename $0` copy   \<component\> \<appname\>
        echo  Usage\: `basename $0` clean \<component\> \<appname\>
        echo ""
        echo "  Available actions:"
        echo "    copy         Setup a compilation environment for the component for customization."
        echo "    build        Build the selected component ."
        echo "    clean        Remove generated binaries."
        echo ""
        echo "  Available components:"
        echo "    master       Build or copy the master part."
        echo "    worker       Build or copy the worker part."
        echo "    all          Build or copy the master and workers parts."
        echo ""
        echo "  <appname> Corresponds to the name of the application used for source files and IDL files."
        echo " "
        exit
}


error() {
        echo "An error occurred, please check the output."
        exit 1;                                           
}                                                   

# Generating autogen.sh script

generate_autogen_sh() {

/bin/cat > autogen.sh << EOF

#!/bin/bash
set -e

/usr/bin/aclocal
/usr/bin/automake -a -c
/usr/bin/autoconf
./configure --host=$TARGET_HOST --with-cs-prefix=$CS_HOME

EOF
/bin/chmod +x autogen.sh
}

# master functions

prepare_master_copy() {
        gsprefix=$1    
        appname=$2     

        if test -d master ; then      
                cd master             
           if test -e $2.cc ; then    
                                      
             if test -e $2.idl ; then 
                echo "All files needed found."
                                              
             else                             
                echo "File $2.idl not found." 
                exit                          
             fi                               

           else
             echo "File $2.cc not found."
             exit                        
           fi                            

        else
                echo "The master directory must exist when using copy action."
                exit                                                          
        fi                                                                    
}                                                                             

prepare_master_build() {
        gsprefix=$1     
        appname=$2      

        if test -d master ; then
                echo "The master directory already exists from a previous build. Removing."
                /bin/rm -rf master                                                         
        fi                                                                                 

        /bin/mkdir master
        /bin/cp *.* master
        cd master 
		/bin/rm $2-functions.cc                                                                                                

        /bin/mkdir gsbuild
        cd gsbuild        

        ln -s -f ../*.c .
        ln -s -f ../*.cc .
        ln -s -f ../*.cpp .
        ln -s -f ../*.cxx .
        ln -s -f ../*.idl .
        ln -s -f ../*.h .  
}                                                  

copy_master_build_env() {
        gsprefix=$1      
        appname=$2       

        /bin/cp /opt/COMPSs//Bindings/c/share/c_build/master/Makefile.am Makefile.am.source
        /bin/cat /opt/COMPSs//Bindings/c/share/c_build/master/configure.in | /bin/sed -e s/PACKAGE/"$appname"/g > configure.in                                                                                             
        /bin/cat Makefile.am.source | /bin/sed 's/PACKAGE/'$appname'/g' > Makefile.am
                                                                            
        generate_autogen_sh                                                                                                                                
        /usr/bin/touch NEWS README AUTHORS ChangeLog                                                                                                                
        echo "" > empty.cc                                                                                                                                   
}                                                                                                                     

build_master() {
        gsprefix=$1
        appname=$2
        ./autogen.sh      
        /usr/bin/make                
}                   

finish_master_build() {
	gsprefix=$1    
        appname=$2     
        /bin/cp -f $appname ..
        cd ..            
        cd ..          
}                                  

clean_master() {         
        if test -d master ; then
           cd master            
           /bin/rm -f $appname
           cd ..                                                   
        else                                                       
           echo "The master directory must exist when using clean action."
           exit                                                           
        fi                           
}                                                                    


# worker functions
prepare_worker_copy() {
        gsprefix=$1    
        appname=$2     

        if test -d worker ; then
                cd worker       
           if test -e $2-functions.cc ; then
                                           
             if test -e $2.idl ; then      
                echo "All files needed found."

             else
                echo "File $2.idl not found."
                exit                         
             fi                              

           else
             echo "File $2-functions.cc not found."
             exit                                 
           fi                                     

        else
                echo "The worker directory must exist when using copy action."
                exit                                                          
        fi                                                                    
}                                                   

prepare_worker_build() {
	gsprefix=$1     
        appname=$2      


        if test -d worker ; then
                echo "The worker directory already exists from a previous build. Removing."
                /bin/rm -rf worker                                                         
        fi                                                                                 

        /bin/mkdir worker
        /bin/cp *.* worker
        /bin/cp ./src/* worker
        cd worker
		/bin/rm $2.cc
                                                                              
        /bin/mkdir gsbuild
        cd gsbuild        

        ln -s -f ../*.c .
        ln -s -f ../*.cc .
        ln -s -f ../*.cpp .
        ln -s -f ../*.cxx .
        ln -s -f ../*.idl .
        ln -s -f ../*.h .    
}                                           

copy_worker_build_env() {
        gsprefix=$1      
        appname=$2       

        /bin/cp /opt/COMPSs//Bindings/c/share/c_build/worker/Makefile.am Makefile.am.source
        /bin/cat /opt/COMPSs//Bindings/c/share/c_build/worker/configure.in | /bin/sed -e s/PACKAGE/"$appname"/g  > configure.in                                                                                                                                               
        /bin/cat Makefile.am.source | /bin/sed 's/PACKAGE/'$appname'/g' > Makefile.am                             
        /bin/cp /opt/COMPSs//Bindings/c/share/c_build/worker/files/* .
        generate_autogen_sh                                                                                                                                
        /usr/bin/touch NEWS README AUTHORS ChangeLog                                                                                                                

}                                           

build_worker() {
        gsprefix=$1
        appname=$2 
        echo "Running Autogen... "
        ./autogen.sh              
        /usr/bin/make                
}                   

finish_worker_build() {
        gsprefix=$1    
        appname=$2     
        /bin/cp -f worker_c ..
        #/bin/cp -f persistent_worker_c ..
        /bin/cp -f nio_worker_c ..
        cd ..

        cd ..
}                                           

clean_worker() {
 
        if test -d worker ; then
           cd worker            
           /bin/rm -f worker_c persistent_worker_c clean.sh 
           cd ..                                                      
        else                                                          
           echo "The worker directory must exist when using clean action."
           exit                                                           
        fi                                   
}    
                                                          
# main code
if test $# != 3 ; then
   if test $# != 5; then
        usage           
   fi                   
fi                        

action=$1
component=$2
appname=$3

if test x"$CS_HOME" != x ; then
        echo "Using environment variable CS_HOME."
        gsprefix=$CS_HOME                         
else                                                  
        gsprefix=/opt/COMPSs//Bindings/c                             
fi                                                    


case $action in
        copy)  
                case $component in
                        master)   
                                echo "Preparing master build environment..."
                                prepare_master_copy $gsprefix $appname      
                                copy_master_build_env $gsprefix $appname    
                                ;;                                          
                        worker)                                             
                                echo "Preparing worker build environment..."
                                prepare_worker_copy $gsprefix $appname      
                                copy_worker_build_env $gsprefix $appname    
                                ;;                                          
                        all)                                                
                                echo "Preparing master and worker build environment:"
                                echo " "                                             

                                echo "Preparing master build environment..."
                                prepare_master_copy $gsprefix $appname      
                                copy_master_build_env $gsprefix $appname    
                                cd ..                                       

                                echo " "
                                echo "Preparing worker build environment..."
                                prepare_worker_copy $gsprefix $appname      
                                copy_worker_build_env $gsprefix $appname    
                                ;;                                    
                        *)                                            
                                usage                                 
                                ;;                                    
                esac                                                  
                ;;                                                   
        build)                                                        
                case $component in                                    
                        master)                                       
                                echo "Building master"                
                                prepare_master_build $gsprefix $appname
                                copy_master_build_env $gsprefix $appname
                                build_master $gsprefix $appname
                                finish_master_build $gsprefix $appname                                 
                                ;;                                                                     
                        worker)                                                                        
                                echo "Building worker"                                                 
                                prepare_worker_build $gsprefix $appname                                
                                copy_worker_build_env $gsprefix $appname                               
                                build_worker $gsprefix $appname
                                finish_worker_build $gsprefix $appname
                                ;;
                        all)
                                echo "Building all:"
                                echo " "
                                echo "Building Master..."

                                prepare_master_build $gsprefix $appname
                                copy_master_build_env $gsprefix $appname
                                build_master $gsprefix $appname
                                finish_master_build $gsprefix $appname

                                echo " "
                                echo "Building Worker..."

                                prepare_worker_build $gsprefix $appname
                                copy_worker_build_env $gsprefix $appname
                                build_worker $gsprefix $appname
                                finish_worker_build $gsprefix $appname
                                ;;
                        *)
                                usage
                                ;;
                esac
                ;;
        clean)
                case $component in
                        master)
                                echo "Cleaning master"
                                clean_master
                                ;;
                        worker)
                                echo "Cleaning worker"
                                clean_worker
                                ;;
                        all)
                                echo "Cleaning master and worker"
                                clean_master
                                clean_worker
                                ;;
                        *)
                                usage
                                ;;
                esac
                ;;
        *)
                usage
                ;;
esac

echo "Command succesful."

