#!/bin/bash

  # Obtain parameters
  COMPSs_exec=$1
  comm=$2
  runcompss_opts=$3
  base_app_dir=$4
  COMPSs_log_folder=$5
  target_log_folder=$6
  retry_num=$7
  execution_envs=$8
  
  # Global variables
  AGENT_PIDS=""
  exit_value=0
  NUM_RETRIES="50"
  jar_name="5.0_4_agent_nested.jar"
  app_name="5.0_4_agent_nested"
  expected_time="60s"

  # Traps and Handlers
  function kill_agents() {
    for pid in ${AGENT_PIDS}; do
      kill -SIGINT ${pid}
    done
  }
  trap kill_agents EXIT

  function validate_parallel_running_tasks() {
    starts="${1}"
    ends="${2}"
    min_parallel_tasks=${3}
    limit_parallel_tasks=${4}
    
    already_started=0
    max_parallel_tasks=0
    for start in ${starts}; do
      already_started=$((already_started + 1))
      already_ended="0";
      for end in ${ends}; do
        if [ "${end}" -le "${start}" ]; then
          already_ended=$((already_ended + 1))
        fi
      done
      running_tasks=$((already_started - already_ended))
      if [ "${running_tasks}" -gt "${max_parallel_tasks}" ]; then
        max_parallel_tasks=${running_tasks}
      fi
    done
    if [ ${max_parallel_tasks} -lt "${min_parallel_tasks}" ]; then
      echo "Simultaneous tasks not properly managed. Found ${max_parallel_tasks} running in parallel and at least ${min_parallel_tasks} expected."  > >(tee -a "${error_log}")
      exit 1
    fi
    if [ ${max_parallel_tasks} -gt "${limit_parallel_tasks}" ]; then
      echo "Simultaneous tasks not properly managed. Found ${max_parallel_tasks} running in parallel and only ${limit_parallel_tasks} expected."  > >(tee -a "${error_log}")
      exit 1
    fi
  }


  #----------------------------------------------------------------------------------
  # Generate Project.xml according to system
  sed -i '/<InstallDir>/c<InstallDir>'"${COMPSS_HOME}"'<\/InstallDir>' "${base_app_dir}"/project.xml
  
  #----------------------------------------------------------------------------------
  # Create all working dir folders
  mkdir -p /tmp/COMPSsWorker01/
  
  #----------------------------------------------------------------------------------
  # Run application
  echo ""
  echo "*** RUNNING AGENTS TEST: nested compss with multiple agents"
  log_dir="${COMPSs_log_folder}/${app_name}_0${retry_num}/"
  mkdir -p "${log_dir}"
  output_log="${log_dir}test.outputlog"
  error_log="${log_dir}test.errorlog"
  touch "${output_log}"
  touch "${error_log}"
  
  compss_agent_start_service \
    --num_agents=4 \
    --agent_name_prefix="COMPSsWorker" \
    --classpath="${base_app_dir}/${jar_name}" \
    --log_dir=${log_dir} \
    -d \
    --exec_time=${expectedTime} \
    ${runcompss_opts} \
    --reuse_resources_on_block=false \
    --project="${base_app_dir}/project.xml" \
    --resources="${base_app_dir}/resources.xml" \
    --topology=chain \
    --cei="recursive.CountItf" \
    "recursive.Count" 3

  agent1_log_dir="${log_dir}/COMPSsWorker01/"
  agent2_log_dir="${log_dir}/COMPSsWorker02/"
  agent3_log_dir="${log_dir}/COMPSsWorker03/"
  agent4_log_dir="${log_dir}/COMPSsWorker04/"

  created_jobs=$(ls "${agent1_log_dir}jobs" | grep -c NEW.out)
  if [ ! "${created_jobs}" == "1" ]; then
    echo "Agent1 has executed ${created_jobs} tasks and only 1 expected." > >(tee -a "${error_log}")
    exit 1
  fi 
  created_jobs=$(ls "${agent2_log_dir}jobs" | grep -c NEW.out)
  if [ ! "${created_jobs}" == "1" ]; then
    echo "Agent2 has executed ${created_jobs} tasks and only 1 expected." > >(tee -a "${error_log}")
    exit 1
  fi 
  created_jobs=$(ls "${agent3_log_dir}jobs" | grep -c NEW.out)
  if [ ! "${created_jobs}" == "1" ]; then
    echo "Agent3 has executed ${created_jobs} tasks and only 1 expected." > >(tee -a "${error_log}")
    exit 1
  fi 
  created_jobs=$(ls "${agent4_log_dir}jobs" | grep -c NEW.out)
  if [ ! "${created_jobs}" == "1" ]; then
    echo "Agent4 has executed ${created_jobs} tasks and only 1 expected." > >(tee -a "${error_log}")
    exit 1
  fi 
    

  job2_method=$( grep "\"method_name\"" "${agent2_log_dir}/jobs/job1_NEW.out" | cut -c 24- | jq -r '.method_name')
  job3_method=$( grep "\"method_name\"" "${agent3_log_dir}/jobs/job1_NEW.out" | cut -c 24- | jq -r '.method_name')
  job4_method=$( grep "\"method_name\"" "${agent4_log_dir}/jobs/job1_NEW.out" | cut -c 24- | jq -r '.method_name')
  
  job2_value=$( grep -v "\[" "${agent2_log_dir}/jobs/job1_NEW.out" | tail -n 1)
  job3_value=$( grep -v "\[" "${agent3_log_dir}/jobs/job1_NEW.out" | tail -n 1)
  job4_value=$( grep -v "\[" "${agent4_log_dir}/jobs/job1_NEW.out" | tail -n 1)
  if [ ! "${job2_method}" == "count" ]; then
    echo "Unexpected method (${job2_method}) for job 2." > >(tee -a "${error_log}")
    exit 1
  fi
  if [ ! "${job2_value}" == "3" ]; then
    echo "Unexpected value (${job2_value}) for job 2." > >(tee -a "${error_log}")
    exit 1
  fi
  if [ ! "${job3_method}" == "count" ]; then
    echo "Unexpected method (${job3_method}) for job 3." > >(tee -a "${error_log}")
    exit 1
  fi
  if [ ! "${job3_value}" == "2" ]; then
    echo "Unexpected value (${job3_value}) for job 3." > >(tee -a "${error_log}")
    exit 1
  fi
  if [ ! "${job4_method}" == "count" ]; then
    echo "Unexpected method (${job4_method}) for job 4." > >(tee -a "${error_log}")
    exit 1
  fi
  if [ ! "${job4_value}" == "1" ]; then
    echo "Unexpected value (${job4_value}) for job 4." > >(tee -a "${error_log}")
    exit 1
  fi
  echo "All task executed as expected and with the expected values." 

  # Copy LOG files
  cp -rf "${COMPSs_log_folder}/${app_name}_0${retry_num}"/* "${target_log_folder}"
  exit_value=0

  #----------------------------------------------------------------------------------
  # Return execution status
  exit ${exit_value}
