#!/bin/bash -e

  # Obtain parameters
  source_base_dir=$1
  target_base_dir=$2

  # Copy dummy Storage jar
  (
  cd "${source_base_dir}"/../../../../utils/storage/redisPSCO/
  mvn clean package
  )
  mkdir -p "${target_base_dir}"/jars/
  cp "${source_base_dir}"/../../../../utils/storage/redisPSCO/target/compss-redisPSCO.jar "${target_base_dir}"/jars/compss-redisPSCO.jar

  # Copy files
  cp "${source_base_dir}"/target/70-pscosRedis.jar "${target_base_dir}"/pscosRedis.jar

  # Now we download Redis source code from their official repo, compile it and use the redis-server executable
  cp "${source_base_dir}"/target/lib/jedis*.jar "${target_base_dir}"/jedis.jar
  cp "${source_base_dir}"/REDIS-VERSION "${target_base_dir}"/REDIS-VERSION

  cp "${source_base_dir}"/project.xml "${target_base_dir}"/project.xml
  cp "${source_base_dir}"/resources.xml "${target_base_dir}"/resources.xml

  cp "${source_base_dir}"/execution "${target_base_dir}"/execution
  cp "${source_base_dir}"/result_internal "${target_base_dir}"/result_internal
