#!/bin/bash

  # Obtain parameters
  COMPSs_exec=$1
  comm=$2
  runcompss_opts=$3
  base_app_dir=$4
  COMPSs_log_folder=$5
  target_log_folder=$6
  retryNum=$7

  # Global exit variable
  exitValue=0

  #----------------------------------------------------------------------------------
  # Generate Project.xml according to system
  sed -i '/<InstallDir>/c<InstallDir>'${COMPSS_HOME}'<\/InstallDir>' ${base_app_dir}/project.xml

  #----------------------------------------------------------------------------------
  # Create all working dir folders
  mkdir -p /tmp/COMPSsWorker01/

  #----------------------------------------------------------------------------------
  # Create storage Conf
  storageConf=${target_log_folder}/storage.conf
  cat > $storageConf << EOF
COMPSsWorker01
EOF

  # Add trap to kill redis instance/s
  clean() {
    pkill redis
  }
  trap clean EXIT

  #----------------------------------------------------------------------------------
  # Set Storage implementation location
  storageImplPath=${base_app_dir}/jars/compss-redisPSCO.jar

  # Download the specified Redis Version, unzip it, compile the redis-server
  # utility, move it to the main folder and execute the main test
  REDIS_VERSION=$(cat REDIS-VERSION)
  REDIS_URL=http://download.redis.io/releases
  REDIS_FOLDER=redis-${REDIS_VERSION}
  REDIS_TAR_NAME=${REDIS_FOLDER}.tar.gz
  # Download Redis
  wget ${REDIS_URL}/${REDIS_TAR_NAME}
  # Uncompress it
  tar -xzvf ${REDIS_TAR_NAME}
  rm ${REDIS_TAR_NAME}
  # Go to the Redis directory and compile the redis-server utility
  cd ${REDIS_FOLDER}
  make redis-server
  cd ..
  # Move the redis-server executable to the main folder
  cp ${REDIS_FOLDER}/src/redis-server redis-server
  rm -rf ${REDIS_FOLDER}

  # Set a single standalone Redis instance
  ./redis-server --daemonize yes

  #----------------------------------------------------------------------------------
  # Run application 1 - Java PSCOs internalExecution
  echo
  echo "*** RUNNING JAVA APPLICATION PSCOs internalExecution"
  log_folder="${target_log_folder}/internalExecution"
  mkdir -p ${log_folder}
  output_log="${log_folder}/testPSCO_internalExecution_0${retryNum}.outputlog"
  error_log="${log_folder}/testPSCO_internalExecution_0${retryNum}.errorlog"
  expectedTime=60s

  timeout --signal=2 $expectedTime ${COMPSs_exec} \
     --project=${base_app_dir}/project.xml \
     --resources=${base_app_dir}/resources.xml \
     --debug \
     --lang=java \
     --comm=$comm \
     --storage_conf=${storageConf} \
     --jvm_workers_opts="-Dcompss.worker.removeWD=true" \
     ${runcompss_opts} \
     --classpath=${base_app_dir}/pscosRedis.jar:${storageImplPath}:${base_app_dir}/jedis.jar \
     testPSCOInternal.Internal > >(tee ${output_log}) 2> >(tee ${error_log} >&2)


  #Check timeout
  if [[ "$?" = "124" ]]; then
     #Copy LOG files
     cp -rf ${COMPSs_log_folder}/testPSCOInternal.Internal_0${retryNum}/* ${log_folder}

     #Report time out
     echo "[WARNING] Java Application timed out" >> ${output_log}
     ev1=124
  else
     #Copy LOG files
     cp -rf ${COMPSs_log_folder}/testPSCOInternal.Internal_0${retryNum}/* ${log_folder}

     #Check result
     ${base_app_dir}/result_internal ${output_log} ${log_folder}
     ev1=$?
  fi

  #----------------------------------------------------------------------------------
  # Sleep between applications
  sleep 2s

  #----------------------------------------------------------------------------------
  #Create all working dir folders
  mkdir -p /tmp/COMPSsWorker01/

  #----------------------------------------------------------------------------------
  #Return execution status
  if [ $ev1 -ne 0 ]; then
     exitValue=$ev1
  else
     exitValue=$ev2
  fi
  exit $exitValue
