#!/bin/bash

#$1 the keyword to search in the grep

n_occurences=1 #arbitrary
#limit=5

while [ $n_occurences -ne 0 ]
do
	n_occurences=$(ps -ef 2> /dev/null | grep -c $1)
	sleep 1
done

# If has arrived here means that $n_occurences <= $limit so there's no alive
# java/python process otherwise has been timedout so the exit code is different
# than 0

exit 0
