<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <!-- GENERAL INFORMATION -->
    <artifactId>wdc-tracing-extrae</artifactId>
    <packaging>jar</packaging>
    <parent>
        <groupId>es.bsc.compss</groupId>
        <artifactId>wdc-tracing</artifactId>
        <version>3.4.rc1</version>
    </parent>

    <!-- PROJECT INFORMATION -->
    <name>WDC Extrae Tracing backend</name>
    <description>Tracing back-end using extrae</description>
    <url>http://www.bsc.es</url>
    <inceptionYear>2025</inceptionYear>
    <licenses>
        <license>
            <name>Apache License, Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.html</url>
        </license>
    </licenses>
    <organization>
        <name>BSC</name>
        <url>http://www.bsc.es</url>
    </organization>

    <!-- DEPENDENCIES -->
    <dependencies>
        <!-- Tracing API -->
        <dependency>
            <groupId>es.bsc.compss</groupId>
            <artifactId>wdc-tracing-api</artifactId>
            <version>${project.version}</version>
        </dependency>
		<!-- Extrae -->
		<dependency>
			<groupId>es.bsc.cepbatools</groupId>
			<artifactId>extrae</artifactId>
		</dependency>
        <!-- Log4j -->
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-core</artifactId>
		</dependency>
    </dependencies>

    <!-- BUILD -->
    <build>
        <finalName>${project.artifactId}</finalName>
        <plugins>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven-compiler-plugin.version}</version>
            </plugin>
        </plugins>
    </build>
</project>