#!/bin/bash -e

  action=$1

  if [ "$action" == "install" ]; then
    if [ $# -eq 2 ]; then
      # Installation knowing previous old version
      oldversion=$2
      echo " "
      echo " * Installing COMPSs PLUTO from previous version ${oldversion}..."
      echo " "
      rm -rf /opt/COMPSs/Dependencies/pluto
    else
      # Clean installation
      echo " "
      echo " * Installing COMPSs PLUTO..."
      echo " "
    fi
  elif [ "$action" == "upgrade" ]; then
    # Upgrade from previous version
    oldversion=$2
    echo " "
    echo " * Upgrading COMPSs PLUTO from previous version ${oldversion}..."
    echo " "
    if [ -d "/opt/COMPSs/Dependencies/pluto" ]; then
      mv /opt/COMPSs/Dependencies/pluto /tmp/COMPSs_pluto.bkp
    fi
  elif [ "$action" == "abort-upgrade" ]; then
    # Update failed, recover previous version
    newversion=$2
    echo " "
    echo " * COMPSs PLUTO $newversion upgrade aborted. Please check errors above."
    echo " "
    if [ -d "/tmp/COMPSs_pluto.bkp" ]; then
      mv /tmp/COMPSs_pluto.bkp /opt/COMPSs/Dependencies/pluto
    fi
  fi

