#!/bin/bash -e

  distribution=$1
  arch=$2
  COMPSs_version=$3

  release_types="unstable testing stable"
  trunk_rel_path=../../../../
  packages_target=${trunk_rel_path}/builders/packages/
  PKGNAME=$(cat $arch/control | grep 'Package:' | tail -n 1 | cut -d ":" -f2- | cut -d " " -f2-)

  echo " "
  echo "* Erasing previous tmp Files..."
  rm -rf tmp/

  echo " "
  echo "* Compiling sources..."
  cd ${trunk_rel_path}/compss/tools/monitor
  mvn -U clean install
  cd -

  echo " "
  echo "* Create deployment folders"
  COMPSs_target=tmp/opt/COMPSs
  mkdir -p ${COMPSs_target}
  mkdir -p ${COMPSs_target}/Tools/monitor
  mkdir -p tmp/etc/init.d/

  echo " "
  echo " * Downloading and configuring Tomcat for COMP Superscalar Monitor..."
  TOMCAT_VER="7.0.65"
  TOMCAT_URL="http://compss.bsc.es/repo/apache-tomcat/apache-tomcat-7.0.65.tar.gz"
  wget $TOMCAT_URL
  tar xzf apache-tomcat-$TOMCAT_VER.tar.gz
  mv apache-tomcat-$TOMCAT_VER ${COMPSs_target}/Tools/monitor/apache-tomcat
  rm -rf ${COMPSs_target}/Tools/monitor/apache-tomcat/webapps/*
  rm -f ${COMPSs_target}/Tools/monitor/apache-tomcat/conf/server.xml
  rm apache-tomcat-$TOMCAT_VER.tar.gz

  echo " "
  echo "* Copy deployment files"
  #Monitor files
  cp ${trunk_rel_path}/compss/tools/monitor/target/*.war ${COMPSs_target}/Tools/monitor/apache-tomcat/webapps/
  cp ${trunk_rel_path}/compss/tools/monitor/target/classes/compss-monitor.conf ${COMPSs_target}/Tools/monitor/apache-tomcat/conf/
  cp ${trunk_rel_path}/compss/tools/monitor/target/classes/server.xml ${COMPSs_target}/Tools/monitor/apache-tomcat/conf/
  cp ${trunk_rel_path}/compss/tools/monitor/target/classes/*log4j* ${COMPSs_target}/Tools/monitor/
  cp ${trunk_rel_path}/compss/tools/monitor/scripts/compss-monitor tmp/etc/init.d/

  for rt in ${release_types}; do
    echo " "
    echo "* Creating package structure for ${rt}..."
    mkdir -p tmp/DEBIAN
    chmod 755 .
    cp $arch/control tmp/DEBIAN/control
    cp docs tmp/DEBIAN/docs
    cp compat tmp/DEBIAN/compat
    cp conffiles tmp/DEBIAN/conffiles
    cp preinst tmp/DEBIAN/preinst
    cp postinst tmp/DEBIAN/postinst
    cp prerm tmp/DEBIAN/prerm
    cp postrm tmp/DEBIAN/postrm
    PKGVERSION=${COMPSs_version}.${distribution}
    if [ "$rt" != "stable" ]; then
      PKGVERSION="${COMPSs_version}.${distribution}-${rt}"
    fi
    sed -i '/Version:/cVersion: '${PKGVERSION}'' tmp/DEBIAN/control

    echo "  * Generating md5sums file..." 
    cd tmp/
    files=$(find . -type f | grep -v DEBIAN | cat)
    if [ "${files}" != "" ]; then
      md5sum ${files} > DEBIAN/md5sums
    else 
      touch DEBIAN/md5sums
    fi
    cd ../
    echo Installed-Size: $(du tmp/ | tail -1 | awk '{print $1}') >> tmp/DEBIAN/control

    echo "  * Generating DEB package..."
    dpkg -b tmp ${PKGNAME}_${PKGVERSION}_${arch}.deb
    if [ $? -ne 0 ]; then
      echo "Error creating deb package"
      exit 1
    fi

    echo "  * Cleaning tmp files..."
    rm -rf tmp/DEBIAN

    echo "  * Moving built DEB package to final location..."
    mkdir -p ${packages_target}/${distribution}/$PKGNAME 
    mv ${PKGNAME}_${PKGVERSION}_${arch}.deb ${packages_target}/${distribution}/$PKGNAME
  done

  # Clean COMPSs tmp files
  echo " "
  echo "* Cleaning COMPSs tmp files"
  rm -rf tmp/

