#!/bin/bash -e

  action=$1

  if [ "$action" == "install" ]; then
    if [ $# -eq 2 ]; then
      # Installation knowing previous old version
      oldversion=$2
      echo " "
      echo " * Installing COMPSs Monitor Tool from previous version ${oldversion}..."
      echo " "
      rm -rf /opt/COMPSs/Tools/monitor
    else
      # Clean installation
      echo " "
      echo " * Installing COMPSs Monitor Tool..."
      echo " "
    fi
  elif [ "$action" == "upgrade" ]; then
    # Upgrade from previous version
    oldversion=$2
    echo " "
    echo " * Upgrading COMPSs Monitor Tool from previous version ${oldversion}..."
    echo " "
    if [ -d "/opt/COMPSs/Tools/monitor" ]; then
      mv /opt/COMPSs/Tools/monitor /tmp/COMPSs_monitor.bkp
    fi
  elif [ "$action" == "abort-upgrade" ]; then
    # Update failed, recover previous version
    newversion=$2
    echo " "
    echo " * COMPSs Monitor Tool $newversion upgrade aborted. Please check errors above."
    echo " "
    if [ -d "/tmp/COMPSs_monitor.bkp" ]; then
       mkdir -p /opt/COMPSs/Tools/
       mv /tmp/COMPSs_monitor.bkp /opt/COMPSs/Tools/monitor
    fi
  fi

