#!/bin/bash -e
  
  # Obtain parameters
  source_base_dir=$1
  target_base_dir=$2
  
  
  # Copy files
  cp -f ${source_base_dir}/target/63-decaf.jar ${target_base_dir}/decaf.jar   
                  
  cp -f ${source_base_dir}/project.xml ${target_base_dir}/project.xml                  
  cp -f ${source_base_dir}/resources.xml ${target_base_dir}/resources.xml
  cp -Rf ${source_base_dir}/decaf ${target_base_dir}/decaf
  cp -f ${source_base_dir}/execution ${target_base_dir}/execution
  cp -f ${source_base_dir}/result ${target_base_dir}/result
