#!/bin/bash

  # Obtain parameters
  COMPSs_exec=$1
  comm=$2
  runcompss_opts=$3
  base_app_dir=$4
  COMPSs_log_folder=$5
  target_log_folder=$6
  retry_num=$7
  execution_envs=$8
 
  # Global variables
  exit_value=1
  app_name="Matmul_mo"

  #----------------------------------------------------------------------------------
  # Compiling C app
  cd "${base_app_dir}" || exit 1
  "$(dirname "${COMPSs_exec}")"/compss_build_app "${app_name}"
  ev=$?
  if [ $ev -ne 0 ]; then
     echo "[ERROR] Cannot compile C app. See errors above."
     exit $ev
  fi

  #----------------------------------------------------------------------------------
  # Generating project.xml
  sed -i '/<InstallDir>/c<InstallDir>'"${COMPSS_HOME}"'<\/InstallDir>' "${base_app_dir}"/project.xml
  sed -i '/<AppDir>/c<AppDir>'"${base_app_dir}"'\/<\/AppDir>' "${base_app_dir}"/project.xml

  #----------------------------------------------------------------------------------
  # Create all working dir folders
  mkdir -p /tmp/COMPSsWorker01/

  #----------------------------------------------------------------------------------
  # Run application
  echo
  echo "*** RUNNING C APPLICATION MATMUL MO"
  output_log="${target_log_folder}/matmul_mo_c_0${retry_num}.outputlog"
  error_log="${target_log_folder}/matmul_mo_c_0${retry_num}.errorlog"
  N=4
  M=64
  val=1
  expectedTime=360s

  # shellcheck disable=SC2086
  timeout --signal=2 $expectedTime "${COMPSs_exec}" \
     --project="${base_app_dir}"/project.xml \
     --resources="${base_app_dir}"/resources.xml \
     \
     --comm="$comm" \
     --conn=es.bsc.compss.connectors.DefaultNoSSHConnector \
     \
     --debug \
     ${runcompss_opts} \
     \
     --lang=c \
     \
     --input_profile=matmul_mo_in.profile \
     --output_profile=matmul_mo_out.profile \
     --scheduler_config_file=mo_config.properties \
     --scheduler=es.bsc.compss.scheduler.fullgraph.multiobjective.MOScheduler \
     \
     "${base_app_dir}/master/${app_name}" $N $M $val > >(tee "${output_log}") 2> >(tee "${error_log}" >&2)
   
  # Check timeout
  if [[ "$?" = "124" ]]; then
     # Copy LOG files
     cp -rf "${COMPSs_log_folder}/${app_name}_0${retry_num}"/* "${target_log_folder}"

     # Report time out
     echo "[WARNING] C Application timed out" >> "${output_log}"
     exit_value=124
  else
     # Copy LOG files
     cp -rf "${COMPSs_log_folder}/${app_name}_0${retry_num}"/* "${target_log_folder}"

     # Check result
     "${base_app_dir}"/result "${output_log}" "${error_log}" "${target_log_folder}"
     exit_value=$?
  fi
  
  #----------------------------------------------------------------------------------
  # Return execution status
  exit ${exit_value}
