#!/bin/bash -e

SANDBOX="/tmp/agent_container"
rm -rf ${SANDBOX}
mkdir -p ${SANDBOX}

INIT_DIR=$(pwd)
RUNTIME_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )"/../../../.. && pwd )"

echo "Copying framework to ${SANDBOX}"
cp -r "${RUNTIME_DIR}" ${SANDBOX}
cp "${RUNTIME_DIR}/utils/docker/compss-image-dockerfile/agent/Dockerfile" ${SANDBOX}/framework/Dockerfile

echo "Removing Tests from maven"
sed -i -e 's#<module>tests/sources</module># #g'  ${SANDBOX}/framework/pom.xml
sed -i -e 's#<module>performance_analysis/auto-cbm</module># #g'  ${SANDBOX}/framework/pom.xml


# UPDATE DEFAULT CONFIGURATION FILES
echo "Updating configuration files"
sed -i '/default_resources.xml/d' ${SANDBOX}/framework/compss/runtime/adaptors/agent/RESTagent/scripts/startAgent.sh
sed -i '/default_project.xml/d' ${SANDBOX}/framework/compss/runtime/adaptors/agent/RESTagent/scripts/startAgent.sh

# CLEANING MAVEN PROJECT
cd "${SANDBOX}"/framework
echo "Building image"
mvn clean

# BUILDING IMAGE
echo "Building image"
cd "${SANDBOX}"
docker build -t mf2c/compss-agent:it2 ./framework

rm -rf "${SANDBOX}"
cd "${INIT_DIR}"
