#!/bin/bash -e
  
#Obtain parameter
source_base_dir=$1
target_base_dir=$2
  
#Copy files

cp -rf ${source_base_dir}/project.xml ${target_base_dir}/project.xml
cp -rf ${source_base_dir}/resources.xml ${target_base_dir}/resources.xml
cp -rf ${source_base_dir}/target/09-errorManagement.jar ${target_base_dir}/ErrorManagerTest.jar
  
cp -rf ${source_base_dir}/execution ${target_base_dir}/execution
cp -rf ${source_base_dir}/deploy ${target_base_dir}/deploy
cp -rf ${source_base_dir}/result ${target_base_dir}/result
