#!/bin/bash

  # Obtain parameters
  COMPSs_exec=$1
  comm=$2
  runcompss_opts=$3
  base_app_dir=$4
  COMPSs_log_folder=$5
  target_log_folder=$6
  retryNum=$7
  pythonInterpreter=$8

  #Global exit variable
  exitValue=0

  #----------------------------------------------------------------------------------
  # Generate Project.xml according to system
  sed -i '/<InstallDir>/c<InstallDir>'"${COMPSS_HOME}"'<\/InstallDir>' "${base_app_dir}"/project.xml

  #----------------------------------------------------------------------------------
  # Create all working dir folders
  mkdir -p /tmp/COMPSsWorker01/

  #----------------------------------------------------------------------------------
  # Set environment variables
  export computingUnits="2"
  export processorName="MainProcessor"
  export processorSpeed="2.4"
  export processorArchitecture="amd64"
  export processorPropertyName="ThreadAffinity"
  export processorPropertyValue="Big"
  export memorySize="8.0"
  export memoryType="Volatile"
  export storageSize="240.0"
  export storageType="SSD"
  export operatingSystemType="Linux"
  export operatingSystemDistribution="OpenSUSE"
  export operatingSystemVersion="13.2"
  export appSoftware="JAVA, PYTHON, COMPSS"
  export hostQueues="sequential, debug, bsc"
  export wallClockLimit="10"

  #----------------------------------------------------------------------------------
  # Run application 1 - environment variables
  echo
  echo "*** RUNNING PYTHON APPLICATION ENVIRONMENT VARIABLES TASK"
  output_log="${target_log_folder}/environmentVariables_python_0${retryNum}.outputlog"
  error_log="${target_log_folder}/environmentVariables_python_0${retryNum}.errorlog"
  expectedTime=80s

  # shellcheck disable=SC2086
  timeout --signal=2 $expectedTime "${COMPSs_exec}" \
     --project="${base_app_dir}"/project.xml \
     --resources="${base_app_dir}"/resources.xml \
     \
     --comm="$comm" \
     \
     --debug \
     ${runcompss_opts} \
     \
     --lang=python \
     --python_interpreter="$pythonInterpreter" \
     --pythonpath="${base_app_dir}"/src \
     \
     "${base_app_dir}"/src/environmentVariables.py > >(tee "${output_log}") 2> >(tee "${error_log}" >&2)

  # Take the latest log folder as retry number
  # Fixes the possiblity to test with both python 2 and 3 one after the other
  retryNum=$(find "${COMPSs_log_folder}" -name environmentVariables.py* -type d | wc -l)

  # Check timeout
  if [[ "$?" = "124" ]]; then
     # Copy LOG files
     cp -rf "${COMPSs_log_folder}"/environmentVariables.py_0"${retryNum}"/* "${target_log_folder}"

     # Report time out
     echo "[WARNING] Python Application timed out" >> "${output_log}"
     exitValue=124
  else
     # Copy LOG files
     cp -rf "${COMPSs_log_folder}"/environmentVariables.py_0"${retryNum}"/* "${target_log_folder}"

     # Check result
     "${base_app_dir}"/result "${output_log}" "${error_log}" "${target_log_folder}" "${comm}"
     exitValue=$?
  fi

  #----------------------------------------------------------------------------------
  # Return execution status
  exit $exitValue
