#!/bin/bash -e
  
  #Obtain parameter
  source_base_dir=$1
  target_base_dir=$2
  
  #Copy files
  cp -f ${source_base_dir}/target/10-priorityTasks.jar ${target_base_dir}/priorityTasks.jar 
                    
  cp -f ${source_base_dir}/project.xml ${target_base_dir}/project_priorityTasks.xml                  
  cp -f ${source_base_dir}/resources.xml ${target_base_dir}/resources_priorityTasks.xml
  
  cp -f ${source_base_dir}/execution ${target_base_dir}/execution
  cp -f ${source_base_dir}/result ${target_base_dir}/result
