#!/bin/bash

  #Obtain parameters
  COMPSs_exec=$1
  comm=$2
  runcompss_opts=$3
  base_app_dir=$4
  COMPSs_log_folder=$5
  target_log_folder=$6
  retryNum=$7
  
  #Global exit variable
  exitValue=0
  
  #----------------------------------------------------------------------------------
  #Generate Project.xml according to system
  sed -i '/<InstallDir>/c<InstallDir>'${COMPSS_HOME}'<\/InstallDir>' ${base_app_dir}/project_priorityTasks.xml
  
  #----------------------------------------------------------------------------------
  #Create all working dir folders
  mkdir -p /tmp/COMPSsWorker01/
  
  #----------------------------------------------------------------------------------
  #Run application 1 - Priority Tasks
  echo
  echo "*** RUNNING JAVA APPLICATION PRIORITY TASKS"
  output_log="${target_log_folder}/priorityTasks_0${retryNum}.outputlog"
  error_log="${target_log_folder}/priorityTasks_0${retryNum}.errorlog"
  expectedTime=120s
  normal=20
  priority=20
  
  timeout --signal=2 $expectedTime ${COMPSs_exec} \
     --project=${base_app_dir}/project_priorityTasks.xml \
     --resources=${base_app_dir}/resources_priorityTasks.xml \
     --debug \
     --lang=java \
     --comm=$comm \
     ${runcompss_opts} \
     --classpath=${base_app_dir}/priorityTasks.jar \
     priorityTasks.PriorityTasks $normal $priority > >(tee ${output_log}) 2> >(tee ${error_log} >&2)
  
  
  #Check timeout
  if [[ "$?" = "124" ]]; then
     #Copy LOG files
     cp -rf ${COMPSs_log_folder}/priorityTasks.PriorityTasks_0${retryNum}/* ${target_log_folder}
     
     #Report time out
     echo "[WARNING] Java Application timed out" >> ${output_log}
     exitValue=124
  else
     #Copy LOG files
     cp -rf ${COMPSs_log_folder}/priorityTasks.PriorityTasks_0${retryNum}/* ${target_log_folder}
  
     #Check result
     ${base_app_dir}/result ${output_log} ${target_log_folder} $normal $priority
     exitValue=$?
  fi
  
  
  #----------------------------------------------------------------------------------
  #Return execution status
  exit $exitValue
  
