#!/bin/bash -e

  #Obtain parameters
  COMPSs_exec=$1
  comm=$2
  base_app_dir=$3
  COMPSs_log_folder=$4
  target_log_folder=$5
  retryNum=$6

  #Global exit variable
  exitValue=0

  #----------------------------------------------------------------------------------
  #Generate Project.xml according to system
  sed -i '/<InstallDir>/c<InstallDir>'${IT_HOME}'<\/InstallDir>' ${base_app_dir}/project.xml
 
  #----------------------------------------------------------------------------------
  #Create all working dir folders
  mkdir -p /tmp/COMPSsWorker01/
  
  #----------------------------------------------------------------------------------
  #Run application 1 - Test
  echo
  echo "*** RUNNING PYTHON ARGS KWARGS TEST"
  output_log="${target_log_folder}/python_test_0${retryNum}.outputlog"
  error_log="${target_log_folder}/python_test_0${retryNum}.errorlog"  
  expectedTime=360s

  timeout --signal=2 $expectedTime ${COMPSs_exec} \
     --pythonpath=${base_app_dir}/src \
     --project=${base_app_dir}/project.xml \
     --resources=${base_app_dir}/resources.xml \
     --debug \
     --comm=$comm \
     --lang=python \
     ${base_app_dir}/src/argskwargs.py > >(tee ${output_log}) 2> >(tee ${error_log} >&2)
  
  #Check timeout
  if [[ "$?" = "124" ]]; then
     #Copy LOG files
     cp -rf ${COMPSs_log_folder}/argskwargs.py_0${retryNum}/* ${target_log_folder}

     #Report timeout
     echo "[WARNING] Python Application timed out" >> ${output_log}
     exitValue=124
  else
     #Copy LOG files
     cp -rf ${COMPSs_log_folder}/argskwargs.py_0${retryNum}/* ${target_log_folder}
  
     #Check result
     ${base_app_dir}/result ${output_log} ${error_log} ${target_log_folder}
     exitValue=$?
  fi
  
  #----------------------------------------------------------------------------------
  #Return execution status
  exit $exitValue

