#!/bin/bash
 
  #############################################################
  # Name: buildMN_aux
  # Description: SCRIPT FOR LOCAL COMPSs BUILD in MareNostrum
  # Parameters: <targetDir>           Base Target Installation folder
  #
  # ATTENTION: DO NOT EXECUTE THIS FILE. IT IS AUTOMATICALLY 
  #            EXECUTED FROM buildMN script
  #############################################################

  usage() {
    echo "Incorrect number of parameters"
    echo " Usage: buildMN_aux <FullTargetPath>"
    echo " "
    exit 1
  }

  ####################
  # MAIN
  ####################
  # Get parameters
  if [ $# -ne 1 ]; then
    usage
  fi

  # SET SCRIPT VARIABLES
  targetDir=$1
  scriptDir=$(dirname $0)

  modules="intel/2017.4 transfer/1.0 bsc/1.0 impi/2017.4 mkl/2017.4 python/2.7.13 boost/1.64.0_py2 java/8u131 papi/5.5.1" # gcc/7.2.0"
  additionalExports=""
  queues_cfg="mn.cfg"
  extrae_with_openmpi="false"
  openmpi_version="/1.10.4"
  extrae_with_impi="true"
  impi_version=""
  #echo " salloc -p interactive /bin/bash -c \"${scriptDir}/buildSC_aux ${targetDir} '${modules}' '${additionalExports}' '${queues_cfg}' '${extrae_with_openmpi}' '${openmpi_version}' '${extrae_with_impi}' '${impi_version}'\""
  ${scriptDir}/buildSC_aux ${targetDir} "${modules}" "${additionalExports}" "${queues_cfg}" "${extrae_with_openmpi}" "${openmpi_version}" "${extrae_with_impi}" "${impi_version}"

  # END
  exit 0

