#!/bin/bash

  #############################################################
  # Name: buildSalomon_aux
  # Description: SCRIPT FOR LOCAL COMPSs BUILD in Salomon
  # Parameters: <targetDir>           Base Target Installation folder
  #
  # ATTENTION: DO NOT EXECUTE THIS FILE. IT IS AUTOMATICALLY
  #            EXECUTED FROM buildSalomon script
  #############################################################

  usage() {
    echo "Incorrect number of parameters"
    echo " Usage: buildKarolina_aux <FullTargetPath>"
    echo " "
    exit 1
  }

  ####################
  # MAIN
  ####################
  # Get parameters
  if [ $# -ne 1 ]; then
    usage
  fi

  # SET SCRIPT VARIABLES
  targetDir=$1
  SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

  # DEFINE MODULES
  modules="GCC/10.2.0 libxml2/2.9.10-GCCcore-10.2.0 binutils/2.35-GCCcore-10.2.0 bzip2/1.0.8-GCCcore-10.2.0 zlib/1.2.11-GCCcore-10.2.0 impi/2019.9.304-iccifort-2020.4.304 Java/1.8.0_221"
  unload_before_python="ignore"
  run_before_py3_modules="ignore"
  py3_modules="Python/3.8.6-GCCcore-10.2.0"
  run_before_py3_other_modules="ignore"
  py3_other_modules="ignore"

  # DEFINE CONFIGURATION PARAMETERS
  #(Environment vars must be scaped to get the correct value if not it could take a value previous to load the modules)
  additionalExports="export EXTRAE_MPI_PATH=\$I_MPI_ROOT/intel64/ EXTRAE_MPI_LIBS=\$I_MPI_ROOT/intel64/lib/release"
  additional_module_use_folder="ignore"
  queues_cfg="karolina.cfg"
  extrae_with_openmpi="false"
  openmpi_version=""
  extrae_with_impi="true"
  impi_version=""
  autoparallel="false"
  c_binding="false"
  extrae_no_mpi="true"
  r_binding="false"

  # CALL buildSC_aux
  "${SCRIPT_DIR}"/buildSC_aux "${targetDir}" "${modules}" "${unload_before_python}" "${run_before_py3_modules}" "${py3_modules}" "${run_before_py3_other_modules}" "${py3_other_modules}" "${additionalExports}" "${additional_module_use_folder}" "${queues_cfg}" "${extrae_with_openmpi}" "${openmpi_version}" "${extrae_with_impi}" "${impi_version}" "${autoparallel}" "${c_binding}" "${extrae_no_mpi}" "${r_binding}"
  ev=$?

  # End
  if [ $ev -ne 0 ]; then
    echo "ERROR: Exception in auxiliar script"
    exit $ev
  fi
  exit 0
