#!/bin/bash -e

  distr=$1
  mode=$2
  COMPSS_VERSION=$3

  SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
  package_name=compss-tools
  trunk_rel_path=../../../../

  echo " "
  echo "* Erasing previous tmp Files..."
  rm -rf tmp/

  echo " "
  echo "* Creating package structure..."
  mkdir -p tmp/BUILD tmp/RPMS tmp/SOURCES/ tmp/SPECS/ tmp/SRPMS tmp/BUILDROOT

  echo " "
  echo "* Copying SPEC file to RPM build path..."
  echo " "
  cp ./${package_name}_"${mode}".spec tmp/SPECS/

  echo " "
  echo "* Generating RPM package for version $COMPSS_VERSION..."
  cd tmp/
  rpmbuild --define "_topdir $PWD" -bb --clean SPECS/${package_name}_"${mode}".spec
  ev=$?
  if [ $ev -ne 0 ]; then
        echo "Error creating rpm"
        exit $ev
  fi
  cd "${SCRIPT_DIR}"

  echo " "
  echo "* Moving built RPM package to final location..."
  mkdir -p ${trunk_rel_path}/builders/packages/"${distr}"/${package_name}
  mv tmp/RPMS/"${mode}"/${package_name}-* ${trunk_rel_path}/builders/packages/"$distr"/${package_name}

  echo " "
  echo "* Cleaning all tmp files..."
  rm -r tmp/

