#!/bin/bash -e

  usage() {
    exitValue=$1
  
    echo " "
    echo "Usage $0 <version>"
    echo " "
  
    exit "$exitValue"
  }

 
  #=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
  # MAIN
  #=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

  # Check parameters
  if [ $# -ne 1 ]; then
    echo "ERROR: Incorrect number of parameters"
    usage 1
  fi

  # Set parameters
  version=$1
  buildFolder="mt"
  buildScript="buildMT"
  MTuser=compss
  MTendpoint=mt1.bsc.es

  # Call generic script
  ./deploy_tag_to_SC "${version}" ${buildFolder} ${buildScript} ${MTuser} ${MTendpoint}

  # END
  exit 0

