#!/bin/bash -e

  usage() {
    exitValue=$1
  
    echo " "
    echo "Usage $0 <version>"
    echo " "
  
    exit $exitValue
  }

 
  #=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
  # MAIN
  #=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

  # Check parameters
  if [ $# -ne 1 ]; then
    echo "ERROR: Incorrect number of parameters"
    usage 1
  fi

  # Set parameters
  version=$1
  builderFolder="nord"
  builderScript="buildNord"
  nordUser=compss
  nordEndpoint=nord1.bsc.es

  # Call generic script
  cd ${scriptDir}
  ./deploy_tag_to_SC ${version} ${buildFolder} ${buildScript} ${nordUser} ${nordEndpoint}
  cd -

  # END
  exit 0

