#!/bin/bash -e

usage() {
  exitValue=$1

  echo " "
  echo "Usage ./generate_tag <version>"
  echo " "

  exit $exitValue
}
 
  #=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
  #=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
  # Check parameters
  if [ $# -ne 1 ]; then
    echo "ERROR: Incorrect number of parameters"
    usage 1
  fi

  # Get version parameters
  version=$1
  echo "Creating new COMPSs Tag ${version}..."

  # Define script variables
  script_dir=$(pwd)/$(dirname $0)
  trunk_dir=${script_dir}../../../
  tags_dir=${trunk_dir}/../../../../tags/

  #---------------------------------------------------------------------
  # Create tag
  echo "- Create tag"
  svn cp ${trunk_dir} ${tags_dir}/${version}

  #---------------------------------------------------------------------
  # Add headers
  echo "- Generate header files"
  sh ${tags_dir}/${version}/utils/scripts/header_setup/replace_all.sh

  #---------------------------------------------------------------------
  # Commit modifications
  echo "- Commit modifications"
  cd ${tags_dir}
  svn commit -m "Adding new tag ${version}"
  cd ${script_dir}

  #---------------------------------------------------------------------
  # NOTIFY SUCCESS
  echo " "
  echo "FINISHED! New COMPSs Tag ${version} created"
  echo " "

  # END
  exit 0
