#!/bin/bash -e

usage() {
  exitValue=$1

  echo " "
  echo "Usage ./generate_tag <version>"
  echo " "

  exit $exitValue
}
 
  #=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
  #=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
  # Check parameters
  if [ $# -ne 1 ]; then
    echo "ERROR: Incorrect number of parameters"
    usage 1
  fi

  # Get version parameters
  version=$1
  echo "Creating new COMPSs Tag ${version}..."

  # Define script variables
  script_dir=$(pwd)/$(dirname $0)
  trunk_dir=${script_dir}/../../../
  tags_dir=${trunk_dir}/../tags/

  #---------------------------------------------------------------------
  # Clean trunk
  cd ${trunk_dir}
  mvn -U clean
  cd ${script_Dir}

  #---------------------------------------------------------------------
  # Create tag
  echo "- Create tag"
  echo "   ScriptDir: ${script_dir}"
  echo "   TrunkDir:  ${trunk_dir}"
  echo "   TagsDir:   ${tags_dir}"
  svn cp ${trunk_dir} ${tags_dir}/${version}

  #---------------------------------------------------------------------
  # Add headers
  echo "- Generate header files"
  sh ${tags_dir}/${version}/utils/scripts/header_setup/replace_all.sh

  #---------------------------------------------------------------------
  # Commit modifications
  echo "- Commit modifications"
  cd ${tags_dir}
  svn commit -m "Adding new tag ${version}"
  cd ${script_dir}

  #---------------------------------------------------------------------
  # Clean tag
  cd ${tags_dir}
  rm -rf ${version}
  svn up

  #---------------------------------------------------------------------
  # NOTIFY SUCCESS
  echo " "
  echo "FINISHED! New COMPSs Tag ${version} created"
  echo " "

  # END
  exit 0
