#!/bin/bash -e
  
  #Obtain parameter
  source_base_dir=$1
  target_base_dir=$2
  
  #Copy files
  cp -f ${source_base_dir}/target/15-kmeans.jar ${target_base_dir}/kmeans.jar   
                  
  cp -f ${source_base_dir}/project.xml ${target_base_dir}/project_kmeans.xml                  
  cp -f ${source_base_dir}/resources.xml ${target_base_dir}/resources_kmeans.xml
  
  cp -f ${source_base_dir}/execution ${target_base_dir}/execution
  cp -f ${source_base_dir}/result ${target_base_dir}/result
  