#!/bin/bash

  # Obtain parameters
  COMPSs_exec=$1
  comm=$2
  runcompss_opts=$3
  base_app_dir=$4
  COMPSs_log_folder=$5
  target_log_folder=$6
  retryNum=$7
  
  # Global exit variable
  exitValue=0
  
  #----------------------------------------------------------------------------------
  #Generate Project.xml according to system
  sed -i '/<InstallDir>/c<InstallDir>'${COMPSS_HOME}'<\/InstallDir>' ${base_app_dir}/project.xml
  
  #----------------------------------------------------------------------------------
  # Create all working dir folders
  mkdir -p /tmp/COMPSsWorker01/
  
  #----------------------------------------------------------------------------------
  # Run application 75 - Worker Environment 
  echo
  echo "*** RUNNING JAVA APPLICATION WORKER ENVIRONMENT TASK"
  output_log="${target_log_folder}/workerEnvironment_0${retryNum}.outputlog"
  error_log="${target_log_folder}/workerEnvironment_0${retryNum}.errorlog"
  expectedTime=60s

  extraCPmaster="/tmp/extraClasspath/master"
  extraPPmaster="/tmp/extraPythonpath/master"
  extraLPmaster="/tmp/extraLibrarypath/master"
  
  timeout --signal=2 $expectedTime ${COMPSs_exec} \
     --project=${base_app_dir}/project.xml \
     --resources=${base_app_dir}/resources.xml \
     --debug \
     --comm=$comm \
     ${runcompss_opts} \
     --classpath=${base_app_dir}/workerEnvironment.jar:${extraCPmaster} \
     --pythonpath=${extraPPmaster} \
     --library_path=${extraLPmaster} \
     workerEnvironment.Main "${extraCPmaster}" "${extraPPmaster}" "${extraLPmaster}" > >(tee ${output_log}) 2> >(tee ${error_log} >&2)
  
  # Check timeout
  if [[ "$?" = "124" ]]; then
     # Copy LOG files
     cp -rf ${COMPSs_log_folder}/workerEnvironment.Main_0${retryNum}/* ${target_log_folder}
     
     # Report time out
     echo "[WARNING] Java Application timed out" >> ${output_log}
     exitValue=124
  else
     # Copy LOG files
     cp -rf ${COMPSs_log_folder}/workerEnvironment.Main_0${retryNum}/* ${target_log_folder}
  
     # Check result
     ${base_app_dir}/result ${output_log} ${target_log_folder}
     exitValue=$?
  fi
 
  
  #----------------------------------------------------------------------------------
  # Return execution status
  exit $exitValue

