DATATYPE_MAP = {
    "BOOLEAN_T": "Boolean",
    "CHAR_T": "Text",
    "BYTE_T": "Integer",
    "SHORT_T": "Integer",
    "INT_T": "Integer",
    "LONG_T": "Integer",
    "FLOAT_T": "Float",
    "DOUBLE_T": "Float",
    "STRING_T": "Text",
    "STRING_64_T": "Text",
    "FILE_T": "File",
    "OBJECT_T": "?",
    "PSCO_T": "?",
    "EXTERNAL_PSCO_T": "?",
    "BINDING_OBJECT_T": "?",
    "WCHAR_T": "Text",
    "WSTRING_T": "Text",
    "LONGLONG_T": "Integer",
    "VOID_T": "?",
    "ANY_T": "DataType",
    "ARRAY_CHAR_T": "Text",
    "ARRAY_BYTE_T": "?",
    "ARRAY_SHORT_T": "?",
    "ARRAY_INT_T": "?",
    "ARRAY_LONG_T": "?",
    "ARRAY_FLOAT_T": "?",
    "ARRAY_DOUBLE_T": "?",
    "COLLECTION_T": "?",
    "DICT_COLLECTION_T": "?",
    "STREAM_T": "?",
    "EXTERNAL_STREAM_T": "?",
    "ENUM_T": "Text",
    "NULL_T": "Null",
    "DIRECTORY_T": "Dataset",
}


def map_datatype(custom_type: str) -> str:
    """ Map a custom COMPSs datatype to a Schema.org type. """
    return DATATYPE_MAP.get(custom_type, "Text")  # Default fallback
