#!/bin/bash -e

base="base22"
platforms="linux/amd64,linux/arm64"
images="rt bindings all tutorial ci"
version=$(date -u +%y%m%d-%H%M%S)

while getopts :b:p: OPTION
do
  case ${OPTION} in
    b) base=${OPTARG} ;;
    p) platforms=${OPTARG} ;;
    *) echo "Usage: ${BASH_SOURCE[0]} [<Base> -b ${base}] [<Platforms> -p ${platforms}] [<Images> ${images}]" ; exit 1 ;;
  esac
done
shift $((OPTIND - 1)) && images=${*-${images}}

echo "- Base: ${base}"
echo "- Platforms: ${platforms}"
echo "- Images: ${images}"
echo "- Version: ${version}"

cd -- "$(dirname -- "${BASH_SOURCE[0]}")"

read -rp 'Do you want to push images? [Yes/NO] ' answer
[[ "${answer}" =~ ^[Yy](es)?$ ]] && docker login -u compss $(test -t 0 || echo "--password-stdin") \
                                 && echo "Images will be pushed to Docker Hub" && push=--push \
                                 || echo "Images won't be pushed to Docker Hub"

cache=--no-cache
for image in ${images}
do
  echo "Building image compss/${base}_${image}:${version}"
  docker build ${cache} ${push} --platform ${platforms} --target base_${image} \
               -t compss/${base}_${image}:${version} -t compss/${base}_${image} .
  cache=
done
