#!/bin/bash -e

  #############################################################
  # Name: buildSSF_aux
  # Description: SCRIPT FOR LOCAL COMPSs BUILD in SSF
  # Parameters: <targetDir> Base Target Installation folder
  #
  # ATTENTION: DO NOT EXECUTE THIS FILE. IT IS AUTOMATICALLY
  #            EXECUTED FROM buildSSF script
  #############################################################

  usage() {
    echo "Incorrect number of parameters"
    echo " Usage: buildSSF_aux <FullTargetPath>"
    echo " "
    exit 1
  }

  ####################
  # MAIN
  ####################
  # Get parameters
  if [ $# -ne 1 ]; then
    usage
  fi

  # SET SCRIPT VARIABLES
  targetDir=$1
  SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

  # DEFINE MODULES
  modules="autotools"
  unload_before_python="ignore"
  py2_modules="ignore"
  py3_modules="ignore"
  py3_other_modules="ignore"

  # DEFINE CONFIGURATION PARAMETERS
  additionalExports="export BOOST_CPPFLAGS=-I/opt/intel/hpc-orchestrator/pub/libs/gnu/mvapich2/boost/1.63.0/include PATH=/usr/include/libxml:$PATH"
  additional_module_use_folder="ignore"
  queues_cfg="ssf.cfg"
  extrae_with_openmpi="false"
  openmpi_version=""
  extrae_with_impi="true"
  impi_version=""
  autoparallel="false"

  # CALL buildSC_aux
  "${SCRIPT_DIR}"/buildSC_aux "${targetDir}" "${modules}" "${unload_before_python}" "${py2_modules}" "${py3_modules}" "${py3_other_modules}" "${additionalExports}" "${additional_module_use_folder}" "${queues_cfg}" "${extrae_with_openmpi}" "${openmpi_version}" "${extrae_with_impi}" "${impi_version}" "${autoparallel}"

  # END
  exit 0
