#!/bin/bash

  # Obtain parameters
  COMPSs_exec=$1
  comm=$2
  runcompss_opts=$3
  base_app_dir=$4
  target_log_folder=$5
  compss_module=$6
  execution_envs=$7

  # Global variables
  app_name="simple.py"

  #--------------------------------------------------------------------------------


  #----------------------------------------------------------------------------------
  # Create all working dir folders
  mkdir -p /tmp/COMPSsWorker01/

  #----------------------------------------------------------------------------------
  # Run application
  echo
  echo "*** RUNNING PYTHON APPLICATION SIMPLE"
  for exec_env in ${execution_envs}; do
    echo "   - Running with Environment: ${exec_env}"
    output_log="${target_log_folder}/${app_name}_${exec_env}_0.outputlog"
    error_log="${target_log_folder}/${app_name}_${exec_env}_0.errorlog"
    specific_log_dir="${target_log_folder}/${app_name}_${exec_env}_0"
    mkdir -p "${specific_log_dir}"

    master_working_dir=${target_log_folder}
    if [ "$exec_env" == 'gpfs' ]; then
        worker_working_dir=${specific_log_dir}
    fi
    if [ "$exec_env" == 'scratch' ]; then
        worker_working_dir="scratch"
    fi

    export COMPSS_PYTHON_VERSION=3-ML

    module load ${compss_module}

    expectedTime=5
    # shellcheck disable=SC2086
    "${COMPSs_exec}" --exec_time=${expectedTime} \
      --num_nodes=2 \
      --comm="$comm" \
      --master_working_dir=${master_working_dir} \
      --worker_working_dir=${worker_working_dir} \
      --base_log_dir=${target_log_folder} \
      --debug \
      --summary \
      --qos=debug \
      \
      --debug \
      ${runcompss_opts} \
      \
      --lang=python \
      --pythonpath="${base_app_dir}" \
      \
      "${base_app_dir}/src/${app_name}" > >(tee "${output_log}") 2> >(tee "${error_log}" >&2)


  done
