#!/bin/bash -e
  
  #Obtain parameter
  source_base_dir=$1
  target_base_dir=$2
  
  #Copy files
  cp -f ${source_base_dir}/target/04-constraintsTest.jar ${target_base_dir}/constraintsTest.jar   
                  
  cp -f ${source_base_dir}/project.xml ${target_base_dir}/project_constraintsTest.xml                  
  cp -f ${source_base_dir}/resources.xml ${target_base_dir}/resources_constraintsTest.xml
  
  cp -f ${source_base_dir}/execution ${target_base_dir}/execution
  cp -f ${source_base_dir}/result_constraintsTest ${target_base_dir}/result_constraintsTest
  cp -f ${source_base_dir}/result_dynamicTest ${target_base_dir}/result_dynamicTest
