#!/bin/bash

  # Get parameters
  vm_user=$1
  vm_ip=$2

  echo "- Cleaning VM before snapshot"

  #---------------------------------------------------------------------------------------------------------------------
  # Clean hosts insertion
  ssh -t -t -o StrictHostKeyChecking=no -o BatchMode=yes -o ChallengeResponseAuthentication=no ${vm_user}@${vm_ip} "sudo sh /home/${vm_user}/tests/configure_hosts_remove"

  #---------------------------------------------------------------------------------------------------------------------
  # Clean deployed files
  ssh -t -t -o StrictHostKeyChecking=no -o BatchMode=yes -o ChallengeResponseAuthentication=no ${vm_user}@${vm_ip} "rm -f /home/${vm_user}/*.sh"
  ssh -t -t -o StrictHostKeyChecking=no -o BatchMode=yes -o ChallengeResponseAuthentication=no ${vm_user}@${vm_ip} "rm -f /home/${vm_user}/compss.tar.gz"
  ssh -t -t -o StrictHostKeyChecking=no -o BatchMode=yes -o ChallengeResponseAuthentication=no ${vm_user}@${vm_ip} "rm -rf /home/${vm_user}/tmpTrunk/"
  ssh -t -t -o StrictHostKeyChecking=no -o BatchMode=yes -o ChallengeResponseAuthentication=no ${vm_user}@${vm_ip} "rm -rf /home/${vm_user}/tests/"

  #---------------------------------------------------------------------------------------------------------------------
  # Clean possible remaining test files
  ssh -t -t -o StrictHostKeyChecking=no -o BatchMode=yes -o ChallengeResponseAuthentication=no ${vm_user}@${vm_ip} "ps -elfa | grep java | grep integratedtoolkit.nio.worker.NIOWorker | awk {' print $4 '} | xargs -r kill -9"
  ssh -t -t -o StrictHostKeyChecking=no -o BatchMode=yes -o ChallengeResponseAuthentication=no ${vm_user}@${vm_ip} "rm -f /home/${vm_user}/hs_err_pid*"
  ssh -t -t -o StrictHostKeyChecking=no -o BatchMode=yes -o ChallengeResponseAuthentication=no ${vm_user}@${vm_ip} "rm -rf /home/${vm_user}/.COMPSs/"

  #---------------------------------------------------------------------------------------------------------------------
  # Clean maven repository
  ssh -t -t -o StrictHostKeyChecking=no -o BatchMode=yes -o ChallengeResponseAuthentication=no ${vm_user}@${vm_ip} "rm -rf /home/${vm_user}/.m2/"


  #---------------------------------------------------------------------------------------------------------------------
  # Clean VM
  ssh -t -t -o StrictHostKeyChecking=no -o BatchMode=yes -o ChallengeResponseAuthentication=no ${vm_user}@${vm_ip} "rm -f /home/${vm_user}/.bash_history"
  ssh -t -t -o StrictHostKeyChecking=no -o BatchMode=yes -o ChallengeResponseAuthentication=no ${vm_user}@${vm_ip} "sudo rm -f /home/${vm_user}/.ssh/known_hosts"


  # All process OK. Exit
  echo "- Cleaning DONE"
  exit 0

