#!/bin/bash

  #Obtain parameters
  COMPSs_exec=$1
  comm=$2
  base_app_dir=$3
  COMPSs_log_folder=$4
  target_log_folder=$5
  retryNum=$6
  
  #Global exit variable
  exitValue=0
  
  #----------------------------------------------------------------------------------
  #Generate Project.xml according to system
  sed -i '/<InstallDir>/c<InstallDir>'${IT_HOME}'<\/InstallDir>' ${base_app_dir}/project_servicesTest.xml
  
  #----------------------------------------------------------------------------------
  #Create all working dir folders
  mkdir -p /tmp/COMPSsWorker01/
  
  #----------------------------------------------------------------------------------
  #Run application 1 - Basic Types
  echo
  echo "*** RUNNING JAVA APPLICATION SERVICES"
  #Start tomcat and services
  java -jar ${base_app_dir}/groupService.jar &
  groupServicePID=$!
  sleep 15s
  
  output_log="${target_log_folder}/servicesTest_0${retryNum}.outputlog"
  error_log="${target_log_folder}/servicesTest_0${retryNum}.errorlog"
  expectedTime=60s
  numCalls=4
  
  timeout --signal=2 $expectedTime ${COMPSs_exec} \
     --project=${base_app_dir}/project_servicesTest.xml \
     --resources=${base_app_dir}/resources_servicesTest.xml \
     --debug \
     --lang=java \
     --comm=$comm \
     --classpath=${base_app_dir}/servicesTest.jar \
     servicesTest.ServicesTest $numCalls > >(tee ${output_log}) 2> >(tee ${error_log} >&2)
  
  #Check timeout
  if [[ "$?" = "124" ]]; then
     #Shutdown tomcat and services
     kill $groupServicePID
     
     #Copy LOG files
     cp -rf ${COMPSs_log_folder}/servicesTest.ServicesTest_0${retryNum}/* ${target_log_folder}
     
     #Report time out
     echo "[WARNING] Java Application timed out" >> ${output_log}
     exitValue=124
  else
     #Shutdown tomcat and services
     kill $groupServicePID
     
     #Copy LOG files
     cp -rf ${COMPSs_log_folder}/servicesTest.ServicesTest_0${retryNum}/* ${target_log_folder}
  
     #Check result
     ${base_app_dir}/result ${output_log} ${target_log_folder}
     exitValue=$?
  fi
  
  
  #----------------------------------------------------------------------------------
  #Return execution status
  exit $exitValue
  
