#!/bin/bash

  # Obtain parameters
  COMPSs_exec=$1
  comm=$2
  runcompss_opts=$3
  base_app_dir=$4
  COMPSs_log_folder=$5
  target_log_folder=$6
  retry_num=$7
  execution_envs=$8
  modules=$9
  master_working_dir=${10}
  worker_working_dir=${11}
  
  # Global variables
  exit_value=1
  jar_name="0_simple_java_mn.jar"
  app_name="simple.Simple"
  
  #----------------------------------------------------------------------------------

  #----------------------------------------------------------------------------------
  # Create all working dir folders
  mkdir -p /tmp/COMPSsWorker01/

  module load ${modules}
  
  #----------------------------------------------------------------------------------
  # Run application
  echo
  echo "*** RUNNING JAVA APPLICATION SIMPLE"
  output_log="${target_log_folder}/simple_0${retry_num}.outputlog"
  error_log="${target_log_folder}/simple_0${retry_num}.errorlog"
  expectedTime=5
  
  # shellcheck disable=SC2086
    #module load ${modules}

   "${COMPSs_exec}" --exec_time=${expectedTime} \
     --num_nodes=2 \
     --comm="$comm" \
     --master_working_dir=${master_working_dir} \
     --worker_working_dir=${worker_working_dir} \
     --base_log_dir=${target_log_folder} \
     --debug \
     --qos=debug \
     --summary \
     ${runcompss_opts} \
     \
     --classpath="${base_app_dir}/${jar_name}" \
     \
     "${app_name}" 1 > >(tee "${output_log}") 2> >(tee "${error_log}" >&2)
  
  # Check timeout
 	
     # Copy LOG files
     #cp -rf "${COMPSs_log_folder}/${app_name}_0${retry_num}"/* "${target_log_folder}"
     #echo ${base_app_dir}
  
     # Check result
     #"${base_app_dir}"/result "${output_log}" "${error_log}" "${target_log_folder}"
     #exit_value=$?
  
  
  #----------------------------------------------------------------------------------
  # Return execution status
  exit ${exit_value}
