#!/bin/bash -e
  
  #Obtain parameter
  source_base_dir=$1
  target_base_dir=$2
  
  #Copy files
  cp -f ${source_base_dir}/target/31-graph.jar ${target_base_dir}/graph.jar    
                 
  cp -f ${source_base_dir}/project.xml ${target_base_dir}/project.xml                  
  cp -f ${source_base_dir}/resources.xml ${target_base_dir}/resources.xml
  
  cp -f ${source_base_dir}/execution ${target_base_dir}/execution
  cp -f ${source_base_dir}/result ${target_base_dir}/result
 
  # Auxiliar result files 
  cp -f ${source_base_dir}/A.in ${target_base_dir}/java_sparseLU_A.in
  cp -f ${source_base_dir}/A.out ${target_base_dir}/java_sparseLU_A.out
  cp -f ${source_base_dir}/final_graph.dot ${target_base_dir}/final_graph.dot

