#!/bin/bash

  # Obtain parameters
  COMPSs_exec=$1
  comm=$2
  runcompss_opts=$3
  base_app_dir=$4
  COMPSs_log_folder=$5
  target_log_folder=$6
  retryNum=$7
  
  # Global exit variable
  exitValue=0
  
  #----------------------------------------------------------------------------------
  # Generate Project.xml according to system
  sed -i '/<InstallDir>/c<InstallDir>'${IT_HOME}'<\/InstallDir>' ${base_app_dir}/project.xml
  
  #----------------------------------------------------------------------------------
  # Create all working dir folders
  mkdir -p /tmp/COMPSsWorker01/
  
  #----------------------------------------------------------------------------------
  totalExitValue=0
  applications="simpleTests.Barrier simpleTests.Independent simpleTests.IndependentWithSync simpleTests.SingleChain simpleTests.SingleLongChain complexTests.TripleChainNoSync complexTests.TripleChainOneSync complexTests.TripleChainDoubleSync"
  for app in $applications; do
    echo
    echo "*** RUNNING JAVA APPLICATION $app"
    appLogFolder=${target_log_folder}/$app
    mkdir -p ${appLogFolder}
    output_log="${appLogFolder}/$app_0${retryNum}.outputlog"
    error_log="${appLogFolder}/$app_0${retryNum}.errorlog"
    
    expectedTime=60s
    timeout --signal=2 $expectedTime ${COMPSs_exec} \
      --lang=java \
      --classpath=${base_app_dir}/graph.jar \
      -g \
      --debug \
      --comm=$comm \
      ${runcompss_opts} \
      --project=${base_app_dir}/project.xml \
      --resources=${base_app_dir}/resources.xml \
      $app > >(tee ${output_log}) 2> >(tee ${error_log} >&2)
      
    # Check timeout
    if [[ "$?" = "124" ]]; then
      # Copy LOG files
      cp -rf ${COMPSs_log_folder}/${app}_0${retryNum}/* ${appLogFolder}
     
      # Report time out
      echo "[WARNING] Java Application timed out" >> ${output_log}
      exitValue=124
    else
      # Copy LOG files
      cp -rf ${COMPSs_log_folder}/${app}_0${retryNum}/* ${appLogFolder}
    
      # Check result
      ${base_app_dir}/result ${output_log} ${appLogFolder} ${base_app_dir} ${app}
      exitValue=$?
    fi
    
    if [ $exitValue -ne 0 ]; then
      totalExitValue=$exitValue
    fi
  done

  #----------------------------------------------------------------------------------
  # Return execution status
  exit ${totalExitValue}
