#!/bin/bash -e

  #############################################################
  # Name: buildKNL_aux
  # Description: SCRIPT FOR LOCAL COMPSs BUILD in CTE-KNL
  # Parameters: <targetDir> Base Target Installation folder
  #
  # ATTENTION: DO NOT EXECUTE THIS FILE. IT IS AUTOMATICALLY
  #            EXECUTED FROM buildKNL script
  #############################################################

  usage() {
    echo "Incorrect number of parameters"
    echo " Usage: buildKNL_aux <FullTargetPath>"
    echo " "
    exit 1
  }

  ####################
  # MAIN
  ####################
  # Get parameters
  if [ $# -ne 1 ]; then
    usage
  fi

  # SET SCRIPT VARIABLES
  targetDir=$1
  SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

  # DEFINE MODULES
  modules="bsc/current java python/2.7.12-INTEL boost"
  unload_before_python="ignore"
  py2_modules="python/2.7.12-INTEL"
  py3_modules=""
  py3_other_modules="ignore"

  # DEFINE CONFIGURATION PARAMETERS
  additionalExports="export BOOST_CPPFLAGS=-I\${BOOST_INCLUDE} PATH=/usr/include/libxml:$PATH"
  queues_cfg="knl.cfg"
  extrae_with_openmpi="false"
  openmpi_version=""
  extrae_with_impi="true"
  impi_version=""
  autoparallel="false"

  # CALL buildSC_aux
  "${SCRIPT_DIR}"/buildSC_aux "${targetDir}" "${modules}" "${unload_before_python}" "${py2_modules}" "${py3_modules}" "${py3_other_modules}" "${additionalExports}" "${queues_cfg}" "${extrae_with_openmpi}" "${openmpi_version}" "${extrae_with_impi}" "${impi_version}" "${autoparallel}"

  # END
  exit 0
