#!/bin/bash -e

  #############################################################
  # Name: buildKNL_aux
  # Description: SCRIPT FOR LOCAL COMPSs BUILD in CTE-KNL
  # Parameters: <targetDir> Base Target Installation folder
  #
  # ATTENTION: DO NOT EXECUTE THIS FILE. IT IS AUTOMATICALLY
  #            EXECUTED FROM buildKNL script
  #############################################################

  usage() {
    echo "Incorrect number of parameters"
    echo " Usage: buildKNL_aux <FullTargetPath>"
    echo " "
    exit 1
  }

  ####################
  # MAIN
  ####################
  # Get parameters
  if [ $# -ne 1 ]; then
    usage
  fi

  # SET SCRIPT VARIABLES
  targetDir=$1
  scriptDir=$(dirname $0)

  modules="bsc/current java boost"
  py2_modules="python/2.7.12-INTEL"
  py3_modules=""
  additionalExports="export BOOST_CPPFLAGS=-I\${BOOST_INCLUDE} PATH=/usr/include/libxml:$PATH"
  queues_cfg="knl.cfg"
  extrae_with_openmpi="false"
  openmpi_version=""
  extrae_with_impi="true"
  impi_version=""

  ${scriptDir}/buildSC_aux ${targetDir} "${modules}" "${py2_modules}" "${py3_modules}" "${additionalExports}" "${queues_cfg}" "${extrae_with_openmpi}" "${openmpi_version}" "${extrae_with_impi}" "${impi_version}"
