#!/bin/bash -e 
 
  #############################################################
  # Name: buildKNL
  # Description: SCRIPT FOR CTE-KNL COMPSs BUILD
  # Parameters: <KNL_user> CTE-KNL user account. Preferable with ssh keys inserted
  #             <FullTmpPath> Tmp path on CTE-KNL for deployment
  #             <FullTargetPath> Base Target Installation folder on CTE-KNL
  #############################################################

  ####################
  # FUNCTIONS
  ####################
  usage() {
    echo " Usage: buildKNL <KNL_user> <FullTmpPath> <FullTargetPath>"
    echo " "
  }


  ####################
  # MAIN
  ####################
  # Get parameters
  if [ $# -eq 1 ]; then
    if [ "$1" == "usage" ]; then
      usage
      exit 0
    fi
  fi
  if [ $# -ne 3 ]; then
    echo "Incorrect number of parameters"
    usage
    exit 1
  fi

  # SET SCRIPT VARIABLES
  scriptDir=$(pwd)/$(dirname $0)

  KNLuser=$1
  KNLtmpDir=$2
  KNLtargetDir=$3
  KNLloginNode=klogin1.bsc.es
  KNLauxScript=${scriptDir}/buildKNL_aux
  PRELOAD_ENV=""

  # Perform installation
  cd ${scriptDir}/../commons
  ./buildSC ${KNLuser} ${KNLloginNode} ${KNLtmpDir} ${KNLtargetDir} ${KNLauxScript} "${PRELOAD_ENV}"
  exitStatus=$?
  cd ${scriptDir}

  # END
  exit $exitStatus

