#!/bin/bash

  # Obtain parameters
  COMPSs_exec=$1
  comm=$2
  runcompss_opts=$3
  base_app_dir=$4
  COMPSs_log_folder=$5
  target_log_folder=$6
  retry_num=$7
  execution_envs=$8
  modules=$9
  master_working_dir=${10}
  worker_working_dir=${11}

  # Global variables
  exit_value=1
  app_name="simple.py"

  #--------------------------------------------------------------------------------


  #----------------------------------------------------------------------------------
  # Create all working dir folders
  mkdir -p /tmp/COMPSsWorker01/

  #----------------------------------------------------------------------------------
  # Run application
  echo
  echo "*** RUNNING PYTHON APPLICATION SIMPLE"

  for python_interpreter in ${execution_envs}; do
    echo "   - Running with Interpreter: ${python_interpreter}"
    output_log="${target_log_folder}/${app_name}_${python_interpreter}_0${retry_num}.outputlog"
    error_log="${target_log_folder}/${app_name}_${python_interpreter}_0${retry_num}.errorlog"
    specific_log_dir="${COMPSs_log_folder}/${app_name}_${python_interpreter}_0${retry_num}"
    exec_target_log_folder="${target_log_folder}/${app_name}_${python_interpreter}_0${retry_num}"
    mkdir -p "${exec_target_log_folder}"
    expectedTime=5

    python_mpi_worker=""
    if [ "$python_interpreter" == 'python2_mpi' ]; then
        python_interpreter="python2"
        python_mpi_worker="--python_mpi_worker=true"
    fi
    if [ "$python_interpreter" == 'python3_mpi' ]; then
        python_interpreter="python3"
        python_mpi_worker="--python_mpi_worker=true"
    fi
    if [ "$python_interpreter" == 'python3' ]; then
        export COMPSS_PYTHON_VERSION=3-ML
    fi
    module load ${modules}

    # shellcheck disable=SC2086
    "${COMPSs_exec}" --exec_time=${expectedTime} \
      --num_nodes=2 \
      --comm="$comm" \
      --master_working_dir=${master_working_dir} \
      --worker_working_dir=${worker_working_dir} \
      --base_log_dir=${target_log_folder} \
      --debug \
      --summary \
      --qos=debug \
      \
      --debug \
      ${runcompss_opts} \
      \
      --lang=python \
      --python_interpreter="${python_interpreter}" \
      ${python_mpi_worker} \
      --pythonpath="${base_app_dir}" \
      --specific_log_dir="${specific_log_dir}" \
      \
      "${base_app_dir}/src/${app_name}" > >(tee "${output_log}") 2> >(tee "${error_log}" >&2)


  done

  #----------------------------------------------------------------------------------
  # Return execution status
  exit ${exit_value}
