#!/bin/bash -e

platforms="linux/amd64,linux/arm64"
images="minimal pycompss compss compss-tutorial"

while getopts :v:p: OPTION
do
  case ${OPTION} in
    v) version=${OPTARG} ;;
    p) platforms=${OPTARG} ;;
    *) echo "Usage: ${BASH_SOURCE[0]} -v version [<Platforms> -p ${platforms}] [<Images> ${images}]" ; exit 1 ;;
  esac
done
shift $((OPTIND - 1)) && images=${*-${images}}
[ -z "${version}" ] && echo "You must define a version with the flag -v" && exit 1

echo "- Platforms: ${platforms}"
echo "- Images: ${images}"
echo "- Version: ${version}"

cd -- "$(dirname -- "${BASH_SOURCE[0]}")"/../..

read -rp 'Do you want to push images? [Yes/NO] ' answer
[[ "${answer}" =~ ^[Yy](es)?$ ]] && docker login -u compss $(test -t 0 || echo "--password-stdin") \
                                 && echo "Images will be pushed to Docker Hub" && push=--push \
                                 || echo "Images won't be pushed to Docker Hub"

cache=--no-cache
for image in ${images}
do
  echo "Building image compss/${image}:${version}"
  docker build ${cache} ${push} --platform ${platforms} --target ${image} \
               -t compss/${image}:${version} .
  cache=
done
