#!/bin/bash -e

  #Obtain parameter
  source_base_dir=$1
  target_base_dir=$2

  #Copy files
  cp -f ${source_base_dir}/execution ${target_base_dir}/execution
  cp -f ${source_base_dir}/result ${target_base_dir}/result

  cp -rf ${source_base_dir}/src ${target_base_dir}/src

  cp -f ${source_base_dir}/project.xml ${target_base_dir}/project.xml
  cp -f ${source_base_dir}/resources.xml ${target_base_dir}/resources.xml

  #cp -f ${source_base_dir}/skip ${target_base_dir}/skip
