#!/bin/ksh
#

ifort -traceback -assume byterecl -O3 -fp-model precise -fp-stack-check -convert big_endian -mcmodel=large -shared-intel -c module_flt.f90
ifort -traceback -assume byterecl -O3 -fp-model precise -fp-stack-check -convert big_endian -mcmodel=large -shared-intel -c allprep_rrtm.f

ifort -traceback -assume byterecl -O3 -fp-model precise -fp-stack-check -convert big_endian -mcmodel=large -shared-intel -o allprep_rrtm.x allprep_rrtm.o module_flt.o 

echo Started.

./allprep_rrtm.x

echo Finished.
rm *.o
rm *.x
rm *.mod

exit
