#!/bin/bash -e
  
  #Obtain parameter
  source_base_dir=$1
  target_base_dir=$2
  
  #Copy files
  cp -f ${source_base_dir}/target/06-sharedDisks.jar ${target_base_dir}/sharedDisks.jar      
               
  cp -f ${source_base_dir}/project.xml ${target_base_dir}/project_sharedDisks.xml                  
  cp -f ${source_base_dir}/resources.xml ${target_base_dir}/resources_sharedDisks.xml
  
  cp -f ${source_base_dir}/execution ${target_base_dir}/execution
  cp -f ${source_base_dir}/result ${target_base_dir}/result
  