#!/bin/bash

  # Obtain parameters
  COMPSs_exec=$1
  comm=$2
  runcompss_opts=$3
  base_app_dir=$4
  target_log_folder=$5
  compss_module=$6
  execution_envs=$7


  # Global variables
  jar_name="0_simple_java_sc.jar"
  app_name="simple.Simple"

  #----------------------------------------------------------------------------------

  #----------------------------------------------------------------------------------
  # Load COMPSs module + application

  module load ${compss_mode}


  # module load xxx

  #----------------------------------------------------------------------------------
  # Run application
  echo
  echo "*** RUNNING JAVA APPLICATION SIMPLE"
  for exec_env in ${execution_envs}; do
    echo "   - Running with Environment: ${exec_env}"
    output_log="${target_log_folder}/${app_name}_${exec_env}_0.outputlog"
    error_log="${target_log_folder}/${app_name}_${exec_env}_0.errorlog"
    specific_log_dir="${target_log_folder}/${app_name}_${exec_env}_0"
    mkdir -p "${specific_log_dir}"

    master_working_dir=${target_log_folder}
    if [ "$exec_env" == 'gpfs' ]; then
        worker_working_dir=${specific_log_dir}
    fi
    if [ "$exec_env" == 'scratch' ]; then
        worker_working_dir="scratch"
    fi

    # shellcheck disable=SC2086
    module load ${compss_module}

    "${COMPSs_exec}" --exec_time=${expectedTime} \
      --num_nodes=2 \
      --comm="$comm" \
      --master_working_dir=${master_working_dir} \
      --worker_working_dir=${worker_working_dir} \
      --base_log_dir=${target_log_folder} \
      --debug \
      --qos=debug \
      --summary \
      ${runcompss_opts} \
      \
      --classpath="${base_app_dir}/${jar_name}" \
      \
      "${app_name}" 1 > >(tee "${output_log}") 2> >(tee "${error_log}" >&2)

     # Check timeout

     # Copy LOG files
     #cp -rf "${COMPSs_log_folder}/${app_name}_0${retry_num}"/* "${target_log_folder}"
     #echo ${base_app_dir}

     # Check result
     #"${base_app_dir}"/result "${output_log}" "${error_log}" "${target_log_folder}"
     #exit_value=$?
  done
