#!/bin/bash -e

  COMPSs_version=3.4.post2608

  echo " "
  echo "# Building COMPSs packages..."
  echo " "
  cd specs

  cd sc
  echo " "
  echo " * Building SC packages..."
  echo " "
  ./buildsc ${COMPSs_version}
  cd ..

  echo " "
  echo " * Finished"
  echo " "
  cd ..

