#!/bin/bash -e

  # Define directories
  SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
  SCS_BASE_DIR=${SCRIPT_DIR}/scs/

  # Define remote parameters
  SCuser=compss
  SCtmp=/home/bsc19/compss/tmpCOMPSs/
  SCtarget=/apps/COMPSs/Trunk

  # Install on each enabled supercomputer
  ENABLED_SCS=("asgard" "jureca" "knl" "mn" "mt" "nord" "ssf" "uv")
  SCS_SCRIPT_NAMES=("buildAsgard" "buildJureca" "buildKNL" "buildMN" "buildMT" "buildNord" "buildSSF" "buildUV")

  echo "Installing COMPSs at SCs"

  for i in "${!ENABLED_SCS[@]}"; do
    SCName="${ENABLED_SCS[$i]}"
    SCscript="${SCS_SCRIPT_NAMES[$i]}"

    echo "-- Installing COMPSs at $SCName SuperComputer"
    cd "${SCS_BASE_DIR}"/"$SCName"
    ./"${SCscript}" "$SCuser" "$SCtmp" "$SCtarget"
    cd "${SCRIPT_DIR}"
    echo "-- COMPSs at $SCName Installed!"
  done

  # DONE
  echo "COMPSs Successfully installed in all SuperComputers"
  exit 0

