#!/bin/bash -e
 
  COMPSs_version=3.0.rc2208
 
  echo " "
  echo "# Building COMPSs packages..."
  echo " "
  cd specs 

  cd sc
  echo " "
  echo " * Building SC packages..."
  echo " "
  ./buildsc ${COMPSs_version}
  cd ..

  echo " "
  echo " * Finished"
  echo " "
  cd ..

