#!/bin/bash -e 
 
  #############################################################
  # Name: buildMN
  # Description: SCRIPT FOR MareNostrum COMPSs BUILD
  # Parameters: <MN_user> MareNostrum user account. Preferable with ssh keys inserted
  #             <FullTmpPath> Tmp path on MareNostrum for deployment
  #             <FullTargetPath> Base Target Installation folder on MareNostrum
  #############################################################

  ####################
  # FUNCTIONS
  ####################
  usage() {
    echo " Usage: buildMN <MN_user> <FullTmpPath> <FullTargetPath>"
    echo " "
  }


  ####################
  # MAIN
  ####################
  # Get parameters
  if [ $# -eq 1 ]; then
    if [ "$1" == "usage" ]; then
      usage
      exit 0
    fi
  fi
  if [ $# -ne 3 ]; then
    echo "Incorrect number of parameters"
    usage
    exit 1
  fi

  # SET SCRIPT VARIABLES
  MNuser=$1
  MNtmpDir=$2
  MNtargetDir=$3
  scriptDir=$(pwd)/$(dirname $0)
  sourcesDir=$(pwd)/$(dirname $0)/..
  tmpDir=${scriptDir}/tmp
  MNloginNode=mn1.bsc.es

  echo "- MN user       = ${MNuser}"
  echo "- MN login node = ${MNloginNode}"
  echo "- MN tmp Dir    = ${MNtmpDir}"
  echo "- MN target Dir = ${MNtargetDir}"
  echo "- Script Dir    = ${scriptDir}"
  echo "- Sources Dir   = ${sourcesDir}"
  echo "- Local tmp Dir = ${tmpDir}"
  sleep 5

  echo "- Compile sources"
  cd ${sourcesDir}/compss/
  mvn -U clean package
  cd ${scriptDir}

  # COPY TRUNK
  echo "- Copy trunk to tmpdir"
  rm -rf ${tmpDir}
  mkdir -p ${tmpDir}
  cp ${sourcesDir}/changelog ${tmpDir}
  cp -r ${sourcesDir}/compss ${tmpDir}
  cp -r ${sourcesDir}/dependencies ${tmpDir}
  cp -r ${sourcesDir}/doc ${tmpDir}
  cp -r ${sourcesDir}/files ${tmpDir}
  cp ${sourcesDir}/LICENSE ${tmpDir}
  cp ${sourcesDir}/NOTICE ${tmpDir}
  cp ${sourcesDir}/pom.xml ${tmpDir}
  cp ${sourcesDir}/README ${tmpDir}
  cp ${sourcesDir}/RELEASE_NOTES ${tmpDir}
  find . -name .svn | xargs rm -rf  #Cleans svn files

  # CLEAN TRUNK COMPILATION
  echo "- Clean sources"
  cd ${sourcesDir}/compss/
  mvn -U clean
  cd ${scriptDir}

  # COMPSs Monitor APACHE
  echo "- Downloading Apache for COMSPs Monitor"
  cd ${tmpDir}
  TOMCAT_VER="7.0.65"
  TOMCAT_URL="http://compss.bsc.es/repo/apache-tomcat/apache-tomcat-7.0.65.tar.gz"
  wget ${TOMCAT_URL}
  mv apache-tomcat-${TOMCAT_VER}.tar.gz apache-tomcat.tar.gz
  cd ${scriptDir}

  # DEPLOY ON TMP MN
  echo "- Deploy files to tmpDir in MN"
  ssh -t -t -o StrictHostKeyChecking=no -o BatchMode=yes -o ChallengeResponseAuthentication=no ${MNuser}@${MNloginNode} "rm -rf ${MNtmpDir}; mkdir -p ${MNtmpDir}"
  scp -r -q -o StrictHostKeyChecking=no ${tmpDir} ${MNuser}@${MNloginNode}:${MNtmpDir}
  scp -r -q -o StrictHostKeyChecking=no ${scriptDir}/buildMN_aux ${MNuser}@${MNloginNode}:${MNtmpDir}

  # Execute deployment aux script
  echo "- Execute installation on MN"
  ssh -t -t -o StrictHostKeyChecking=no -o BatchMode=yes -o ChallengeResponseAuthentication=no ${MNuser}@${MNloginNode} "${MNtmpDir}/buildMN_aux ${MNtargetDir}"

  # ERASE TMP FILES
  echo "- Erase tmp files"
  ssh -t -t -o StrictHostKeyChecking=no -o BatchMode=yes -o ChallengeResponseAuthentication=no ${MNuser}@${MNloginNode} "rm -rf ${MNtmpDir}"
  rm -rf ${tmpDir}

  # END
  echo "Congratulations!"
  echo "COMPSs Runtime Successfully installed!"
  echo " "
  exit 0
