#!/bin/bash

  #Obtain parameters
  COMPSs_exec=$1
  base_app_dir=$2
  COMPSs_log_folder=$3
  target_log_folder=$4
  
  #Global exit variable
  exitValue=0
  
  #----------------------------------------------------------------------------------
  #Generate Project.xml according to system
  sed -i '/<InstallDir>/c<InstallDir>'${IT_HOME}'\/scripts\/system<\/InstallDir>' ${base_app_dir}/project_simple.xml
  
  #----------------------------------------------------------------------------------
  #Run application 1 - Simple
  echo
  echo "*** RUNNING JAVA APPLICATION SIMPLE"
  output_log="${target_log_folder}/simple.outputlog"
  error_log="${target_log_folder}/simple.errorlog"
  expectedTime=60s
  
  timeout --signal=2 $expectedTime ${COMPSs_exec} \
     --app=simple.Simple \
     --project=${base_app_dir}/project_simple.xml \
     --resources=${base_app_dir}/resources_simple.xml \
     --lang=java \
     --cline_args="1" \
     --classpath=${base_app_dir}/simple.jar > >(tee ${output_log}) 2> >(tee ${error_log} >&2)
  
  
  #Check timeout
  if [[ "$?" = "124" ]]; then
     #Copy LOG files
     cp -rf ${COMPSs_log_folder}/simple.Simple_01/* ${target_log_folder}
       
     #Report time out
     echo "[WARNING] Java Application timed out" >> ${output_log}
     exitValue=124
  else
     #Copy LOG files
     cp -rf ${COMPSs_log_folder}/simple.Simple_01/* ${target_log_folder}
  
     #Check result
     ${base_app_dir}/result ${output_log} ${target_log_folder}
     exitValue=$?
  fi
  
  
  #----------------------------------------------------------------------------------
  #Return execution status
  exit $exitValue
