#!/bin/bash

  #Obtain parameters
  COMPSs_exec=$1
  comm=$2
  base_app_dir=$3
  COMPSs_log_folder=$4
  target_log_folder=$5
  retryNum=$6
  
  #Global exit variable
  exitValue=0
  
  #----------------------------------------------------------------------------------
  #Generate Project.xml according to system
  sed -i '/<InstallDir>/c<InstallDir>'${IT_HOME}'<\/InstallDir>' ${base_app_dir}/project.xml
  
  #----------------------------------------------------------------------------------
  #Create all working dir folders
  mkdir -p /tmp/COMPSsWorker01/
  
  #----------------------------------------------------------------------------------
  # Binaries paths
  helloWorldOMPSS="${base_app_dir}/bin/helloWorldOMPSS"
  export HELLO_WORLD_OMPSS=${helloWorldOMPSS}
  
  #----------------------------------------------------------------------------------
  # Run application 47 - OmpSs
  echo
  echo "*** RUNNING JAVA APPLICATION OMPSS"
  
  echo "OmpSs Binary: ${HELLO_WORLD_OMPSS}"
  
  output_log="${target_log_folder}/ompss_0${retryNum}.outputlog"
  error_log="${target_log_folder}/ompss_0${retryNum}.errorlog"
  expectedTime=60s
  
  timeout --signal=2 $expectedTime ${COMPSs_exec} \
     --project=${base_app_dir}/project.xml \
     --resources=${base_app_dir}/resources.xml \
     --debug \
     --lang=java \
     --comm=$comm \
     --classpath=${base_app_dir}/ompss.jar \
     testOMPSS.Main > >(tee ${output_log}) 2> >(tee ${error_log} >&2)
  
  
  #Check timeout
  if [[ "$?" = "124" ]]; then
     #Copy LOG files
     cp -rf ${COMPSs_log_folder}/testOMPSS.Main_0${retryNum}/* ${target_log_folder}
     
     #Report time out
     echo "[WARNING] Java Application timed out" >> ${output_log}
     exitValue=124
  else
     #Copy LOG files
     cp -rf ${COMPSs_log_folder}/testOMPSS.Main_0${retryNum}/* ${target_log_folder}
  
     #Check result
     ${base_app_dir}/result ${output_log} ${target_log_folder}
     exitValue=$?
  fi
  
  
  #----------------------------------------------------------------------------------
  #Return execution status
  exit $exitValue
