#!/bin/bash -e
  
  # Obtain parameter
  source_base_dir=$1
  target_base_dir=$2

  # Compile and deploy MPI
  mpiCC -o ${target_base_dir}/increment.mpi ${source_base_dir}/src/main/c/increment.c  

  # Copy files
  cp -f ${source_base_dir}/target/57-multiImplementations.jar ${target_base_dir}/multiImplementations.jar
  cp -f ${source_base_dir}/src/main/binary/increment.sh ${target_base_dir}
 
  cp -f ${source_base_dir}/project.xml ${target_base_dir}/project.xml                  
  cp -f ${source_base_dir}/resources.xml ${target_base_dir}/resources.xml
  
  cp -f ${source_base_dir}/execution ${target_base_dir}/execution
  cp -f ${source_base_dir}/result ${target_base_dir}/result

