#!/bin/bash -e

  # This script is intended to be called by the buildpackages script
  # However, it can be invoked alone and still function properly
  # An example usage would be ./buildpip 2.0
  # It needs as a command line argument with the version of the target distributable
  # The version should be valid and a COMPSS_${COMPSS_VERSION}.tar.gz file must
  # exist in the specified repository in pyCOMPSsHeadlessResources/url file

  # Define script variables
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

  # Retrieve script parameters
  if [ $# -ne 1 ]; then
    echo "[ERROR] Invalid usage"
    echo "  Usage: $0 <COMPSs_VERSION>"
    exit 1
  fi
  COMPSS_VERSION=$1

  # Add the version number as a resource
  echo "$COMPSS_VERSION" > pyCOMPSsHeadlessResources/VERSION.txt

  # Create distributable folder
  mkdir -p pyCOMPSsHeadless

  # Copy scripts and other files into the pyCOMPSs directory
  # Please, resist the temptation to replace all these lines by
  # cp -rf pyCOMPSsHeadlessResources/* pyCOMPSsHeadless/ or something equivalent
  # It may be possible that not all of the files in that folder are
  # necessary or even appropriate for the installation
  cp -r pyCOMPSsHeadlessResources/pycompss-headless pyCOMPSsHeadless/
  cp pyCOMPSsHeadlessResources/LICENSE.txt pyCOMPSsHeadless/
  cp pyCOMPSsHeadlessResources/MANIFEST.in pyCOMPSsHeadless/
    cp pyCOMPSsHeadlessResources/README.rst pyCOMPSsHeadless/
  cp pyCOMPSsHeadlessResources/VERSION.txt pyCOMPSsHeadless/
  cp pyCOMPSsHeadlessResources/requirements.txt pyCOMPSsHeadless/
  cp pyCOMPSsHeadlessResources/setup.py pyCOMPSsHeadless/

  # Change permissions. This will avoid issues with, for example, python's subprocess.call
  cd pyCOMPSsHeadless
  chmod -R 777 *
  # Create the tar.gz distributable
  # This should leave a .tar.gz in pyCOMPSsHeadless/dist
  python setup.py sdist
  cd "${SCRIPT_DIR}"

  # Finally, move the pyCOMPSsHeadless distributable to packages/pip (tgz included)
  # Delete previous versions (if any)
  rm -rf ../../packages/pip-headless
  mkdir -p ../../packages/pip-headless
  # Change permissions
  chmod -R 777 pyCOMPSsHeadless
  # Move it to its final destination
  mv pyCOMPSsHeadless ../../packages/pip-headless/
