#!/bin/bash

  #############################################################
  # Name: buildLenox_aux
  # Description: SCRIPT FOR LOCAL COMPSs BUILD in LENOX
  # Parameters: <targetDir>           Base Target Installation folder
  #
  # ATTENTION: DO NOT EXECUTE THIS FILE. IT IS AUTOMATICALLY
  #            EXECUTED FROM buildLenox script
  #############################################################

  usage() {
    echo "Incorrect number of parameters"
    echo " Usage: buildLenox_aux <FullTargetPath>"
    echo " "
    exit 1
  }

  ####################
  # MAIN
  ####################
  # Get parameters
  if [ $# -ne 1 ]; then
    usage
  fi

  # SET SCRIPT VARIABLES
  targetDir=$1
  SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

  # DEFINE MODULES
  modules="eb-env GCCcore/12.3.0 binutils/2.40 Prefix/Production ear"
  # "base-env hpcx/2.6.0/gcc boost/1.70.0/intel java/1.8.0_181 papi/5.7.0"
  unload_before_python="ignore"
  # Plain python modules:
  run_before_py3_modules="ignore"
  py3_modules="Python/3.11.3"
  run_before_py3_other_modules="ignore"
  py3_other_modules="" #"python/3.8.11 python/3.9.7"  # python/3.10.0 fails due to missing setuptools

  # DEFINE CONFIGURATION PARAMETERS
  #(Environment vars must be scaped to get the correct value if not it could take a value previous to load the modules)
  additionalExports=""

  additional_module_use_folder="/hpc/base/EAR/production/x86_64-RedHat-9/etc/module/"
  queues_cfg="lenox.cfg"
  extrae_with_openmpi="false"
  openmpi_version=""
  extrae_with_impi="false"
  impi_version=""
  autoparallel="false"
  c_binding="false"
  extrae_no_mpi="true"
  r_binding="false"

  # CALL buildSC_aux
  "${SCRIPT_DIR}"/buildSC_aux "${targetDir}" "${modules}" "${unload_before_python}" "${run_before_py3_modules}" "${py3_modules}" "${run_before_py3_other_modules}" "${py3_other_modules}" "${additionalExports}" "${additional_module_use_folder}" "${queues_cfg}" "${extrae_with_openmpi}" "${openmpi_version}" "${extrae_with_impi}" "${impi_version}" "${autoparallel}" "${c_binding}" "${extrae_no_mpi}" "${r_binding}"
  ev=$?

  # End
  if [ $ev -ne 0 ]; then
    echo "ERROR: Exception in auxiliar script"
    exit $ev
  fi
  exit 0
