#!/bin/bash

  #############################################################
  # Name: buildMN_aux
  # Description: SCRIPT FOR LOCAL COMPSs BUILD in MareNostrum
  # Parameters: <targetDir>           Base Target Installation folder
  #
  # ATTENTION: DO NOT EXECUTE THIS FILE. IT IS AUTOMATICALLY
  #            EXECUTED FROM buildMN script
  #############################################################

  usage() {
    echo "Incorrect number of parameters"
    echo " Usage: buildMN5_aux <FullTargetPath>"
    echo " "
    exit 1
  }

  ####################
  # MAIN
  ####################
  # Get parameters
  if [ $# -ne 1 ]; then
    usage
  fi

  # SET SCRIPT VARIABLES
  targetDir=$1
  SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

  # DEFINE MODULES
  modules="intel/2023.2.0 impi/2021.10.0 mkl/2023.2.0 oneapi/2023.2.0 boost/1.75.0 hdf5 java-openjdk/11.0.18+10 ear-tools/ear-lite/5.0 papi/7.1.0-gcc R/4.3.2"
  unload_before_python=""
  # Plain python modules:
  run_before_py3_modules="ignore"
  py3_modules="python/3.12.1"
  run_before_py3_other_modules=""
  py3_other_modules="python/3.8.18 python/3.9.16 miniforge/24.3.0-0 anaconda/2023.07"
  # miniforge has python 3.10 used as replacement of python/3.10.15 which does not have wheel
  # anaconda has python 3.11 and has jupyter

  # DEFINE CONFIGURATION PARAMETERS
  # (Environment vars must be scaped to get the correct value if not it could take a value previous to load the modules)
  additionalExports='export CFLAGS="-I/usr/include/libxml2/ $CFLAGS"'

  additional_module_use_folder="ignore"
  queues_cfg="mn5.cfg"
  extrae_with_openmpi="false"
  openmpi_version="/4.1.5"
  extrae_with_impi="true"
  impi_version="/2021.10.0"
  autoparallel="false"
  c_binding="true"
  extrae_no_mpi="true"
  r_binding="true"

  # CALL buildSC_aux
  "${SCRIPT_DIR}"/buildSC_aux "${targetDir}" "${modules}" "${unload_before_python}" "${run_before_py3_modules}" "${py3_modules}" "${run_before_py3_other_modules}" "${py3_other_modules}" "${additionalExports}" "${additional_module_use_folder}" "${queues_cfg}" "${extrae_with_openmpi}" "${openmpi_version}" "${extrae_with_impi}" "${impi_version}" "${autoparallel}" "${c_binding}" "${extrae_no_mpi}" "${r_binding}"
  ev=$?

  # End
  if [ $ev -ne 0 ]; then
    echo "ERROR: Exception in auxiliar script"
    exit $ev
  fi
  exit 0
