#!/bin/bash -e

  action=$1

  if [ "$action" == "remove" ]; then
    # Remove software
    rm -rf /opt/COMPSs/Runtime/connectors
    echo " "
    echo " * COMPSs Runtime Cloud Resources successfully removed"
    echo " "
  elif [ "$action" == "purge" ]; then
    # Purge config files
    rm -rf /opt/COMPSs/Runtime/connectors
    echo " "
    echo " * COMPSs Runtime Cloud Resources successfully purged"
    echo " "
  elif [ "$action" == "upgrade" ]; then
    # Upgrade software
    newversion=$2
    rm -rf /opt/COMPSs/Runtime/connectors
    echo " "
    echo " * COMPSs Runtime Cloud Resources upgraded to $newversion"
    echo " "
  elif [ "$action" == "disappear" ]; then
    # Disappear
    overwriter=$2
    overwriterversion=$3
    rm -rf /opt/COMPSs/Runtime/connectors
    echo " "
    echo " * COMPSs Runtime Cloud Resources diappeared due to $overwriter - $overwriterversion"
    echo "   Please, reinstall COMPSs Runtime Cloud Resources if needed"
    echo " "
  elif [ "$action" == "failed-upgrade" ]; then
    # Revert on failed upgrade
    oldversion=$2
    echo " "
    echo " * COMPSs Runtime Cloud Resources upgrade failed. Reverting to $oldversion"
    echo " "
  elif [ "$action" == "abort-install" ]; then
    if [ $# -eq 1 ]; then
      # Abort generic installation
      echo " "
      echo " * COMPSs Runtime Cloud Resources installation aborted. Please check errors above."
      echo " "
    else
      # Abort reverting to previous version
      oldversion=$2
      echo " "
      echo " * COMPSs Runtime Cloud Resources installation aborted. Please check errors above."
      echo "   Reverting to version $oldversion"
      echo " "
    fi
  elif [ "$action" == "abort-upgrade" ]; then
    # Abort upgrade reverting to previous version
    oldversion=$2
    echo " "
    echo " * COMPSs Runtime Cloud Resources upgrade aborted. Please check errors above."
    echo "   Reverting to version $oldversion"
    echo " "
  fi
