#!/bin/bash -e
  
  #Obtain parameter
  source_base_dir=$1
  target_base_dir=$2
  owner=$3
  
  cp -f ${source_base_dir}/increment.py ${target_base_dir}/increment.py
  
  cp -f ${source_base_dir}/xml/project_cloud_base.xml ${target_base_dir}/project_oneProvider_base.xml
  cp -f ${source_base_dir}/xml/resources_cloud_base.xml ${target_base_dir}/resources_oneProvider_base.xml
                 
  cp -f ${source_base_dir}/execution ${target_base_dir}/execution
  cp -f ${source_base_dir}/result ${target_base_dir}/result
  
  cp -rf ${source_base_dir}/certs ${target_base_dir}

