#!/bin/bash -e
  
  # Obtain parameter
  source_base_dir=$1
  target_base_dir=$2
  
  # Copy files
  cp -f ${source_base_dir}/target/55-schedulerFifoData.jar ${target_base_dir}/schedulerFifoData.jar   
                  
  cp -f ${source_base_dir}/project.xml ${target_base_dir}/project.xml                  
  cp -f ${source_base_dir}/resources.xml ${target_base_dir}/resources.xml
  
  cp -f ${source_base_dir}/execution ${target_base_dir}/execution
  cp -f ${source_base_dir}/result_fifoDataScheduler ${target_base_dir}/result_fifoDataScheduler
  