#!/bin/bash -e
  
  # Obtain parameter
  source_base_dir=$1
  target_base_dir=$2
  
  # Copy files
  app_name="1_annotation_task_groups"

  cp "${source_base_dir}"/target/${app_name}.jar "${target_base_dir}"/${app_name}.jar

  cp "${source_base_dir}"/project.xml "${target_base_dir}"/project.xml
  cp "${source_base_dir}"/resources.xml "${target_base_dir}"/resources.xml

  cp "${source_base_dir}"/execution "${target_base_dir}"/execution
  cp "${source_base_dir}"/result "${target_base_dir}"/result

  # Copy dummy Storage jar
  (
  cd "${source_base_dir}"/../../../../../utils/storage/dummyPSCO/
  mvn clean package
  )
  mkdir -p "${target_base_dir}"/jars/
  cp "${source_base_dir}"/../../../../../utils/storage/dummyPSCO/target/compss-dummyPSCO.jar "${target_base_dir}"/jars/compss-dummyPSCO.jar

  cp "${source_base_dir}"/final_graph.dot "${target_base_dir}"/final_graph.dot
