#!/bin/bash -e
  
  #Obtain parameter
  source_base_dir=$1
  target_base_dir=$2
  
  #Copy files
  cp -f ${source_base_dir}/target/11-dataLocality.jar ${target_base_dir}/dataLocality.jar       
              
  cp -f ${source_base_dir}/projectBasicTest.xml ${target_base_dir}/project_basicTest.xml                  
  cp -f ${source_base_dir}/resourcesBasicTest.xml ${target_base_dir}/resources_basicTest.xml
  cp -f ${source_base_dir}/projectComplexTest.xml ${target_base_dir}/project_complexTest.xml                  
  cp -f ${source_base_dir}/resourcesComplexTest.xml ${target_base_dir}/resources_complexTest.xml
  
  cp -f ${source_base_dir}/execution ${target_base_dir}/execution
  cp -f ${source_base_dir}/result_basicTest ${target_base_dir}/result_basicTest
  cp -f ${source_base_dir}/result_complexTest ${target_base_dir}/result_complexTest
  cp -f ${source_base_dir}/result_getAvailableExpected ${target_base_dir}/result_getAvailableExpected
  cp -f ${source_base_dir}/result_getSubmittedGot ${target_base_dir}/result_getSubmittedGot
  