#!/bin/bash -e

  trunk_rel_path=../../../../
  COMPSs_target=$(pwd)/tmp/opt/COMPSs

  # Find JAVA_HOME 
  if [ -z "$JAVA_HOME" ]; then
    echo "Please define \$JAVA_HOME"
    exit 1
  fi

  mkdir -p ${COMPSs_target}/Bindings/c
  cd ${trunk_rel_path}/compss/programming_model/bindings/c
  ./install ${COMPSs_target}/Bindings/c
  cd -
  cp ${trunk_rel_path}/compss/programming_model/bindings/c/buildapp ${COMPSs_target}/Bindings/c/

