#!/bin/bash -e
  
  # Obtain parameter
  source_base_dir=$1
  target_base_dir=$2
  
  # Copy files
  cp "${source_base_dir}"/target/17-sparseLU.jar "${target_base_dir}"/sparseLU.jar

  cp "${source_base_dir}"/project.xml "${target_base_dir}"/project.xml
  cp "${source_base_dir}"/resources.xml "${target_base_dir}"/resources.xml
  
  cp "${source_base_dir}"/execution "${target_base_dir}"/execution
  cp "${source_base_dir}"/result_arrays "${target_base_dir}"/result_arrays
  cp "${source_base_dir}"/result_objects "${target_base_dir}"/result_objects
  cp "${source_base_dir}"/result_files "${target_base_dir}"/result_files
  
  cp "${source_base_dir}"/A.in "${target_base_dir}"/java_sparseLU_A.in
  cp "${source_base_dir}"/A.out "${target_base_dir}"/java_sparseLU_A.out
