#!/bin/bash

  # Obtain parameters
  COMPSs_exec=$1
  comm=$2
  runcompss_opts=$3
  base_app_dir=$4
  COMPSs_log_folder=$5
  target_log_folder=$6
  retry_num=$7
  execution_envs=$8
  
  # Global variables
  AGENT_PIDS=""
  exit_value=0
  NUM_RETRIES="50"
  jar_name="4.1_1_agent_nested_files.jar"
  app_name="4.1_1_agent_nested_files"
  expectedTime="60s"

  # Traps and Handlers
  function kill_agents() {
    for pid in ${AGENT_PIDS}; do
      kill -SIGINT ${pid}
    done
  }
  trap kill_agents EXIT

  function validate_parallel_running_tasks() {
    starts="${1}"
    ends="${2}"
    min_parallel_tasks=${3}
    limit_parallel_tasks=${4}
    
    already_started=0
    max_parallel_tasks=0
    for start in ${starts}; do
      already_started=$((already_started + 1))
      already_ended="0";
      for end in ${ends}; do
        if [ "${end}" -le "${start}" ]; then
          already_ended=$((already_ended + 1))
        fi
      done
      running_tasks=$((already_started - already_ended))
      if [ "${running_tasks}" -gt "${max_parallel_tasks}" ]; then
        max_parallel_tasks=${running_tasks}
      fi
    done
    if [ ${max_parallel_tasks} -lt "${min_parallel_tasks}" ]; then
      echo "Simultaneous tasks not properly managed. Found ${max_parallel_tasks} running in parallel and at least ${min_parallel_tasks} expected."  > >(tee -a "${error_log}")
      exit 1
    fi
    if [ ${max_parallel_tasks} -gt "${limit_parallel_tasks}" ]; then
      echo "Simultaneous tasks not properly managed. Found ${max_parallel_tasks} running in parallel and only ${limit_parallel_tasks} expected."  > >(tee -a "${error_log}")
      exit 1
    fi
  }


  #----------------------------------------------------------------------------------
  # Generate Project.xml according to system
  sed -i '/<InstallDir>/c<InstallDir>'"${COMPSS_HOME}"'<\/InstallDir>' "${base_app_dir}"/project.xml
  
  #----------------------------------------------------------------------------------
  # Create all working dir folders
  mkdir -p /tmp/COMPSsWorker01/
  
  #----------------------------------------------------------------------------------
  # Run application
  echo ""
  echo "*** RUNNING AGENTS TEST: file management for nested compss on different agents"
  log_dir="${COMPSs_log_folder}/${app_name}_0${retry_num}/"
  mkdir -p "${log_dir}"
  output_log="${log_dir}test.outputlog"
  error_log="${log_dir}test.errorlog"
  touch "${output_log}"
  touch "${error_log}"

  # Starting agent
  agent_log_dir="${log_dir}/agent1/"
  mkdir -p "${agent_log_dir}" 
  agent_output_log="${log_dir}agent1.outputlog"
  agent_error_log="${log_dir}agent1.errorlog"

  eval "agent1_log_dir=${agent_log_dir}"
  eval "agent1_output_log=${agent_output_log}"
  eval "agent1_errput_log=${agent_error_log}"

  compss_agent_start_service \
    --num_agents=1 \
    --agent_name_prefix="COMPSsWorker" \
    --classpath="${base_app_dir}/${jar_name}" \
    --log_dir="${agent_log_dir}" \
    --reuse_resources_on_block"=false" \
    -d \
    --exec_time=${expectedTime} \
    ${runcompss_opts} \
    --project="${base_app_dir}/project.xml" \
    --resources="${base_app_dir}/resources.xml" \
    --cei=files.MainItf \
    files.Main

  job1_method=$( grep "\"method_name\"" "${agent1_log_dir}/COMPSsWorker01/jobs/job1_NEW.out" | cut -c 24- | jq -r '.method_name' )
  if [ ! "${job1_method}" == "main" ]; then
    echo "Could not invoke recursive.Count's main method." > >(tee -a "${error_log}")
    exit 1
  fi
  echo  "recursive.Count's main method properly started" > >(tee -a "${output_log}")

  sleep 10s

  created_jobs=$(ls "${agent1_log_dir}COMPSsWorker01/jobs" | grep -c NEW.out)
  if [ ! "${created_jobs}" == "123" ]; then
    echo "Agent1 has executed ${created_jobs} tasks and 123 expected." > >(tee -a "${error_log}")
    exit 1
  fi 
  echo "All task executed as expected and with the expected values." 

  # Copy LOG files
  cp -rf "${COMPSs_log_folder}/${app_name}_0${retry_num}"/* "${target_log_folder}"
  exit_value=0

  #----------------------------------------------------------------------------------
  # Return execution status
  exit ${exit_value}
