#!/bin/bash -e

  trunk_rel_path=../../../../
  COMPSs_target=$(pwd)/tmp/opt/COMPSs

  cp -r ${trunk_rel_path}/dependencies/autoparallel "${COMPSs_target}"/Dependencies/autoparallel
  cp -r ${trunk_rel_path}/dependencies/pluto "${COMPSs_target}"/Dependencies/pluto_install

  find "${COMPSs_target}"/Dependencies -depth -print0 | xargs -0 rm -rf # Clean git files

