#!/bin/bash -e

  #############################################################
  # Name: buildNextgenio_aux
  # Description: SCRIPT FOR LOCAL COMPSs BUILD in Nextgenio
  # Parameters: <targetDir> Base Target Installation folder
  #
  # ATTENTION: DO NOT EXECUTE THIS FILE. IT IS AUTOMATICALLY
  #            EXECUTED FROM buildNextgenio script
  #############################################################

  usage() {
    echo "Incorrect number of parameters"
    echo " Usage: buildNextgenio_aux <FullTargetPath>"
    echo " "
    exit 1
  }

  ####################
  # MAIN
  ####################
  # Get parameters
  if [ $# -ne 1 ]; then
    usage
  fi

  # SET SCRIPT VARIABLES
  targetDir=$1
  SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

  # DEFINE MODULES
  modules="packages-nextgenio intel/19.0.3.199 openmpi/1.10.7-GNU gnu8/8.3.0 boost/1.69.0-GNU papi/5.7.1.0"
  unload_before_python="ignore"
  run_before_py3_modules="ignore"
  py3_modules="python/3.6.0"
  run_before_py3_other_modules="ignore"
  py3_other_modules="ignore"

  # DEFINE CONFIGURATION PARAMETERS
  #(Environment vars must be scaped to get the correct value if not it could take a value previous to load the modules)
  additionalExports="export CPPFLAGS=-I\${BOOST_INC} LDFLAGS=-L\${BOOST_LIB} BOOST_CPPFLAGS=-I\${BOOST_INC} BOOST_HOME=\${BOOST_DIR} JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.262.b10-0.el7_8.x86_64/ MPICC=/home/software/openmpi/1.10.7-GNU/bin/mpicc I_MPI_ROOT="
  # intel module sets I_MPI_ROOT which causes troubles with extrae-openmpi installation - reason why it is unsetted
  additional_module_use_folder="ignore"
  queues_cfg="nextgenio.cfg"
  extrae_with_openmpi="true"
  openmpi_version="/1.10.7-GNU"
  extrae_with_impi="false"    # not used - issues
  impi_version="/2019.3.199"
  autoparallel="false"
  c_binding="true"
  extrae_no_mpi="true"
  r_binding="false"

  # CALL buildSC_aux
  "${SCRIPT_DIR}"/buildSC_aux "${targetDir}" "${modules}" "${unload_before_python}" "${run_before_py3_modules}" "${py3_modules}" "${run_before_py3_other_modules}" "${py3_other_modules}" "${additionalExports}" "${additional_module_use_folder}" "${queues_cfg}" "${extrae_with_openmpi}" "${openmpi_version}" "${extrae_with_impi}" "${impi_version}" "${autoparallel}" "${c_binding}" "${extrae_no_mpi}" "{r_binding}"
  ev=$?

  # End
  if [ $ev -ne 0 ]; then
    echo "ERROR: Exception in auxiliar script"
    exit $ev
  fi
  exit 0
