#!/bin/bash -e

  #############################################################
  # Name: buildNextgenio_aux
  # Description: SCRIPT FOR LOCAL COMPSs BUILD in Nextgenio
  # Parameters: <targetDir> Base Target Installation folder
  #
  # ATTENTION: DO NOT EXECUTE THIS FILE. IT IS AUTOMATICALLY
  #            EXECUTED FROM buildNextgenio script
  #############################################################

  usage() {
    echo "Incorrect number of parameters"
    echo " Usage: buildNextgenio_aux <FullTargetPath>"
    echo " "
    exit 1
  }

  ####################
  # MAIN
  ####################
  # Get parameters
  if [ $# -ne 1 ]; then
    usage
  fi

  # SET SCRIPT VARIABLES
  targetDir=$1
  SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

  modules="packages-nextgenio intel/19.0.3.199 openmpi/1.10.7 gnu8/8.3.0 boost/1.66.0 py2-numpy/1.15.3"
  py2_modules="py2-numpy/1.15.3"
  py3_modules="ignore"
  additionalExports="export BOOST_CPPFLAGS=-I${BOOST_INC} BOOST_HOME=${BOOST_DIR} JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-0.el7_5.x86_64/ MPICC=/opt/ohpc/pub/mpi/openmpi-intel/1.10.7/bin/mpicc"
  queues_cfg="nextgenio.cfg"
  extrae_with_openmpi="true"
  openmpi_version="/1.10.7"
  extrae_with_impi="false"
  impi_version=""

  "${SCRIPT_DIR}"/buildSC_aux "${targetDir}" "${modules}" "${py2_modules}" "${py3_modules}" "${additionalExports}" "${queues_cfg}" "${extrae_with_openmpi}" "${openmpi_version}" "${extrae_with_impi}" "${impi_version}" "false"
