#!/bin/bash -e

  #############################################################
  # Name: buildNextgenio_aux
  # Description: SCRIPT FOR LOCAL COMPSs BUILD in Nextgenio
  # Parameters: <targetDir> Base Target Installation folder
  #
  # ATTENTION: DO NOT EXECUTE THIS FILE. IT IS AUTOMATICALLY
  #            EXECUTED FROM buildNextgenio script
  #############################################################

  usage() {
    echo "Incorrect number of parameters"
    echo " Usage: buildNextgenio_aux <FullTargetPath>"
    echo " "
    exit 1
  }

  ####################
  # MAIN
  ####################
  # Get parameters
  if [ $# -ne 1 ]; then
    usage
  fi

  # SET SCRIPT VARIABLES
  targetDir=$1
  SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

  modules="intel/19.0.3.199 py2-numpy/1.15.3 impi/2019.3.199 gnu8/8.3.0 boost/1.69.0"
  py2_modules="py2-numpy/1.15.3"
  py3_modules="ignore"
  additionalExports="export BOOST_CPPFLAGS=-I${BOOST_INC} BOOST_HOME=${BOOST_DIR}" #PATH=/usr/include/libxml2/libxml:$PATH"
  #additionalExports="$PATH"
  #additionalExports="export LD_LIBRARY_PATH=/opt/intel/compilers_and_libraries_2019.3.199/linux/mpi/intel64/lib:$LD_LIBRARY_PATH"
  queues_cfg="nextgenio.cfg"
  extrae_with_openmpi="false"
  openmpi_version=""
  extrae_with_impi="false"
  impi_version=""

  "${SCRIPT_DIR}"/buildSC_aux "${targetDir}" "${modules}" "${py2_modules}" "${py3_modules}" "${additionalExports}" "${queues_cfg}" "${extrae_with_openmpi}" "${openmpi_version}" "${extrae_with_impi}" "${impi_version}" "false"
