#!/bin/bash -e

  action=$1

  if [ "$action" == "install" ]; then
    if [ $# -eq 2 ]; then
      # Installation knowing previous old version
      oldversion=$2
      echo " "
      echo " * Installing COMPSs Python Binding from previous version ${oldversion}..."
      echo " "
      rm -rf /opt/COMPSs/Bindings/python
    else
      # Clean installation
      echo " "
      echo " * Installing COMPSs Python Binding..."
      echo " "
    fi
  elif [ "$action" == "upgrade" ]; then
    # Upgrade from previous version
    oldversion=$2
    echo " "
    echo " * Upgrading COMPSs Python Binding from previous version ${oldversion}..."
    echo " "
    if [ -d "opt/COMPSs/Bindings/python" ]; then
      mv /opt/COMPSs/Bindings/python /tmp/COMPSs_python_binding.bkp
    fi
  elif [ "$action" == "abort-upgrade" ]; then
    # Update failed, recover previous version
    newversion=$2
    echo " "
    echo " * COMPSs Python Binding $newversion upgrade aborted. Please check errors above."
    echo " "
    if [ -d "/tmp/COMPSs_python_binding.bkp" ]; then
      mv /tmp/COMPSs_python_binding.bkp /opt/COMPSs/Bindings/python
    fi
  fi

