#!/bin/bash -e
  
  # Obtain parameter
  source_base_dir=$1
  target_base_dir=$2

  # Copy files
  cp "${source_base_dir}"/execution "${target_base_dir}"/execution
  cp "${source_base_dir}"/result "${target_base_dir}"/result

  cp -r "${source_base_dir}"/src "${target_base_dir}"

  cp "${source_base_dir}"/project.xml "${target_base_dir}"/project.xml
  cp "${source_base_dir}"/resources.xml "${target_base_dir}"/resources.xml

  # Deplot the WS

  mvn -f ${source_base_dir}/../pom.xml clean install

  ws_jar="ws-jar-with-dependencies.jar"

  cp "${source_base_dir}"/ws/target/${ws_jar} "${target_base_dir}"/ws.jar
  chmod +x "${target_base_dir}"/ws.jar