#!/bin/bash

  # Obtain parameters
  COMPSs_exec=$1
  comm=$2
  runcompss_opts=$3
  base_app_dir=$4
  COMPSs_log_folder=$5
  target_log_folder=$6
  retry_num=$7
  execution_envs=$8

  # Global variables
  exit_value=1
  app_name="http_tasks.py"
  ws_jar_name="ws.jar"

  #----------------------------------------------------------------------------------
  # Generate Project.xml according to system
  sed -i '/<InstallDir>/c<InstallDir>'"${COMPSS_HOME}"'<\/InstallDir>' "${base_app_dir}"/project.xml

  #----------------------------------------------------------------------------------
  # Create all working dir folders
  mkdir -p /tmp/COMPSsWorker01/

  #----------------------------------------------------------------------------------
  echo "*** STARTING THE WEB SERVICE"
  java -jar ${ws_jar_name} &
  ws_pid="$!"
  sleep 2

  check_ws="$(curl -XGET http://localhost:1992/test/dummy 2>/dev/null)"

  if [ "$check_ws" == "it_works" ]; then
    echo
    echo "*** WEB SERVICE RUNNING WITH PID: ${ws_pid}"
  else
    kill -9 ${ws_pid}
    echo " Cannot start Web Service"
    exit 1
  fi

  #----------------------------------------------------------------------------------
  # Run application
  echo
  echo "*** RUNNING PYTHON APPLICATION FILES"

  for python_interpreter in ${execution_envs}; do
    echo "   - Running with Interpreter: ${python_interpreter}"
    output_log="${target_log_folder}/${app_name}_${python_interpreter}_0${retry_num}.outputlog"
    error_log="${target_log_folder}/${app_name}_${python_interpreter}_0${retry_num}.errorlog"
    specific_log_dir="${COMPSs_log_folder}/${app_name}_${python_interpreter}_0${retry_num}"
    exec_target_log_folder="${target_log_folder}/${app_name}_${python_interpreter}_0${retry_num}"
    mkdir -p "${exec_target_log_folder}"
    expectedTime=80s

    python_mpi_worker=""
    if [ "$python_interpreter" == 'python3_mpi' ]; then
       echo "WARN: Test not requiered for ${python_interpreter}" | tee -a "${output_log}"
       continue
    fi

    # shellcheck disable=SC2086
    timeout --signal=2 $expectedTime "${COMPSs_exec}" \
      --project="${base_app_dir}"/project.xml \
      --resources="${base_app_dir}"/resources.xml \
      \
      --comm="$comm" \
      \
      --debug \
      ${runcompss_opts} \
      \
      --lang=python \
      --python_interpreter="${python_interpreter}" \
      ${python_mpi_worker} \
      --pythonpath="${base_app_dir}"/src \
      --specific_log_dir="${specific_log_dir}" \
      \
      "${base_app_dir}/src/${app_name}" > >(tee "${output_log}") 2> >(tee "${error_log}" >&2)

    # Check timeout
    if [[ "$?" = "124" ]]; then
      # Copy LOG files
      cp -rf "${specific_log_dir}"/* "${exec_target_log_folder}"

      # Report time out
      echo "[WARNING] Python Application timed out" >> "${output_log}"
      exit_value=124
    else
      # Copy LOG files
      cp -rf "${specific_log_dir}"/* "${exec_target_log_folder}"

      # Check result
      "${base_app_dir}"/result "${output_log}" "${error_log}" "${exec_target_log_folder}" "${base_app_dir}"
      exit_value=$?
    fi

    if [ ${exit_value} -ne 0 ]; then

      #----------------------------------------------------------------------------------
      echo "*** STOPPING THE WEB SERVICE"
      kill -9 ${ws_pid}
      echo "*** WEB SERVICE HAS BEEN STOPPED:"
      exit ${exit_value}
    fi
  done

  #----------------------------------------------------------------------------------
  echo "*** STOPPING THE WEB SERVICE"
  kill -9 ${ws_pid}
  echo "*** WEB SERVICE HAS BEEN STOPPED:"

  #----------------------------------------------------------------------------------
  # Return execution status
  exit ${exit_value}
