#!/bin/bash -e
  
  # Obtain parameter
  source_base_dir=$1
  target_base_dir=$2
    
  # Copy files
  cp "${source_base_dir}"/execution "${target_base_dir}"/execution
  cp "${source_base_dir}"/result "${target_base_dir}"/result

  cp "${source_base_dir}"/project.xml "${target_base_dir}"/project.xml
  cp "${source_base_dir}"/resources.xml "${target_base_dir}"/resources.xml

  cp -r "${source_base_dir}"/src "${target_base_dir}"/src
  cp "${source_base_dir}"/Matmul.cc "${target_base_dir}"/Matmul.cc
  cp "${source_base_dir}"/Matmul-functions.cc "${target_base_dir}"/Matmul-functions.cc
  cp "${source_base_dir}"/Matmul.idl "${target_base_dir}"/Matmul.idl
