#!/bin/bash -e

  #############################################################
  # Name: buildMT_aux
  # Description: SCRIPT FOR LOCAL COMPSs BUILD in MinoTauro
  # Parameters: <targetDir> Base Target Installation folder
  #
  # ATTENTION: DO NOT EXECUTE THIS FILE. IT IS AUTOMATICALLY
  #            EXECUTED FROM buildMT script
  #############################################################

  usage() {
    echo "Incorrect number of parameters"
    echo " Usage: buildUV_aux <FullTargetPath>"
    echo " "
    exit 1
  }

  ####################
  # MAIN
  ####################
  # Get parameters
  if [ $# -ne 1 ]; then
    usage
  fi

  # SET SCRIPT VARIABLES
  targetDir=$1
  SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

  # DEFINE MODULES
  modules="autoconf autotools java intel python boost"
  unload_before_python="ignore"
  py2_modules="python"
  py3_modules=""
  py3_other_modules="ignore"

  # DEFINE CONFIGURATION PARAMETERS
  additionalExports="export BOOST_CPPFLAGS=-I/apps/BOOST/1.49.0/include PATH=/apps/COMPSs/deps/libxml2/2.9.4/bin:$PATH"
  additional_module_use_folder="ignore"
  queues_cfg="uv.cfg"
  extrae_with_openmpi="true"
  openmpi_version=""
  extrae_with_impi="false"
  impi_version=""
  autoparallel="false"

  # CALL buildSC_aux
  "${SCRIPT_DIR}"/buildSC_aux "${targetDir}" "${modules}" "${unload_before_python}" "${py2_modules}" "${py3_modules}" "${py3_other_modules}" "${additionalExports}" "${additional_module_use_folder}" "${queues_cfg}" "${extrae_with_openmpi}" "${openmpi_version}" "${extrae_with_impi}" "${impi_version}" "${autoparallel}"
  ev=$?

  # End
  if [ $ev -ne 0 ]; then
    echo "ERROR: Exception in auxiliar script"
    exit $ev
  fi
  exit 0
