#!/bin/bash -e 
 
  #############################################################
  # Name: buildMT
  # Description: SCRIPT FOR Ultraviolet COMPSs BUILD
  # Parameters: <MT_user> Ultraviolet user account. Preferable with ssh keys inserted
  #             <FullTmpPath> Tmp path on Ultraviolet for deployment
  #             <FullTargetPath> Base Target Installation folder on Ultraviolet
  #############################################################

  ####################
  # FUNCTIONS
  ####################
  usage() {
    echo " Usage: buildUV <UV_user> <FullTmpPath> <FullTargetPath>"
    echo " "
  }


  ####################
  # MAIN
  ####################
  # Get parameters
  if [ $# -eq 1 ]; then
    if [ "$1" == "usage" ]; then
      usage
      exit 0
    fi
  fi
  if [ $# -ne 3 ]; then
    echo "Incorrect number of parameters"
    usage
    exit 1
  fi

  # SET SCRIPT VARIABLES
  scriptDir=$(pwd)/$(dirname $0)

  MTuser=$1
  MTtmpDir=$2
  MTtargetDir=$3
  MTloginNode=bscsmp02.bsc.es
  MTauxScript=${scriptDir}/buildUV_aux
  PRELOAD_ENV=""

  # Perform installation
  cd ${scriptDir}/../commons
  ./buildSC ${MTuser} ${MTloginNode} ${MTtmpDir} ${MTtargetDir} ${MTauxScript} "${PRELOAD_ENV}"
  exitStatus=$?
  cd ${scriptDir}

  # END
  exit $exitStatus

