#!/bin/bash -e

  #############################################################
  # Name: buildMT_aux
  # Description: SCRIPT FOR LOCAL COMPSs BUILD in MinoTauro
  # Parameters: <targetDir> Base Target Installation folder
  #
  # ATTENTION: DO NOT EXECUTE THIS FILE. IT IS AUTOMATICALLY
  #            EXECUTED FROM buildMT script
  #############################################################

  usage() {
    echo "Incorrect number of parameters"
    echo " Usage: buildUV_aux <FullTargetPath>"
    echo " "
    exit 1
  }

  ####################
  # MAIN
  ####################
  # Get parameters
  if [ $# -ne 1 ]; then
    usage
  fi

  # SET SCRIPT VARIABLES
  targetDir=$1
  SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

  modules="autoconf autotools java intel python boost"
  py2_modules="python"
  py3_modules=""
  additionalExports="export BOOST_CPPFLAGS=-I/apps/BOOST/1.49.0/include PATH=/apps/COMPSs/deps/libxml2/2.9.4/bin:$PATH"
  queues_cfg="uv.cfg"
  extrae_with_openmpi="true"
  openmpi_version=""
  extrae_with_impi="false"
  impi_version=""

  "${SCRIPT_DIR}"/buildSC_aux "${targetDir}" "${modules}" "${py2_modules}" "${py3_modules}" "${additionalExports}" "${queues_cfg}" "${extrae_with_openmpi}" "${openmpi_version}" "${extrae_with_impi}" "${impi_version}" "false"
