#!/bin/bash

  #Get Parameters
  source_base_dir=$1
  actual_dir=$(pwd)/$(dirname $0)

  #Compile
  cd ${source_base_dir}/basic
  echo "---- Compiling java sources"
  mvn -U clean install
  
  #Check errors
  if [ $? -ne 0 ]; then
     echo "ERROR: CANNOT COMPILE JAVA APPS"
     exit 1
  fi
 
  #Go to main folder
  cd ${actual_dir}

  #Exit all ok
  exit 0

