#!/bin/bash

  # Get Parameters
  source_base_dir=$1
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

  # Compile
  cd "${source_base_dir}/basic" || exit 1

  echo "---- Compiling java sources"
  mvn -U clean install  
  # Check errors
  if [ $? -ne 0 ]; then
     echo "ERROR: CANNOT COMPILE JAVA APPS"
     exit 1
  fi
 
  # Go to main folder
  cd "${SCRIPT_DIR}" || exit 1

  # Exit all ok
  exit 0

