#!/bin/bash

  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

  # Backup hosts
  echo "** Creating a backup file"
  cp -f /etc/hosts "${SCRIPT_DIR}"/hosts.backup

  #Setup hosts
  echo "** Inserting new hosts on /etc/hosts"

cat >> /etc/hosts <<EOT
127.0.0.1        COMPSsWorker01
127.0.0.1        COMPSsWorker02
127.0.0.1        COMPSsWorker03
127.0.0.1        COMPSsWorker04
127.0.0.1        COMPSsWorker05
127.0.0.1        COMPSsWorker06
127.0.0.1        COMPSsWorker07
127.0.0.1        COMPSsWorker08
127.0.0.1        COMPSsWorker09
127.0.0.1        COMPSsWorker10
127.0.0.1        COMPSsWorker11
127.0.0.1        COMPSsWorker12
127.0.0.1        COMPSsWorker13
127.0.0.1        COMPSsWorker14
127.0.0.1        COMPSsWorker15
127.0.0.1        COMPSsWorker16
127.0.0.1        COMPSsWorker17
127.0.0.1        COMPSsWorker18
127.0.0.1        COMPSsWorker19
127.0.0.1        COMPSsWorker20
EOT

  # Prompt result
  echo "All done. Status OK"
  exit 0

