#!/bin/bash -e
    sources_dir=$1
    target_dir=$2
    log_dir=$3
    cloud_owner=$4
    connector_server=$5
    connector_class=$6

    #Erase current deployment
    echo "---- Erasing current deployment"
    rm -rf ${target_dir}
    
    #Create new deployment structure
    echo "---- Creating new deployment structure"
    mkdir ${target_dir}
    mkdir ${target_dir}/apps_cloud
    mkdir ${log_dir}
 
    #Deploy scripts
    echo "---- Deploying main scripts for execution"
    cp -f ${sources_dir}/../../scripts/execute_cloud_bscgrid20_tests ${target_dir}/execute_cloud_tests
   
    #TEST CLOUD BLOCK APPS
    echo "---- Deploying Cloud Block Apps"
    cloud_app_folders=$(ls ${sources_dir})
    counter=1
    for app in $cloud_app_folders; do
       if [ "$app" != "pom.xml" ]; then
          if [ $counter -lt 10 ]; then
             target="${target_dir}/apps_cloud/app0$counter"
          else
             target="${target_dir}/apps_cloud/app$counter"
          fi
          mkdir $target
          ${sources_dir}/$app/deploy "${sources_dir}/$app" $target ${cloud_owner}

          projects=$(ls ${target} | grep -s project | cat)
          for proj in $projects; do
             sed -i '/<InstallDir>remote_COMPSs<\/InstallDir>/c<InstallDir>\/opt\/COMPSs\/<\/InstallDir>' ${target}/${proj}
          done
          resources=$(ls ${target} | grep -s resources | cat)   
          for res in $resources; do   
             sed -i '/<Server>/c<Server>'${connector_server}'<\/Server>' ${target}/${res}
             sed -i '/<Connector>/c<Connector>'${connector_class}'<\/Connector>' ${target}/${res}
          done
          counter=$((counter+1))
       fi
    done

