#!/bin/bash -e

  # Define Global Variables
  source_base_dir=$1
  target_base_dir=$2

  # Erase current deployment
  echo "---- Erasing current deployment"
  rm -rf "${target_base_dir}"
   
  # Create new deployment structure
  echo "---- Creating new deployment structure"
  mkdir -p "${target_base_dir}"/logs

  # TEST APPS
  echo "---- Deploying Developpement Apps"
  counter=1
  for path in "${source_base_dir}"/*; do
    app=$(basename "$path")
    if [ "$app" != "pom.xml" ]; then
      if [ "$counter" -lt 10 ]; then
        target="${target_base_dir}/app0$counter"
      else
        target="${target_base_dir}/app$counter"
      fi
      mkdir "$target"
      "${source_base_dir}"/"$app"/deploy "${source_base_dir}/$app" "$target"
      counter=$((counter+1))
    fi
  done

