#!/bin/bash -e

  deploy_distribution() {
    local script_dir=$(dirname $0)
    local distr=$1
    local deployment_folder=$WORKSPACE/test_$distr
    local connector_server="https://bscgrid20.bsc.es:11443/"
    local connector_class="integratedtoolkit.connectors.rocci.ROCCI"

    #Erase current deployment
    echo "---- Erasing current deployment"
    rm -rf ${deployment_folder}
    
    #Create new deployment structure
    echo "---- Creating new deployment structure"
    mkdir ${deployment_folder}
    mkdir ${deployment_folder}/apps_cloud
    mkdir ${deployment_folder}/logs

    #Deploy scripts
    echo "---- Deploying main scripts for execution"
    cp ${script_dir}/execute_cloud_block2 ${deployment_folder}/execute_cloud
    cp ${script_dir}/configure_hosts_insert ${deployment_folder}/configure_hosts_insert

    #Sed default scripts values depending on base distribution
    if [ "$distr" == "centos" ]; then
       sed -i 's/JAVA_HOME\=\/usr\/lib\/jvm\/default\-java/JAVA_HOME\=\/usr\/lib\/jvm\/java\-1\.6\.0\-openjdk\.x86\_64/g' ${deployment_folder}/execute_cloud
    fi
   
    #TEST CLOUD BLOCK APPS
    echo "---- Deploying Cloud Block Apps"
    cloud_owner="jenkins-test"
    cloud_app_folders=$(ls ${script_dir}/../sources/cloud/)
    counter=1
    for app in $cloud_app_folders; do
       if [ "$app" != "pom.xml" ]; then
          if [ $counter -lt 10 ]; then
             target="${deployment_folder}/apps_cloud/app0$counter"
          else
             target="${deployment_folder}/apps_cloud/app$counter"
          fi
          mkdir $target
          ${script_dir}/../sources/cloud/$app/deploy "${script_dir}/../sources/cloud/$app" $target ${cloud_owner}

          projects=$(ls ${target} | grep -s project | cat)
          for proj in $projects; do
             sed -i '/<InstallDir>remote_COMPSs<\/InstallDir>/c<InstallDir>\/opt\/COMPSs\/Runtime\/scripts\/system<\/InstallDir>' ${target}/${proj}
          done
          resources=$(ls ${target} | grep -s resources | cat)   
          for res in $resources; do   
             sed -i '/<Server>/c<Server>'${connector_server}'<\/Server>' ${target}/${res}
             sed -i '/<Connector>/c<Connector>'${connector_server}'<\/Connector>' ${target}/${res}
          done

          counter=$((counter+1))
       fi
    done
  }

  #-----------------------------------------------------------------------------------------------------------------------------
  # MAIN PROGRAM
  #-----------------------------------------------------------------------------------------------------------------------------
  echo 
  echo "*** Deploying packages for UBUNTU"
  deploy_distribution "ubuntu"

  echo
  echo "*** Deploying packages for SUSE"
  deploy_distribution "suse"

  echo
  echo "*** Deploying packages for CENTOS"
  deploy_distribution "centos"

  echo
  echo "*** Deploying packages for DEBIAN"
  deploy_distribution "debian"

