#!/bin/bash

# Check if an image called 'compss' is available locally
if [ -z $(docker images -q compss) ]; then
    echo "Docker image 'compss' does not exist. Build it before trying to run the tests with:"
    echo "$ docker build -t compss ."
    echo "NOTE: the command should be run at the root of the repo."
    exit 1
fi

# Check if there is already a container named 'compss' running
if [ "$(docker ps | grep compss_test)" ]; then
    echo "COMPSs test container already running, reusing it. If you want to use a fresh container remove this one with:"
    echo "$ docker rm -f compss_test"
else
    # container can be stopped and give name conflict, so remove it just in case
    docker rm -f compss_test &> /dev/null  || true # no need to output errors if the container wasn't found
    docker run -d --name=compss_test -v "$(pwd)/../../":/framework compss
    while [ -z "$(docker ps | grep compss_test)" ]; do
        sleep 1 # just in case the container is not up yet 
    done
    docker exec compss_test sudo mvn clean --file /framework/tests/sources/pom.xml
    docker exec compss_test sudo /framework/tests/scripts/configure_hosts_insert
fi

docker exec compss_test /framework/tests/scripts/main "$@"
