#!/bin/bash

  #--------------------------------------------------------------------------------
  #Set global variables
  master_template_id=$1
  distr=$2
  cloud_owner=$3
  comm=$4

  user=user
  base_dir="/home/$user/tests"
  cloud_base_dir="${base_dir}/apps_cloud"
  COMPSs_exec="/opt/COMPSs/Runtime/scripts/user/runcompss"
  COMPSs_log_folder="/home/$user/.COMPSs"
  base_log_folder="$base_dir/logs"

  exitValue=0

  #--------------------------------------------------------------------------------
  if [ "$distr" == "ubuntu" ] || [ "$distr" == "debian" ]; then
    sudo sh -c "echo 'export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64/' >> /etc/profile"
    sudo sh -c "echo 'export IT_HOME=/opt/COMPSs/' >> /etc/profile"
    sudo update-java-alternatives -s java-1.7.0-openjdk-amd64
  else
    if [ "$distr" == "suse" ]; then
      sudo sh -c "echo 'export JAVA_HOME=/usr/lib64/jvm/java-openjdk/' >> /etc/profile"
      sudo sh -c "echo 'export IT_HOME=/opt/COMPSs/' >> /etc/profile"
    else
      if [ "$distr" == "centos" ]; then
        sudo sh -c "echo 'export JAVA_HOME=/usr/lib/jvm/java-openjdk/' >> /etc/profile"
        sudo sh -c "echo 'export IT_HOME=/opt/COMPSs/' >> /etc/profile"
      fi
    fi
  fi
  source /etc/profile

  #--------------------------------------------------------------------------------
  echo
  echo "**Testing Cloud Block Apps"
  appCounter=1
  results=""
  app_folders=$(ls ${cloud_base_dir})
  for app in ${app_folders}; do
      log_folder="${base_log_folder}/block2_$app"
      mkdir -p ${log_folder}
      cd ${cloud_base_dir}/$app
      ./execution ${COMPSs_exec} $comm "${cloud_base_dir}/$app" ${COMPSs_log_folder} ${log_folder} ${master_template_id} ${distr} ${cloud_owner}
      if [ $? -ne 0 ]; then
         exitValue=1
         results="${results}1"
      else
         results="${results}0"
      fi
      appCounter=$((appCounter+1))
      # Sleep to avoid interferences between tests
      sleep 1
  done

  #Show Result table
  counter=1
  pos=0
  echo
  echo -e "\e[34m------------------------------------------------------------------------"
  echo -e "\e[34m------------------------------------------------------------------------"
  echo -e "\e[34m   Application Name                                      TEST STATUS"
  while [ $counter -lt $appCounter ]; do
    if [ "${results:$pos:1}" == "0" ]; then
       echo -e "\e[34m [TEST RESULT] Application CLOUD BLOCK $counter ..................... \e[32mOK"
    else
       echo -e "\e[34m [TEST RESULT] Application CLOUD BLOCK $counter ..................... \e[31mERROR"
    fi
    counter=$((counter+1))
    pos=$((pos+1))
  done  
  echo -e "\e[34m"
  echo -e "\e[34m------------------------------------------------------------------------"
  echo -e "\e[34m------------------------------------------------------------------------" 
  echo -e "\e[34mIf there are errors, please check the WORKSPACE/logs/ files"
  echo -e "\e[0m"

  #--------------------------------------------------------------------------------
  #EXIT
  exit $exitValue

