#!/bin/bash

  #Get parameters
  tester_user=$1
  local_COMPSs=$2
  COMPSs_exec=$3
  comm=$4
  local_target_folder=$5
  local_log_folder=$6
  num_test=$7
  
  #Global variable to catch errors
  exitValue=0

  #-------------------------------------------------------------------------------------
  echo
  echo -e "\e[34m********************************"
  echo -e "\e[34m***  DEPLOYING ON BSCGRID20  ***"
  echo -e "\e[34m********************************"
  echo -e "\e[0m"

  bscgrid20_folder="tmp$RANDOM"
  bscgrid20_path="/home/${tester_user}/shared/${bscgrid20_folder}"
  
  #Log out structure for debug options
  echo "[LOG] bscgrid20 deployement: ${bscgrid20_folder}"  

  #Creating structure
  ssh -t -t -o StrictHostKeyChecking=no -o BatchMode=yes -o ChallengeResponseAuthentication=no ${tester_user}@bscgrid20.bsc.es "/home/jenkins/tests/specific/deploy_specific "$bscgrid20_path""
  if [ $? -ne 0 ]; then
     echo -e "\e[31m ERROR: CANNOT CREATE STRUCTURE ON BSCGRID20"
     echo -e "\e[31m        Verify your ssh connection to bscgrid20"
     echo -e "\e[0m"
     exitValue=1
     exit $exitValue
  fi 

  #Moving COMPSs 
  scp -r -o StrictHostKeyChecking=no ${local_COMPSs}/. ${tester_user}@bscgrid20.bsc.es:"${bscgrid20_path}/COMPSs"
  if [ $? -ne 0 ]; then
     echo -e "\e[31m ERROR: CANNOT DEPLOY YOUR CURRENT COMPSs"
     echo -e "\e[31m        Verify compss_location variable"
     echo -e "\e[0m"
     exitValue=2
     exit $exitValue
  fi

  #Moving compiled tests
  scp -r -o StrictHostKeyChecking=no ${local_target_folder}/* ${tester_user}@bscgrid20.bsc.es:"${bscgrid20_path}/tests/"
  if [ $? -ne 0 ]; then
     echo -e "\e[31m ERROR: CANNOT DEPLOY YOUR CLOUD TESTS"
     echo -e "\e[31m        Verify target_tests variable"
     echo -e "\e[0m"
     exitValue=3
     exit $exitValue
  fi 
 
  #-------------------------------------------------------------------------------------
  #Executing tests
  ssh -t -t -o StrictHostKeyChecking=no -o BatchMode=yes -o ChallengeResponseAuthentication=no ${tester_user}@bscgrid20.bsc.es "${bscgrid20_path}/scripts/main ${bscgrid20_folder} ${COMPSs_exec} ${comm} ${num_test}"
  if [ $? -ne 0 ]; then
     echo -e "\e[31m ERROR: TESTS EXECUTION NOT PASSED"
     echo -e "\e[31m        See errors above or log folder"
     echo -e "\e[0m"
     exitValue=4
  fi
 
  #-------------------------------------------------------------------------------------
  #Recovering logs
  echo
  echo -e "\e[34m**************************"
  echo -e "\e[34m*****  COPYING LOGS  *****"
  echo -e "\e[34m*****   (to local)   *****"
  echo -e "\e[34m**************************"
  echo -e "\e[0m"
  scp -r -o StrictHostKeyChecking=no ${tester_user}@bscgrid20.bsc.es:${bscgrid20_path}/logs/* ${local_log_folder}
  if [ $? -ne 0 ]; then
     exitValue=5
  fi

  #-------------------------------------------------------------------------------------
  #Erasing bscgrid20 deployment
  echo
  echo -e "\e[34m*****************************"
  echo -e "\e[34m*** REMOVING ON BSCGRID20 ***"
  echo -e "\e[34m*****************************"
  echo -e "\e[0m"
  ssh -t -t -o StrictHostKeyChecking=no -o BatchMode=yes -o ChallengeResponseAuthentication=no ${tester_user}@bscgrid20.bsc.es "/home/jenkins/tests/specific/undeploy_specific "$bscgrid20_path""
  if [ $? -ne 0 ]; then
     exitValue=6
  fi

  #-------------------------------------------------------------------------------------
  #Show up result status
  if [ $exitValue -eq 0 ]; then
     echo -e "\e[32m TESTS PASSED"
     echo -e "\e[32m   All tests with status OK. Check above."
     echo -e "\e[0m"
  else
     echo -e "\e[31m TESTS NOT PASSED"
     echo -e "\e[31m   Some test failed. Check above."
     echo -e "\e[0m"
  fi
  exit $exitValue   

