#!/bin/bash

  #--------------------------------------------------------------------------------
  # HELPER COMMON METHODS FOR TEST EXECUTION
  #--------------------------------------------------------------------------------


  #--------------------------------------------------------------------------------
  # Clean orphans
  clean_orphans() {
    # Sleep before cleanning test environment
    sleep 1s

    # Clean possible remaining test processes
    ps x -o  "%r %c" | grep "runcompss" | awk {' print $1 '} | xargs -r -i kill -9 -{}
    ps -elfa | grep "java" | grep "es.bsc.compss.nio.worker.NIOWorker" | awk {' print $4 '} | xargs -r kill -9
    ps -elfa | grep piper | grep -v grep | awk {' print $4 '} | xargs -r kill -9

    # Sleep after cleanning test environment
    sleep 1s
  }

  #--------------------------------------------------------------------------------
  # Check if a command exists
  command_exists () {
    type "$1" &> /dev/null ;
  }

  #--------------------------------------------------------------------------------
  # Compute test result status
  # WARN: Uses global variables --> OUT: results, testNames, exitValue
  get_test_result() {
    local appName=$1
    local testExitValue=$2
    local retries=$3

    testNames+=( ${appName} )

    if [ "$testExitValue" -ne 0 ]; then
      if [ "$testExitValue" -eq 88 ]; then
        # Partially supported feature reported by test
        results="${results}4"
      elif [ "$testExitValue" -eq 99 ]; then
        # Unsupported feature reported by test
        results="${results}5"
      else
        # Test failed
        exitValue=1
        results="${results}3"
      fi
    else
      if [ "$retries" -eq 2 ]; then
        # Test OK on first try (but counter was increased)
        results="${results}0"
      else
        results="${results}1"
      fi
    fi
  }


  #--------------------------------------------------------------------------------
  # Execute application
  # WARN: Uses global variables --> OUT: results, exitValue
  execute_application() {
    local COMPSsExec=$1
    local comm=$2
    local runcompss_opts=$3
    local summary_file=${4}
    local COMPSsLogFolder=$5
    local appBaseDir=$6
    local appLogDir=$7
    local skip=$8
    local MAX_RETRIES=$9
    local appName=${10}
    local pythonInterpreter=${11}

    if [ "${skip}" == "true" ] && [ -f "${appBaseDir}"/skip ]; then
      # Mark test as skip
      results="${results}2"
      testNames+=( ${appName} )
    else
      # Execute test with retries
      cd "${appBaseDir}"
      local retries=1
      local testExitValue=3
      while [ $retries -le $MAX_RETRIES ] && [ $testExitValue -ne 0 ]; do
        if [ -z "${pythonInterpreter}" ]; then
            local appLogDirWithRetries="${appLogDir}_${retries}"
        else
            local appLogDirWithRetries="${appLogDir}_${pythonInterpreter}_${retries}"
        fi
        mkdir -p "${appLogDirWithRetries}"

        # Specific test Execute
        ./execution ${COMPSsExec} ${comm} ${runcompss_opts} ${appBaseDir} ${COMPSsLogFolder} ${appLogDirWithRetries} ${retries} ${pythonInterpreter}
        testExitValue=$?

        # Clean environment if needed
        clean_orphans

        # Increase to next retry
        retries=$((retries + 1))
      done

      # Annotate test result
      get_test_result $appName $testExitValue $retries


      if [ "$testExitValue" -ne 0 ]; then
        if [ "$testExitValue" -eq 88 ]; then
          # Partially supported feature reported by test
          echo -e "[TEST RESULT] NAME ${appName} ..................... PARTIALLY SUPPORTED\n" >> "${summary_file}"
        elif [ "$testExitValue" -eq 99 ]; then
          # Unsupported feature reported by test
          echo -e "[TEST RESULT] NAME ${appName} ..................... UNSUPPORTED\n" >> "${summary_file}"
        else
          # Test failed
          echo -e "[TEST RESULT] NAME ${appName} ..................... ERROR\n" >> "${summary_file}"
        fi
      else
        if [ "$retries" -eq 2 ]; then
          # Test OK on first try (but counter was increased)
          echo -e "[TEST RESULT] NAME ${appName} ..................... OK\n" >> "${summary_file}"
        else
          echo -e "[TEST RESULT] NAME ${appName} ..................... OK with retries\n" >> "${summary_file}"
        fi
      fi
    fi
  }


  #--------------------------------------------------------------------------------
  # Print result
  print_result() {
    local execType=$1
    local results=$2

    # Show results table
    local numTests=${#results}
    local pos=0
    local appCounter=1

    # Header
    echo " "
    echo -e "\e[34m--------------------------------------------------------------------------------------------"
    echo -e "\e[34m--------------------------------------------------------------------------------------------"
    echo "   Application Name                                                               TEST STATUS"

    green=$"\033[32m"
    yellow=$"\033[33m"
    cyan=$"\033[36m"
    red=$"\033[31m"
    gray=$"\033[30m"
    normal=$"\033[0m"

    # Test results
    while [ $pos -lt "${numTests}" ]; do
      if [ $appCounter -lt 10 ]; then
        printCounter="0$appCounter"
      else
        printCounter="$appCounter"
      fi

      if [ "${results:$pos:1}" == "0" ]; then
         printf "${normal}%-60s %-20s ${green}%s\n" "[TEST RESULT] Application ${execType} BLOCK $printCounter NAME ${testNames[$pos]}" "....................." "OK"
      elif [ "${results:$pos:1}" == "1" ]; then
         printf "${normal}%-60s %-20s ${yellow}%s\n" "[TEST RESULT] Application ${execType} BLOCK $printCounter NAME ${testNames[$pos]}" "....................." "OK"
      elif [ "${results:$pos:1}" == "2" ]; then
         printf "${normal}%-60s %-20s ${cyan}%s\n" "[TEST RESULT] Application ${execType} BLOCK $printCounter NAME ${testNames[$pos]}" "....................." "SKIP"
      elif [ "${results:$pos:1}" == "4" ]; then
         printf "${normal}%-60s %-20s ${cyan}%s\n" "[TEST RESULT] Application ${execType} BLOCK $printCounter NAME ${testNames[$pos]}" "....................." "PARTIALLY SUPPORTED"
      elif [ "${results:$pos:1}" == "5" ]; then
         printf "${normal}%-60s %-20s ${gray}%s\n" "[TEST RESULT] Application ${execType} BLOCK $printCounter NAME ${testNames[$pos]}" "....................." "UNSUPPORTED"
      else
         printf "${normal}%-60s %-20s ${red}%s\n" "[TEST RESULT] Application ${execType} BLOCK $printCounter NAME ${testNames[$pos]}" "....................." "ERROR"
      fi
      pos=$((pos+1))
      appCounter=$((appCounter+1))
    done

    # Footer
    echo " "
    echo -e "\e[34m-----------------------------------------------------------------------"
    echo -e "\e[34m------------------------------------------------------------------------"
    echo -e "\e[34mIf there are errors, please check the WORKSPACE/logs/ files"
    echo -e "\e[0m"
  }

  #--------------------------------------------------------------------------------
  # Print Summary file header
  print_summary_header() {
    local summary_file=${1}
    echo -e "\n" >> "${summary_file}"
    echo -e "---------------------------------------------------------------------------------------------\n" >> "${summary_file}"
    echo -e "---------------------------------------------------------------------------------------------\n" >> "${summary_file}"
    echo -e "   Application Name                                                               TEST STATUS\n" >> "${summary_file}" 
  }

  #--------------------------------------------------------------------------------
  # Print Summary file footer
  print_summary_footer() {
    local summary_file=${1}
    echo -e "\n" >> "${summary_file}"
    echo -e "------------------------------------------------------------------------\n" >> "${summary_file}"
    echo -e "------------------------------------------------------------------------\n" >> "${summary_file}" 
    echo -e "If there are errors, please check the log files\n" >> "${summary_file}"
    echo -e "\n" >> "${summary_file}" 
  }