#!/bin/bash

  #--------------------------------------------------------------------------------
  # Get script parameters
  COMPSsExec=$1
  comm=$2
  runcompss_opts=$3
  baseDir=$4
  COMPSsLogFolder=$5
  skip=$6
  MAX_RETRIES=$7

  # Set script variables
  logsBaseDir="${baseDir}"/logs

  exitValue=0
  results=""

  #--------------------------------------------------------------------------------
  # Source common execution script
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  # shellcheck source=./execute_commons
  source "${SCRIPT_DIR}"/execute_commons

  #--------------------------------------------------------------------------------
  echo " "
  echo "**Testing Development Apps"
  echo " "

  for path in ${baseDir}/*; do
    app=$(basename "$path")
    if [ "$app" != "logs" ]; then
      appBaseDir="${baseDir}"/"${app}"
      appLogDir="${logsBaseDir}"/"${app}"

      execute_application "${COMPSsExec}" "${comm}" "${runcompss_opts}" "${COMPSsLogFolder}" "${appBaseDir}" "${appLogDir}" "${skip}" "${MAX_RETRIES}"
    fi
  done

  # Show Result table
  print_result "DEVELOPMENT" "$results"

  #--------------------------------------------------------------------------------
  # EXIT
  exit "$exitValue"

